/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ActivityItem
 */
export interface ActivityItem {
    /**
     * Opaque activity identifier; never a patient, case, or schedule identifier.
     * @type {string}
     * @memberof ActivityItem
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof ActivityItem
     */
    type: string;
    /**
     *
     * @type {string}
     * @memberof ActivityItem
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof ActivityItem
     */
    subtitle?: string;
    /**
     *
     * @type {Date}
     * @memberof ActivityItem
     */
    timestamp: Date;
    /**
     *
     * @type {string}
     * @memberof ActivityItem
     */
    to?: string;
    /**
     *
     * @type {string}
     * @memberof ActivityItem
     */
    severity?: string;
}

/**
 * Check if a given object implements the ActivityItem interface.
 */
export function instanceOfActivityItem(value: object): value is ActivityItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ActivityItemFromJSON(json: any): ActivityItem {
    return ActivityItemFromJSONTyped(json, false);
}

export function ActivityItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityItem {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'type': json['type'],
        'title': json['title'],
        'subtitle': json['subtitle'] == null ? undefined : json['subtitle'],
        'timestamp': (new Date(json['timestamp'])),
        'to': json['to'] == null ? undefined : json['to'],
        'severity': json['severity'] == null ? undefined : json['severity'],
    };
}

export function ActivityItemToJSON(json: any): ActivityItem {
    return ActivityItemToJSONTyped(json, false);
}

export function ActivityItemToJSONTyped(value?: ActivityItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'type': value['type'],
        'title': value['title'],
        'subtitle': value['subtitle'],
        'timestamp': value['timestamp'].toISOString(),
        'to': value['to'],
        'severity': value['severity'],
    };
}
