/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BillingHostedAction
 */
export interface BillingHostedAction {
    /**
     * Short-lived hosted Stripe destination for the current organization. Do not persist or share this URL.
     * @type {string}
     * @memberof BillingHostedAction
     */
    url: string;
    /**
     * 
     * @type {BillingHostedActionKindEnum}
     * @memberof BillingHostedAction
     */
    kind: BillingHostedActionKindEnum;
}


/**
 * @export
 */
export const BillingHostedActionKindEnum = {
    Checkout: 'checkout',
    Portal: 'portal'
} as const;
export type BillingHostedActionKindEnum = typeof BillingHostedActionKindEnum[keyof typeof BillingHostedActionKindEnum];


/**
 * Check if a given object implements the BillingHostedAction interface.
 */
export function instanceOfBillingHostedAction(value: object): value is BillingHostedAction {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    return true;
}

export function BillingHostedActionFromJSON(json: any): BillingHostedAction {
    return BillingHostedActionFromJSONTyped(json, false);
}

export function BillingHostedActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingHostedAction {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'kind': json['kind'],
    };
}

export function BillingHostedActionToJSON(json: any): BillingHostedAction {
    return BillingHostedActionToJSONTyped(json, false);
}

export function BillingHostedActionToJSONTyped(value?: BillingHostedAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'kind': value['kind'],
    };
}

