/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CallerContext
 */
export interface CallerContext {
    /**
     * Effective organization-scoped persona, evaluated from current grants.
     * @type {CallerContextPersonaEnum}
     * @memberof CallerContext
     */
    persona?: CallerContextPersonaEnum;
    /**
     * 
     * @type {string}
     * @memberof CallerContext
     */
    tenant_name?: string;
    /**
     * 
     * @type {string}
     * @memberof CallerContext
     */
    tenant_org_type?: string;
    /**
     * 
     * @type {string}
     * @memberof CallerContext
     */
    experience_tier?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CallerContext
     */
    available_workspaces?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CallerContext
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof CallerContext
     */
    tenant_id: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CallerContext
     */
    roles: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CallerContext
     */
    permissions: Array<string>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CallerContext
     */
    claims?: { [key: string]: any; };
}


/**
 * @export
 */
export const CallerContextPersonaEnum = {
    ClinicalStaff: 'clinical_staff',
    AdvancedClinicalStaff: 'advanced_clinical_staff',
    HospitalAdmin: 'hospital_admin',
    VendorFieldRep: 'vendor_field_rep',
    VendorManager: 'vendor_manager',
    VendorOrgAdmin: 'vendor_org_admin',
    PlatformAdmin: 'platform_admin'
} as const;
export type CallerContextPersonaEnum = typeof CallerContextPersonaEnum[keyof typeof CallerContextPersonaEnum];


/**
 * Check if a given object implements the CallerContext interface.
 */
export function instanceOfCallerContext(value: object): value is CallerContext {
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if (!('tenant_id' in value) || value['tenant_id'] === undefined) return false;
    if (!('roles' in value) || value['roles'] === undefined) return false;
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    return true;
}

export function CallerContextFromJSON(json: any): CallerContext {
    return CallerContextFromJSONTyped(json, false);
}

export function CallerContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): CallerContext {
    if (json == null) {
        return json;
    }
    return {
        
        'persona': json['persona'] == null ? undefined : json['persona'],
        'tenant_name': json['tenant_name'] == null ? undefined : json['tenant_name'],
        'tenant_org_type': json['tenant_org_type'] == null ? undefined : json['tenant_org_type'],
        'experience_tier': json['experience_tier'] == null ? undefined : json['experience_tier'],
        'available_workspaces': json['available_workspaces'] == null ? undefined : json['available_workspaces'],
        'subject': json['subject'],
        'tenant_id': json['tenant_id'],
        'roles': json['roles'],
        'permissions': json['permissions'],
        'claims': json['claims'] == null ? undefined : json['claims'],
    };
}

export function CallerContextToJSON(json: any): CallerContext {
    return CallerContextToJSONTyped(json, false);
}

export function CallerContextToJSONTyped(value?: CallerContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'persona': value['persona'],
        'tenant_name': value['tenant_name'],
        'tenant_org_type': value['tenant_org_type'],
        'experience_tier': value['experience_tier'],
        'available_workspaces': value['available_workspaces'],
        'subject': value['subject'],
        'tenant_id': value['tenant_id'],
        'roles': value['roles'],
        'permissions': value['permissions'],
        'claims': value['claims'],
    };
}

