/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CatalogVendor
 */
export interface CatalogVendor {
    /**
     * 
     * @type {string}
     * @memberof CatalogVendor
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogVendor
     */
    name: string;
}

/**
 * Check if a given object implements the CatalogVendor interface.
 */
export function instanceOfCatalogVendor(value: object): value is CatalogVendor {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CatalogVendorFromJSON(json: any): CatalogVendor {
    return CatalogVendorFromJSONTyped(json, false);
}

export function CatalogVendorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogVendor {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function CatalogVendorToJSON(json: any): CatalogVendor {
    return CatalogVendorToJSONTyped(json, false);
}

export function CatalogVendorToJSONTyped(value?: CatalogVendor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

