/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CatalogContentVisibilityPolicyEffect = {
    Allow: 'allow',
    Block: 'block'
} as const;
export type CatalogContentVisibilityPolicyEffect = typeof CatalogContentVisibilityPolicyEffect[keyof typeof CatalogContentVisibilityPolicyEffect];


export function instanceOfCatalogContentVisibilityPolicyEffect(value: any): boolean {
    for (const key in CatalogContentVisibilityPolicyEffect) {
        if (Object.prototype.hasOwnProperty.call(CatalogContentVisibilityPolicyEffect, key)) {
            if (CatalogContentVisibilityPolicyEffect[key as keyof typeof CatalogContentVisibilityPolicyEffect] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CatalogContentVisibilityPolicyEffectFromJSON(json: any): CatalogContentVisibilityPolicyEffect {
    return CatalogContentVisibilityPolicyEffectFromJSONTyped(json, false);
}

export function CatalogContentVisibilityPolicyEffectFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogContentVisibilityPolicyEffect {
    return json as CatalogContentVisibilityPolicyEffect;
}

export function CatalogContentVisibilityPolicyEffectToJSON(value?: CatalogContentVisibilityPolicyEffect | null): any {
    return value as any;
}

export function CatalogContentVisibilityPolicyEffectToJSONTyped(value: any, ignoreDiscriminator: boolean): CatalogContentVisibilityPolicyEffect {
    return value as CatalogContentVisibilityPolicyEffect;
}

