/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CatalogContentPublicationStatus = {
    Draft: 'draft',
    Published: 'published',
    Revoked: 'revoked'
} as const;
export type CatalogContentPublicationStatus = typeof CatalogContentPublicationStatus[keyof typeof CatalogContentPublicationStatus];


export function instanceOfCatalogContentPublicationStatus(value: any): boolean {
    for (const key in CatalogContentPublicationStatus) {
        if (Object.prototype.hasOwnProperty.call(CatalogContentPublicationStatus, key)) {
            if (CatalogContentPublicationStatus[key as keyof typeof CatalogContentPublicationStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CatalogContentPublicationStatusFromJSON(json: any): CatalogContentPublicationStatus {
    return CatalogContentPublicationStatusFromJSONTyped(json, false);
}

export function CatalogContentPublicationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogContentPublicationStatus {
    return json as CatalogContentPublicationStatus;
}

export function CatalogContentPublicationStatusToJSON(value?: CatalogContentPublicationStatus | null): any {
    return value as any;
}

export function CatalogContentPublicationStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): CatalogContentPublicationStatus {
    return value as CatalogContentPublicationStatus;
}

