/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CatalogContentVisibilityPolicyEffect } from './CatalogContentVisibilityPolicyEffect';
import {
    CatalogContentVisibilityPolicyEffectFromJSON,
    CatalogContentVisibilityPolicyEffectFromJSONTyped,
    CatalogContentVisibilityPolicyEffectToJSON,
    CatalogContentVisibilityPolicyEffectToJSONTyped,
} from './CatalogContentVisibilityPolicyEffect';
import type { CatalogContentType } from './CatalogContentType';
import {
    CatalogContentTypeFromJSON,
    CatalogContentTypeFromJSONTyped,
    CatalogContentTypeToJSON,
    CatalogContentTypeToJSONTyped,
} from './CatalogContentType';

/**
 * 
 * @export
 * @interface CatalogContentVisibilityPolicy
 */
export interface CatalogContentVisibilityPolicy {
    /**
     * 
     * @type {string}
     * @memberof CatalogContentVisibilityPolicy
     */
    id: string;
    /**
     * Authenticated recipient tenant scope; request bodies cannot override it.
     * @type {string}
     * @memberof CatalogContentVisibilityPolicy
     */
    hospital_organization_id: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogContentVisibilityPolicy
     */
    vendor_organization_id: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogContentVisibilityPolicy
     */
    product_id?: string | null;
    /**
     * 
     * @type {CatalogContentType}
     * @memberof CatalogContentVisibilityPolicy
     */
    content_type?: CatalogContentType;
    /**
     * 
     * @type {string}
     * @memberof CatalogContentVisibilityPolicy
     */
    content_item_id?: string | null;
    /**
     * 
     * @type {CatalogContentVisibilityPolicyEffect}
     * @memberof CatalogContentVisibilityPolicy
     */
    effect: CatalogContentVisibilityPolicyEffect;
    /**
     * 
     * @type {string}
     * @memberof CatalogContentVisibilityPolicy
     */
    reason?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogContentVisibilityPolicy
     */
    created_by_user_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CatalogContentVisibilityPolicy
     */
    updated_by_user_id?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CatalogContentVisibilityPolicy
     */
    date_added: Date;
    /**
     * 
     * @type {Date}
     * @memberof CatalogContentVisibilityPolicy
     */
    date_updated?: Date | null;
}



/**
 * Check if a given object implements the CatalogContentVisibilityPolicy interface.
 */
export function instanceOfCatalogContentVisibilityPolicy(value: object): value is CatalogContentVisibilityPolicy {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('hospital_organization_id' in value) || value['hospital_organization_id'] === undefined) return false;
    if (!('vendor_organization_id' in value) || value['vendor_organization_id'] === undefined) return false;
    if (!('effect' in value) || value['effect'] === undefined) return false;
    if (!('date_added' in value) || value['date_added'] === undefined) return false;
    return true;
}

export function CatalogContentVisibilityPolicyFromJSON(json: any): CatalogContentVisibilityPolicy {
    return CatalogContentVisibilityPolicyFromJSONTyped(json, false);
}

export function CatalogContentVisibilityPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogContentVisibilityPolicy {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'hospital_organization_id': json['hospital_organization_id'],
        'vendor_organization_id': json['vendor_organization_id'],
        'product_id': json['product_id'] == null ? undefined : json['product_id'],
        'content_type': json['content_type'] == null ? undefined : CatalogContentTypeFromJSON(json['content_type']),
        'content_item_id': json['content_item_id'] == null ? undefined : json['content_item_id'],
        'effect': CatalogContentVisibilityPolicyEffectFromJSON(json['effect']),
        'reason': json['reason'] == null ? undefined : json['reason'],
        'created_by_user_id': json['created_by_user_id'] == null ? undefined : json['created_by_user_id'],
        'updated_by_user_id': json['updated_by_user_id'] == null ? undefined : json['updated_by_user_id'],
        'date_added': (new Date(json['date_added'])),
        'date_updated': json['date_updated'] == null ? undefined : (new Date(json['date_updated'])),
    };
}

export function CatalogContentVisibilityPolicyToJSON(json: any): CatalogContentVisibilityPolicy {
    return CatalogContentVisibilityPolicyToJSONTyped(json, false);
}

export function CatalogContentVisibilityPolicyToJSONTyped(value?: CatalogContentVisibilityPolicy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'hospital_organization_id': value['hospital_organization_id'],
        'vendor_organization_id': value['vendor_organization_id'],
        'product_id': value['product_id'],
        'content_type': CatalogContentTypeToJSON(value['content_type']),
        'content_item_id': value['content_item_id'],
        'effect': CatalogContentVisibilityPolicyEffectToJSON(value['effect']),
        'reason': value['reason'],
        'created_by_user_id': value['created_by_user_id'],
        'updated_by_user_id': value['updated_by_user_id'],
        'date_added': value['date_added'].toISOString(),
        'date_updated': value['date_updated'] == null ? value['date_updated'] : value['date_updated'].toISOString(),
    };
}

