/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CatalogContentRecipientOrganization } from './CatalogContentRecipientOrganization';
import {
    CatalogContentRecipientOrganizationFromJSON,
    CatalogContentRecipientOrganizationFromJSONTyped,
    CatalogContentRecipientOrganizationToJSON,
    CatalogContentRecipientOrganizationToJSONTyped,
} from './CatalogContentRecipientOrganization';
import type { CatalogContentVisibilityPolicyEffect } from './CatalogContentVisibilityPolicyEffect';
import {
    CatalogContentVisibilityPolicyEffectFromJSON,
    CatalogContentVisibilityPolicyEffectFromJSONTyped,
    CatalogContentVisibilityPolicyEffectToJSON,
    CatalogContentVisibilityPolicyEffectToJSONTyped,
} from './CatalogContentVisibilityPolicyEffect';

/**
 * 
 * @export
 * @interface CatalogContentRecipient
 */
export interface CatalogContentRecipient {
    /**
     * 
     * @type {CatalogContentRecipientOrganization}
     * @memberof CatalogContentRecipient
     */
    organization: CatalogContentRecipientOrganization;
    /**
     * True when assignment and explicit policy evaluation make the recipient eligible before publication gating.
     * @type {boolean}
     * @memberof CatalogContentRecipient
     */
    eligible: boolean;
    /**
     * True when the recipient is eligible, the content is active, and the publication status permits hospital-side visibility.
     * @type {boolean}
     * @memberof CatalogContentRecipient
     */
    visible: boolean;
    /**
     * 
     * @type {CatalogContentVisibilityPolicyEffect}
     * @memberof CatalogContentRecipient
     */
    policy_effect?: CatalogContentVisibilityPolicyEffect;
    /**
     * Human-readable explanations such as direct product assignment, health-system inheritance, explicit allow/block policy specificity, and publication status.
     * @type {Array<string>}
     * @memberof CatalogContentRecipient
     */
    reasons: Array<string>;
}



/**
 * Check if a given object implements the CatalogContentRecipient interface.
 */
export function instanceOfCatalogContentRecipient(value: object): value is CatalogContentRecipient {
    if (!('organization' in value) || value['organization'] === undefined) return false;
    if (!('eligible' in value) || value['eligible'] === undefined) return false;
    if (!('visible' in value) || value['visible'] === undefined) return false;
    if (!('reasons' in value) || value['reasons'] === undefined) return false;
    return true;
}

export function CatalogContentRecipientFromJSON(json: any): CatalogContentRecipient {
    return CatalogContentRecipientFromJSONTyped(json, false);
}

export function CatalogContentRecipientFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogContentRecipient {
    if (json == null) {
        return json;
    }
    return {
        
        'organization': CatalogContentRecipientOrganizationFromJSON(json['organization']),
        'eligible': json['eligible'],
        'visible': json['visible'],
        'policy_effect': json['policy_effect'] == null ? undefined : CatalogContentVisibilityPolicyEffectFromJSON(json['policy_effect']),
        'reasons': json['reasons'],
    };
}

export function CatalogContentRecipientToJSON(json: any): CatalogContentRecipient {
    return CatalogContentRecipientToJSONTyped(json, false);
}

export function CatalogContentRecipientToJSONTyped(value?: CatalogContentRecipient | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization': CatalogContentRecipientOrganizationToJSON(value['organization']),
        'eligible': value['eligible'],
        'visible': value['visible'],
        'policy_effect': CatalogContentVisibilityPolicyEffectToJSON(value['policy_effect']),
        'reasons': value['reasons'],
    };
}

