/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VideoUploadInstructions } from './VideoUploadInstructions';
import {
    VideoUploadInstructionsFromJSON,
    VideoUploadInstructionsFromJSONTyped,
    VideoUploadInstructionsToJSON,
    VideoUploadInstructionsToJSONTyped,
} from './VideoUploadInstructions';
import type { VideoAsset } from './VideoAsset';
import {
    VideoAssetFromJSON,
    VideoAssetFromJSONTyped,
    VideoAssetToJSON,
    VideoAssetToJSONTyped,
} from './VideoAsset';

/**
 * 
 * @export
 * @interface CreateVideoResponse
 */
export interface CreateVideoResponse {
    /**
     * 
     * @type {VideoAsset}
     * @memberof CreateVideoResponse
     */
    video: VideoAsset;
    /**
     * 
     * @type {VideoUploadInstructions}
     * @memberof CreateVideoResponse
     */
    upload?: VideoUploadInstructions;
}

/**
 * Check if a given object implements the CreateVideoResponse interface.
 */
export function instanceOfCreateVideoResponse(value: object): value is CreateVideoResponse {
    if (!('video' in value) || value['video'] === undefined) return false;
    return true;
}

export function CreateVideoResponseFromJSON(json: any): CreateVideoResponse {
    return CreateVideoResponseFromJSONTyped(json, false);
}

export function CreateVideoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateVideoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'video': VideoAssetFromJSON(json['video']),
        'upload': json['upload'] == null ? undefined : VideoUploadInstructionsFromJSON(json['upload']),
    };
}

export function CreateVideoResponseToJSON(json: any): CreateVideoResponse {
    return CreateVideoResponseToJSONTyped(json, false);
}

export function CreateVideoResponseToJSONTyped(value?: CreateVideoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'video': VideoAssetToJSON(value['video']),
        'upload': VideoUploadInstructionsToJSON(value['upload']),
    };
}

