/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTrainingRequest
 */
export interface CreateTrainingRequest {
    /**
     * 
     * @type {CreateTrainingRequestRequestTypeEnum}
     * @memberof CreateTrainingRequest
     */
    request_type?: CreateTrainingRequestRequestTypeEnum;
    /**
     * Optional active rep supporting the selected product.
     * @type {string}
     * @memberof CreateTrainingRequest
     */
    preferred_rep_id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTrainingRequest
     */
    organization_id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTrainingRequest
     */
    product_id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTrainingRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTrainingRequest
     */
    message: string;
}


/**
 * @export
 */
export const CreateTrainingRequestRequestTypeEnum = {
    InPerson: 'in_person',
    Virtual: 'virtual',
    InService: 'in_service'
} as const;
export type CreateTrainingRequestRequestTypeEnum = typeof CreateTrainingRequestRequestTypeEnum[keyof typeof CreateTrainingRequestRequestTypeEnum];


/**
 * Check if a given object implements the CreateTrainingRequest interface.
 */
export function instanceOfCreateTrainingRequest(value: object): value is CreateTrainingRequest {
    if (!('product_id' in value) || value['product_id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CreateTrainingRequestFromJSON(json: any): CreateTrainingRequest {
    return CreateTrainingRequestFromJSONTyped(json, false);
}

export function CreateTrainingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTrainingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'request_type': json['request_type'] == null ? undefined : json['request_type'],
        'preferred_rep_id': json['preferred_rep_id'] == null ? undefined : json['preferred_rep_id'],
        'organization_id': json['organization_id'] == null ? undefined : json['organization_id'],
        'product_id': json['product_id'],
        'title': json['title'],
        'message': json['message'],
    };
}

export function CreateTrainingRequestToJSON(json: any): CreateTrainingRequest {
    return CreateTrainingRequestToJSONTyped(json, false);
}

export function CreateTrainingRequestToJSONTyped(value?: CreateTrainingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'request_type': value['request_type'],
        'preferred_rep_id': value['preferred_rep_id'],
        'organization_id': value['organization_id'],
        'product_id': value['product_id'],
        'title': value['title'],
        'message': value['message'],
    };
}

