/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EducationVersionDraft } from './EducationVersionDraft';
import {
    EducationVersionDraftFromJSON,
    EducationVersionDraftFromJSONTyped,
    EducationVersionDraftToJSON,
    EducationVersionDraftToJSONTyped,
} from './EducationVersionDraft';

/**
 * 
 * @export
 * @interface CreateEducationCourse
 */
export interface CreateEducationCourse {
    /**
     * 
     * @type {string}
     * @memberof CreateEducationCourse
     */
    product_id?: string;
    /**
     * 
     * @type {EducationVersionDraft}
     * @memberof CreateEducationCourse
     */
    version: EducationVersionDraft;
}

/**
 * Check if a given object implements the CreateEducationCourse interface.
 */
export function instanceOfCreateEducationCourse(value: object): value is CreateEducationCourse {
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function CreateEducationCourseFromJSON(json: any): CreateEducationCourse {
    return CreateEducationCourseFromJSONTyped(json, false);
}

export function CreateEducationCourseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEducationCourse {
    if (json == null) {
        return json;
    }
    return {
        
        'product_id': json['product_id'] == null ? undefined : json['product_id'],
        'version': EducationVersionDraftFromJSON(json['version']),
    };
}

export function CreateEducationCourseToJSON(json: any): CreateEducationCourse {
    return CreateEducationCourseToJSONTyped(json, false);
}

export function CreateEducationCourseToJSONTyped(value?: CreateEducationCourse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'product_id': value['product_id'],
        'version': EducationVersionDraftToJSON(value['version']),
    };
}

