/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateHospitalDepartmentRequest
 */
export interface CreateHospitalDepartmentRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateHospitalDepartmentRequest
     */
    name: string;
}

/**
 * Check if a given object implements the CreateHospitalDepartmentRequest interface.
 */
export function instanceOfCreateHospitalDepartmentRequest(value: object): value is CreateHospitalDepartmentRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateHospitalDepartmentRequestFromJSON(json: any): CreateHospitalDepartmentRequest {
    return CreateHospitalDepartmentRequestFromJSONTyped(json, false);
}

export function CreateHospitalDepartmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateHospitalDepartmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateHospitalDepartmentRequestToJSON(json: any): CreateHospitalDepartmentRequest {
    return CreateHospitalDepartmentRequestToJSONTyped(json, false);
}

export function CreateHospitalDepartmentRequestToJSONTyped(value?: CreateHospitalDepartmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

