/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrainingSessionDeliveryMode } from './TrainingSessionDeliveryMode';
import {
    TrainingSessionDeliveryModeFromJSON,
    TrainingSessionDeliveryModeFromJSONTyped,
    TrainingSessionDeliveryModeToJSON,
    TrainingSessionDeliveryModeToJSONTyped,
} from './TrainingSessionDeliveryMode';

/**
 * 
 * @export
 * @interface CreateTrainingSessionRequest
 */
export interface CreateTrainingSessionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateTrainingSessionRequest
     */
    source_request_id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTrainingSessionRequest
     */
    host_user_id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTrainingSessionRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTrainingSessionRequest
     */
    description?: string;
    /**
     * 
     * @type {TrainingSessionDeliveryMode}
     * @memberof CreateTrainingSessionRequest
     */
    delivery_mode: TrainingSessionDeliveryMode;
    /**
     * 
     * @type {Date}
     * @memberof CreateTrainingSessionRequest
     */
    starts_at: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateTrainingSessionRequest
     */
    ends_at: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateTrainingSessionRequest
     */
    location_text?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTrainingSessionRequest
     */
    external_join_url?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateTrainingSessionRequest
     */
    capacity?: number;
}



/**
 * Check if a given object implements the CreateTrainingSessionRequest interface.
 */
export function instanceOfCreateTrainingSessionRequest(value: object): value is CreateTrainingSessionRequest {
    if (!('source_request_id' in value) || value['source_request_id'] === undefined) return false;
    if (!('delivery_mode' in value) || value['delivery_mode'] === undefined) return false;
    if (!('starts_at' in value) || value['starts_at'] === undefined) return false;
    if (!('ends_at' in value) || value['ends_at'] === undefined) return false;
    return true;
}

export function CreateTrainingSessionRequestFromJSON(json: any): CreateTrainingSessionRequest {
    return CreateTrainingSessionRequestFromJSONTyped(json, false);
}

export function CreateTrainingSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTrainingSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'source_request_id': json['source_request_id'],
        'host_user_id': json['host_user_id'] == null ? undefined : json['host_user_id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'delivery_mode': TrainingSessionDeliveryModeFromJSON(json['delivery_mode']),
        'starts_at': (new Date(json['starts_at'])),
        'ends_at': (new Date(json['ends_at'])),
        'location_text': json['location_text'] == null ? undefined : json['location_text'],
        'external_join_url': json['external_join_url'] == null ? undefined : json['external_join_url'],
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
    };
}

export function CreateTrainingSessionRequestToJSON(json: any): CreateTrainingSessionRequest {
    return CreateTrainingSessionRequestToJSONTyped(json, false);
}

export function CreateTrainingSessionRequestToJSONTyped(value?: CreateTrainingSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source_request_id': value['source_request_id'],
        'host_user_id': value['host_user_id'],
        'title': value['title'],
        'description': value['description'],
        'delivery_mode': TrainingSessionDeliveryModeToJSON(value['delivery_mode']),
        'starts_at': value['starts_at'].toISOString(),
        'ends_at': value['ends_at'].toISOString(),
        'location_text': value['location_text'],
        'external_join_url': value['external_join_url'],
        'capacity': value['capacity'],
    };
}

