/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentRevisionInput
 */
export interface DocumentRevisionInput {
    /**
     * Language code for the vendor-supplied caption track.
     * @type {string}
     * @memberof DocumentRevisionInput
     */
    caption_language?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentRevisionInput
     */
    caption_label?: string;
    /**
     * Optional plain-text WebVTT captions, supplied by the vendor with this video revision.
     * @type {string}
     * @memberof DocumentRevisionInput
     */
    captions_vtt?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentRevisionInput
     */
    revision_label: string;
    /**
     * 
     * @type {Date}
     * @memberof DocumentRevisionInput
     */
    publication_date: Date;
    /**
     * 
     * @type {string}
     * @memberof DocumentRevisionInput
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentRevisionInput
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentRevisionInput
     */
    file_name: string;
    /**
     * 
     * @type {DocumentRevisionInputMediaTypeEnum}
     * @memberof DocumentRevisionInput
     */
    media_type: DocumentRevisionInputMediaTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof DocumentRevisionInput
     */
    byte_size: number;
    /**
     * 
     * @type {string}
     * @memberof DocumentRevisionInput
     */
    sha256: string;
}


/**
 * @export
 */
export const DocumentRevisionInputMediaTypeEnum = {
    ApplicationPdf: 'application/pdf',
    ImagePng: 'image/png',
    ImageJpeg: 'image/jpeg',
    VideoMp4: 'video/mp4',
    VideoQuicktime: 'video/quicktime',
    VideoWebm: 'video/webm'
} as const;
export type DocumentRevisionInputMediaTypeEnum = typeof DocumentRevisionInputMediaTypeEnum[keyof typeof DocumentRevisionInputMediaTypeEnum];


/**
 * Check if a given object implements the DocumentRevisionInput interface.
 */
export function instanceOfDocumentRevisionInput(value: object): value is DocumentRevisionInput {
    if (!('revision_label' in value) || value['revision_label'] === undefined) return false;
    if (!('publication_date' in value) || value['publication_date'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('file_name' in value) || value['file_name'] === undefined) return false;
    if (!('media_type' in value) || value['media_type'] === undefined) return false;
    if (!('byte_size' in value) || value['byte_size'] === undefined) return false;
    if (!('sha256' in value) || value['sha256'] === undefined) return false;
    return true;
}

export function DocumentRevisionInputFromJSON(json: any): DocumentRevisionInput {
    return DocumentRevisionInputFromJSONTyped(json, false);
}

export function DocumentRevisionInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentRevisionInput {
    if (json == null) {
        return json;
    }
    return {
        
        'caption_language': json['caption_language'] == null ? undefined : json['caption_language'],
        'caption_label': json['caption_label'] == null ? undefined : json['caption_label'],
        'captions_vtt': json['captions_vtt'] == null ? undefined : json['captions_vtt'],
        'revision_label': json['revision_label'],
        'publication_date': (new Date(json['publication_date'])),
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'file_name': json['file_name'],
        'media_type': json['media_type'],
        'byte_size': json['byte_size'],
        'sha256': json['sha256'],
    };
}

export function DocumentRevisionInputToJSON(json: any): DocumentRevisionInput {
    return DocumentRevisionInputToJSONTyped(json, false);
}

export function DocumentRevisionInputToJSONTyped(value?: DocumentRevisionInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'caption_language': value['caption_language'],
        'caption_label': value['caption_label'],
        'captions_vtt': value['captions_vtt'],
        'revision_label': value['revision_label'],
        'publication_date': value['publication_date'].toISOString().substring(0,10),
        'title': value['title'],
        'description': value['description'],
        'file_name': value['file_name'],
        'media_type': value['media_type'],
        'byte_size': value['byte_size'],
        'sha256': value['sha256'],
    };
}

