/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentRevision
 */
export interface DocumentRevision {
    /**
     * Language code for the vendor-supplied caption track.
     * @type {string}
     * @memberof DocumentRevision
     */
    caption_language?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentRevision
     */
    caption_label?: string;
    /**
     * Optional plain-text WebVTT captions, supplied by the vendor with this video revision.
     * @type {string}
     * @memberof DocumentRevision
     */
    captions_vtt?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentRevision
     */
    revision_label: string;
    /**
     * 
     * @type {Date}
     * @memberof DocumentRevision
     */
    publication_date: Date;
    /**
     * 
     * @type {string}
     * @memberof DocumentRevision
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentRevision
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentRevision
     */
    file_name: string;
    /**
     * 
     * @type {DocumentRevisionMediaTypeEnum}
     * @memberof DocumentRevision
     */
    media_type: DocumentRevisionMediaTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof DocumentRevision
     */
    byte_size: number;
    /**
     * 
     * @type {string}
     * @memberof DocumentRevision
     */
    sha256: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentRevision
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentRevision
     */
    content_id: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentRevision
     */
    organization_id: string;
    /**
     * 
     * @type {DocumentRevisionProcessingStateEnum}
     * @memberof DocumentRevision
     */
    processing_state: DocumentRevisionProcessingStateEnum;
    /**
     * 
     * @type {DocumentRevisionPublicationStateEnum}
     * @memberof DocumentRevision
     */
    publication_state: DocumentRevisionPublicationStateEnum;
    /**
     * 
     * @type {Date}
     * @memberof DocumentRevision
     */
    created_at: Date;
    /**
     * 
     * @type {Date}
     * @memberof DocumentRevision
     */
    published_at?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof DocumentRevision
     */
    withdrawn_at?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentRevision
     */
    withdrawal_reason?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentRevision
     */
    failure_reason?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentRevision
     */
    main_asset_name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DocumentRevision
     */
    duration_seconds?: number | null;
}


/**
 * @export
 */
export const DocumentRevisionMediaTypeEnum = {
    ApplicationPdf: 'application/pdf',
    ImagePng: 'image/png',
    ImageJpeg: 'image/jpeg',
    VideoMp4: 'video/mp4',
    VideoQuicktime: 'video/quicktime',
    VideoWebm: 'video/webm'
} as const;
export type DocumentRevisionMediaTypeEnum = typeof DocumentRevisionMediaTypeEnum[keyof typeof DocumentRevisionMediaTypeEnum];

/**
 * @export
 */
export const DocumentRevisionProcessingStateEnum = {
    AwaitingUpload: 'awaiting_upload',
    Uploading: 'uploading',
    Queued: 'queued',
    Processing: 'processing',
    Ready: 'ready',
    Failed: 'failed'
} as const;
export type DocumentRevisionProcessingStateEnum = typeof DocumentRevisionProcessingStateEnum[keyof typeof DocumentRevisionProcessingStateEnum];

/**
 * @export
 */
export const DocumentRevisionPublicationStateEnum = {
    Draft: 'draft',
    Published: 'published',
    Withdrawn: 'withdrawn'
} as const;
export type DocumentRevisionPublicationStateEnum = typeof DocumentRevisionPublicationStateEnum[keyof typeof DocumentRevisionPublicationStateEnum];


/**
 * Check if a given object implements the DocumentRevision interface.
 */
export function instanceOfDocumentRevision(value: object): value is DocumentRevision {
    if (!('revision_label' in value) || value['revision_label'] === undefined) return false;
    if (!('publication_date' in value) || value['publication_date'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('file_name' in value) || value['file_name'] === undefined) return false;
    if (!('media_type' in value) || value['media_type'] === undefined) return false;
    if (!('byte_size' in value) || value['byte_size'] === undefined) return false;
    if (!('sha256' in value) || value['sha256'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('content_id' in value) || value['content_id'] === undefined) return false;
    if (!('organization_id' in value) || value['organization_id'] === undefined) return false;
    if (!('processing_state' in value) || value['processing_state'] === undefined) return false;
    if (!('publication_state' in value) || value['publication_state'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    return true;
}

export function DocumentRevisionFromJSON(json: any): DocumentRevision {
    return DocumentRevisionFromJSONTyped(json, false);
}

export function DocumentRevisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentRevision {
    if (json == null) {
        return json;
    }
    return {
        
        'caption_language': json['caption_language'] == null ? undefined : json['caption_language'],
        'caption_label': json['caption_label'] == null ? undefined : json['caption_label'],
        'captions_vtt': json['captions_vtt'] == null ? undefined : json['captions_vtt'],
        'revision_label': json['revision_label'],
        'publication_date': (new Date(json['publication_date'])),
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'file_name': json['file_name'],
        'media_type': json['media_type'],
        'byte_size': json['byte_size'],
        'sha256': json['sha256'],
        'id': json['id'],
        'content_id': json['content_id'],
        'organization_id': json['organization_id'],
        'processing_state': json['processing_state'],
        'publication_state': json['publication_state'],
        'created_at': (new Date(json['created_at'])),
        'published_at': json['published_at'] == null ? undefined : (new Date(json['published_at'])),
        'withdrawn_at': json['withdrawn_at'] == null ? undefined : (new Date(json['withdrawn_at'])),
        'withdrawal_reason': json['withdrawal_reason'] == null ? undefined : json['withdrawal_reason'],
        'failure_reason': json['failure_reason'] == null ? undefined : json['failure_reason'],
        'main_asset_name': json['main_asset_name'] == null ? undefined : json['main_asset_name'],
        'duration_seconds': json['duration_seconds'] == null ? undefined : json['duration_seconds'],
    };
}

export function DocumentRevisionToJSON(json: any): DocumentRevision {
    return DocumentRevisionToJSONTyped(json, false);
}

export function DocumentRevisionToJSONTyped(value?: DocumentRevision | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'caption_language': value['caption_language'],
        'caption_label': value['caption_label'],
        'captions_vtt': value['captions_vtt'],
        'revision_label': value['revision_label'],
        'publication_date': value['publication_date'].toISOString().substring(0,10),
        'title': value['title'],
        'description': value['description'],
        'file_name': value['file_name'],
        'media_type': value['media_type'],
        'byte_size': value['byte_size'],
        'sha256': value['sha256'],
        'id': value['id'],
        'content_id': value['content_id'],
        'organization_id': value['organization_id'],
        'processing_state': value['processing_state'],
        'publication_state': value['publication_state'],
        'created_at': value['created_at'].toISOString(),
        'published_at': value['published_at'] == null ? value['published_at'] : value['published_at'].toISOString(),
        'withdrawn_at': value['withdrawn_at'] == null ? value['withdrawn_at'] : value['withdrawn_at'].toISOString(),
        'withdrawal_reason': value['withdrawal_reason'],
        'failure_reason': value['failure_reason'],
        'main_asset_name': value['main_asset_name'],
        'duration_seconds': value['duration_seconds'],
    };
}

