/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentWithdrawalRequest
 */
export interface DocumentWithdrawalRequest {
    /**
     * 
     * @type {string}
     * @memberof DocumentWithdrawalRequest
     */
    reason: string;
}

/**
 * Check if a given object implements the DocumentWithdrawalRequest interface.
 */
export function instanceOfDocumentWithdrawalRequest(value: object): value is DocumentWithdrawalRequest {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function DocumentWithdrawalRequestFromJSON(json: any): DocumentWithdrawalRequest {
    return DocumentWithdrawalRequestFromJSONTyped(json, false);
}

export function DocumentWithdrawalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentWithdrawalRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'],
    };
}

export function DocumentWithdrawalRequestToJSON(json: any): DocumentWithdrawalRequest {
    return DocumentWithdrawalRequestToJSONTyped(json, false);
}

export function DocumentWithdrawalRequestToJSONTyped(value?: DocumentWithdrawalRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
    };
}

