/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EducationCourse } from './EducationCourse';
import {
    EducationCourseFromJSON,
    EducationCourseFromJSONTyped,
    EducationCourseToJSON,
    EducationCourseToJSONTyped,
} from './EducationCourse';

/**
 * 
 * @export
 * @interface EducationCoursePage
 */
export interface EducationCoursePage {
    /**
     * 
     * @type {Array<EducationCourse>}
     * @memberof EducationCoursePage
     */
    items: Array<EducationCourse>;
    /**
     * 
     * @type {number}
     * @memberof EducationCoursePage
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof EducationCoursePage
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof EducationCoursePage
     */
    offset: number;
}

/**
 * Check if a given object implements the EducationCoursePage interface.
 */
export function instanceOfEducationCoursePage(value: object): value is EducationCoursePage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    return true;
}

export function EducationCoursePageFromJSON(json: any): EducationCoursePage {
    return EducationCoursePageFromJSONTyped(json, false);
}

export function EducationCoursePageFromJSONTyped(json: any, ignoreDiscriminator: boolean): EducationCoursePage {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(EducationCourseFromJSON)),
        'total': json['total'],
        'limit': json['limit'],
        'offset': json['offset'],
    };
}

export function EducationCoursePageToJSON(json: any): EducationCoursePage {
    return EducationCoursePageToJSONTyped(json, false);
}

export function EducationCoursePageToJSONTyped(value?: EducationCoursePage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(EducationCourseToJSON)),
        'total': value['total'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

