/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EducationLessonDraft
 */
export interface EducationLessonDraft {
    /**
     * 
     * @type {string}
     * @memberof EducationLessonDraft
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof EducationLessonDraft
     */
    body?: string;
    /**
     * Private document identifier, or empty for a text lesson.
     * @type {string}
     * @memberof EducationLessonDraft
     */
    document_id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EducationLessonDraft
     */
    acknowledgement_required: boolean;
}

/**
 * Check if a given object implements the EducationLessonDraft interface.
 */
export function instanceOfEducationLessonDraft(value: object): value is EducationLessonDraft {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('acknowledgement_required' in value) || value['acknowledgement_required'] === undefined) return false;
    return true;
}

export function EducationLessonDraftFromJSON(json: any): EducationLessonDraft {
    return EducationLessonDraftFromJSONTyped(json, false);
}

export function EducationLessonDraftFromJSONTyped(json: any, ignoreDiscriminator: boolean): EducationLessonDraft {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'body': json['body'] == null ? undefined : json['body'],
        'document_id': json['document_id'] == null ? undefined : json['document_id'],
        'acknowledgement_required': json['acknowledgement_required'],
    };
}

export function EducationLessonDraftToJSON(json: any): EducationLessonDraft {
    return EducationLessonDraftToJSONTyped(json, false);
}

export function EducationLessonDraftToJSONTyped(value?: EducationLessonDraft | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'body': value['body'],
        'document_id': value['document_id'],
        'acknowledgement_required': value['acknowledgement_required'],
    };
}

