/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventPublication
 */
export interface EventPublication {
    /**
     * 
     * @type {boolean}
     * @memberof EventPublication
     */
    published: boolean;
}

/**
 * Check if a given object implements the EventPublication interface.
 */
export function instanceOfEventPublication(value: object): value is EventPublication {
    if (!('published' in value) || value['published'] === undefined) return false;
    return true;
}

export function EventPublicationFromJSON(json: any): EventPublication {
    return EventPublicationFromJSONTyped(json, false);
}

export function EventPublicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventPublication {
    if (json == null) {
        return json;
    }
    return {
        
        'published': json['published'],
    };
}

export function EventPublicationToJSON(json: any): EventPublication {
    return EventPublicationToJSONTyped(json, false);
}

export function EventPublicationToJSONTyped(value?: EventPublication | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'published': value['published'],
    };
}

