/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeatureSettings
 */
export interface FeatureSettings {
    /**
     * 
     * @type {boolean}
     * @memberof FeatureSettings
     */
    billing_enabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FeatureSettings
     */
    native_rooms_enabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FeatureSettings
     */
    documents_enabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FeatureSettings
     */
    email_enabled: boolean;
}

/**
 * Check if a given object implements the FeatureSettings interface.
 */
export function instanceOfFeatureSettings(value: object): value is FeatureSettings {
    if (!('billing_enabled' in value) || value['billing_enabled'] === undefined) return false;
    if (!('native_rooms_enabled' in value) || value['native_rooms_enabled'] === undefined) return false;
    if (!('documents_enabled' in value) || value['documents_enabled'] === undefined) return false;
    if (!('email_enabled' in value) || value['email_enabled'] === undefined) return false;
    return true;
}

export function FeatureSettingsFromJSON(json: any): FeatureSettings {
    return FeatureSettingsFromJSONTyped(json, false);
}

export function FeatureSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'billing_enabled': json['billing_enabled'],
        'native_rooms_enabled': json['native_rooms_enabled'],
        'documents_enabled': json['documents_enabled'],
        'email_enabled': json['email_enabled'],
    };
}

export function FeatureSettingsToJSON(json: any): FeatureSettings {
    return FeatureSettingsToJSONTyped(json, false);
}

export function FeatureSettingsToJSONTyped(value?: FeatureSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'billing_enabled': value['billing_enabled'],
        'native_rooms_enabled': value['native_rooms_enabled'],
        'documents_enabled': value['documents_enabled'],
        'email_enabled': value['email_enabled'],
    };
}

