/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HospitalDepartment
 */
export interface HospitalDepartment {
    /**
     * 
     * @type {string}
     * @memberof HospitalDepartment
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof HospitalDepartment
     */
    name: string;
}

/**
 * Check if a given object implements the HospitalDepartment interface.
 */
export function instanceOfHospitalDepartment(value: object): value is HospitalDepartment {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function HospitalDepartmentFromJSON(json: any): HospitalDepartment {
    return HospitalDepartmentFromJSONTyped(json, false);
}

export function HospitalDepartmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): HospitalDepartment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function HospitalDepartmentToJSON(json: any): HospitalDepartment {
    return HospitalDepartmentToJSONTyped(json, false);
}

export function HospitalDepartmentToJSONTyped(value?: HospitalDepartment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

