/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface InsightsHighlight
 */
export interface InsightsHighlight {
    /**
     *
     * @type {string}
     * @memberof InsightsHighlight
     */
    key: string;
    /**
     *
     * @type {string}
     * @memberof InsightsHighlight
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof InsightsHighlight
     */
    subtitle?: string;
    /**
     *
     * @type {string}
     * @memberof InsightsHighlight
     */
    value?: string;
    /**
     *
     * @type {string}
     * @memberof InsightsHighlight
     */
    to?: string;
}

/**
 * Check if a given object implements the InsightsHighlight interface.
 */
export function instanceOfInsightsHighlight(value: object): value is InsightsHighlight {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function InsightsHighlightFromJSON(json: any): InsightsHighlight {
    return InsightsHighlightFromJSONTyped(json, false);
}

export function InsightsHighlightFromJSONTyped(json: any, ignoreDiscriminator: boolean): InsightsHighlight {
    if (json == null) {
        return json;
    }
    return {

        'key': json['key'],
        'title': json['title'],
        'subtitle': json['subtitle'] == null ? undefined : json['subtitle'],
        'value': json['value'] == null ? undefined : json['value'],
        'to': json['to'] == null ? undefined : json['to'],
    };
}

export function InsightsHighlightToJSON(json: any): InsightsHighlight {
    return InsightsHighlightToJSONTyped(json, false);
}

export function InsightsHighlightToJSONTyped(value?: InsightsHighlight | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'key': value['key'],
        'title': value['title'],
        'subtitle': value['subtitle'],
        'value': value['value'],
        'to': value['to'],
    };
}
