/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EducationVersion } from './EducationVersion';
import {
    EducationVersionFromJSON,
    EducationVersionFromJSONTyped,
    EducationVersionToJSON,
    EducationVersionToJSONTyped,
} from './EducationVersion';
import type { LearningEnrollment } from './LearningEnrollment';
import {
    LearningEnrollmentFromJSON,
    LearningEnrollmentFromJSONTyped,
    LearningEnrollmentToJSON,
    LearningEnrollmentToJSONTyped,
} from './LearningEnrollment';

/**
 * 
 * @export
 * @interface LearningDetail
 */
export interface LearningDetail {
    /**
     * 
     * @type {LearningEnrollment}
     * @memberof LearningDetail
     */
    enrollment: LearningEnrollment;
    /**
     * 
     * @type {EducationVersion}
     * @memberof LearningDetail
     */
    version: EducationVersion | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof LearningDetail
     */
    acknowledged_lesson_ids: Array<string>;
    /**
     * Lesson ID to the private document revision that must be reviewed before acknowledgement.
     * @type {{ [key: string]: string; }}
     * @memberof LearningDetail
     */
    document_revisions: { [key: string]: string; };
}

/**
 * Check if a given object implements the LearningDetail interface.
 */
export function instanceOfLearningDetail(value: object): value is LearningDetail {
    if (!('enrollment' in value) || value['enrollment'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('acknowledged_lesson_ids' in value) || value['acknowledged_lesson_ids'] === undefined) return false;
    if (!('document_revisions' in value) || value['document_revisions'] === undefined) return false;
    return true;
}

export function LearningDetailFromJSON(json: any): LearningDetail {
    return LearningDetailFromJSONTyped(json, false);
}

export function LearningDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearningDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'enrollment': LearningEnrollmentFromJSON(json['enrollment']),
        'version': EducationVersionFromJSON(json['version']),
        'acknowledged_lesson_ids': json['acknowledged_lesson_ids'],
        'document_revisions': json['document_revisions'],
    };
}

export function LearningDetailToJSON(json: any): LearningDetail {
    return LearningDetailToJSONTyped(json, false);
}

export function LearningDetailToJSONTyped(value?: LearningDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enrollment': LearningEnrollmentToJSON(value['enrollment']),
        'version': EducationVersionToJSON(value['version']),
        'acknowledged_lesson_ids': value['acknowledged_lesson_ids'],
        'document_revisions': value['document_revisions'],
    };
}

