/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LearningEnrollmentRequest
 */
export interface LearningEnrollmentRequest {
    /**
     * 
     * @type {string}
     * @memberof LearningEnrollmentRequest
     */
    version_id: string;
}

/**
 * Check if a given object implements the LearningEnrollmentRequest interface.
 */
export function instanceOfLearningEnrollmentRequest(value: object): value is LearningEnrollmentRequest {
    if (!('version_id' in value) || value['version_id'] === undefined) return false;
    return true;
}

export function LearningEnrollmentRequestFromJSON(json: any): LearningEnrollmentRequest {
    return LearningEnrollmentRequestFromJSONTyped(json, false);
}

export function LearningEnrollmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearningEnrollmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'version_id': json['version_id'],
    };
}

export function LearningEnrollmentRequestToJSON(json: any): LearningEnrollmentRequest {
    return LearningEnrollmentRequestToJSONTyped(json, false);
}

export function LearningEnrollmentRequestToJSONTyped(value?: LearningEnrollmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version_id': value['version_id'],
    };
}

