/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NativePresenterInput
 */
export interface NativePresenterInput {
    /**
     * 
     * @type {string}
     * @memberof NativePresenterInput
     */
    organization_id: string;
}

/**
 * Check if a given object implements the NativePresenterInput interface.
 */
export function instanceOfNativePresenterInput(value: object): value is NativePresenterInput {
    if (!('organization_id' in value) || value['organization_id'] === undefined) return false;
    return true;
}

export function NativePresenterInputFromJSON(json: any): NativePresenterInput {
    return NativePresenterInputFromJSONTyped(json, false);
}

export function NativePresenterInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): NativePresenterInput {
    if (json == null) {
        return json;
    }
    return {
        
        'organization_id': json['organization_id'],
    };
}

export function NativePresenterInputToJSON(json: any): NativePresenterInput {
    return NativePresenterInputToJSONTyped(json, false);
}

export function NativePresenterInputToJSONTyped(value?: NativePresenterInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization_id': value['organization_id'],
    };
}

