/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NativePresenter
 */
export interface NativePresenter {
    /**
     * 
     * @type {string}
     * @memberof NativePresenter
     */
    user_id: string;
    /**
     * 
     * @type {string}
     * @memberof NativePresenter
     */
    organization_id: string;
    /**
     * 
     * @type {boolean}
     * @memberof NativePresenter
     */
    is_host: boolean;
}

/**
 * Check if a given object implements the NativePresenter interface.
 */
export function instanceOfNativePresenter(value: object): value is NativePresenter {
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    if (!('organization_id' in value) || value['organization_id'] === undefined) return false;
    if (!('is_host' in value) || value['is_host'] === undefined) return false;
    return true;
}

export function NativePresenterFromJSON(json: any): NativePresenter {
    return NativePresenterFromJSONTyped(json, false);
}

export function NativePresenterFromJSONTyped(json: any, ignoreDiscriminator: boolean): NativePresenter {
    if (json == null) {
        return json;
    }
    return {
        
        'user_id': json['user_id'],
        'organization_id': json['organization_id'],
        'is_host': json['is_host'],
    };
}

export function NativePresenterToJSON(json: any): NativePresenter {
    return NativePresenterToJSONTyped(json, false);
}

export function NativePresenterToJSONTyped(value?: NativePresenter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['user_id'],
        'organization_id': value['organization_id'],
        'is_host': value['is_host'],
    };
}

