/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface NotificationItem
 */
export interface NotificationItem {
    /**
     *
     * @type {string}
     * @memberof NotificationItem
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof NotificationItem
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof NotificationItem
     */
    subtitle?: string;
    /**
     *
     * @type {Date}
     * @memberof NotificationItem
     */
    created_at: Date;
    /**
     *
     * @type {string}
     * @memberof NotificationItem
     */
    priority?: string;
    /**
     *
     * @type {string}
     * @memberof NotificationItem
     */
    to?: string;
    /**
     *
     * @type {Date}
     * @memberof NotificationItem
     */
    read_at?: Date | null;
}

/**
 * Check if a given object implements the NotificationItem interface.
 */
export function instanceOfNotificationItem(value: object): value is NotificationItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    return true;
}

export function NotificationItemFromJSON(json: any): NotificationItem {
    return NotificationItemFromJSONTyped(json, false);
}

export function NotificationItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationItem {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'title': json['title'],
        'subtitle': json['subtitle'] == null ? undefined : json['subtitle'],
        'created_at': (new Date(json['created_at'])),
        'priority': json['priority'] == null ? undefined : json['priority'],
        'to': json['to'] == null ? undefined : json['to'],
        'read_at': json['read_at'] == null ? undefined : (new Date(json['read_at'])),
    };
}

export function NotificationItemToJSON(json: any): NotificationItem {
    return NotificationItemToJSONTyped(json, false);
}

export function NotificationItemToJSONTyped(value?: NotificationItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'title': value['title'],
        'subtitle': value['subtitle'],
        'created_at': value['created_at'].toISOString(),
        'priority': value['priority'],
        'to': value['to'],
        'read_at': value['read_at'] == null ? value['read_at'] : value['read_at'].toISOString(),
    };
}
