/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationAccess
 */
export interface OrganizationAccess {
    /**
     * 
     * @type {string}
     * @memberof OrganizationAccess
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationAccess
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationAccess
     */
    org_type: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationAccess
     */
    persona: string;
}

/**
 * Check if a given object implements the OrganizationAccess interface.
 */
export function instanceOfOrganizationAccess(value: object): value is OrganizationAccess {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('org_type' in value) || value['org_type'] === undefined) return false;
    if (!('persona' in value) || value['persona'] === undefined) return false;
    return true;
}

export function OrganizationAccessFromJSON(json: any): OrganizationAccess {
    return OrganizationAccessFromJSONTyped(json, false);
}

export function OrganizationAccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationAccess {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'org_type': json['org_type'],
        'persona': json['persona'],
    };
}

export function OrganizationAccessToJSON(json: any): OrganizationAccess {
    return OrganizationAccessToJSONTyped(json, false);
}

export function OrganizationAccessToJSONTyped(value?: OrganizationAccess | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'org_type': value['org_type'],
        'persona': value['persona'],
    };
}

