/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordResetRequest
 */
export interface PasswordResetRequest {
    /**
     * 
     * @type {string}
     * @memberof PasswordResetRequest
     */
    token: string;
    /**
     * At least 12 characters and at most 256 UTF-8 bytes.
     * @type {string}
     * @memberof PasswordResetRequest
     */
    password: string;
}

/**
 * Check if a given object implements the PasswordResetRequest interface.
 */
export function instanceOfPasswordResetRequest(value: object): value is PasswordResetRequest {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function PasswordResetRequestFromJSON(json: any): PasswordResetRequest {
    return PasswordResetRequestFromJSONTyped(json, false);
}

export function PasswordResetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordResetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'password': json['password'],
    };
}

export function PasswordResetRequestToJSON(json: any): PasswordResetRequest {
    return PasswordResetRequestToJSONTyped(json, false);
}

export function PasswordResetRequestToJSONTyped(value?: PasswordResetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'password': value['password'],
    };
}

