/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepComplianceRequirementInput
 */
export interface RepComplianceRequirementInput {
    /**
     * 
     * @type {string}
     * @memberof RepComplianceRequirementInput
     */
    rep_user_id: string;
    /**
     * 
     * @type {string}
     * @memberof RepComplianceRequirementInput
     */
    vendor_org_id: string;
    /**
     * 
     * @type {string}
     * @memberof RepComplianceRequirementInput
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof RepComplianceRequirementInput
     */
    instructions?: string;
    /**
     * Optional calendar date; empty means no date. Due and validity dates include the full UTC calendar day.
     * @type {string}
     * @memberof RepComplianceRequirementInput
     */
    due_on?: string;
}

/**
 * Check if a given object implements the RepComplianceRequirementInput interface.
 */
export function instanceOfRepComplianceRequirementInput(value: object): value is RepComplianceRequirementInput {
    if (!('rep_user_id' in value) || value['rep_user_id'] === undefined) return false;
    if (!('vendor_org_id' in value) || value['vendor_org_id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function RepComplianceRequirementInputFromJSON(json: any): RepComplianceRequirementInput {
    return RepComplianceRequirementInputFromJSONTyped(json, false);
}

export function RepComplianceRequirementInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepComplianceRequirementInput {
    if (json == null) {
        return json;
    }
    return {
        
        'rep_user_id': json['rep_user_id'],
        'vendor_org_id': json['vendor_org_id'],
        'title': json['title'],
        'instructions': json['instructions'] == null ? undefined : json['instructions'],
        'due_on': json['due_on'] == null ? undefined : json['due_on'],
    };
}

export function RepComplianceRequirementInputToJSON(json: any): RepComplianceRequirementInput {
    return RepComplianceRequirementInputToJSONTyped(json, false);
}

export function RepComplianceRequirementInputToJSONTyped(value?: RepComplianceRequirementInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rep_user_id': value['rep_user_id'],
        'vendor_org_id': value['vendor_org_id'],
        'title': value['title'],
        'instructions': value['instructions'],
        'due_on': value['due_on'],
    };
}

