/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RepComplianceEvidence } from './RepComplianceEvidence';
import {
    RepComplianceEvidenceFromJSON,
    RepComplianceEvidenceFromJSONTyped,
    RepComplianceEvidenceToJSON,
    RepComplianceEvidenceToJSONTyped,
} from './RepComplianceEvidence';

/**
 * 
 * @export
 * @interface RepComplianceRequirement
 */
export interface RepComplianceRequirement {
    /**
     * 
     * @type {string}
     * @memberof RepComplianceRequirement
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RepComplianceRequirement
     */
    organization_id: string;
    /**
     * 
     * @type {string}
     * @memberof RepComplianceRequirement
     */
    rep_user_id: string;
    /**
     * 
     * @type {string}
     * @memberof RepComplianceRequirement
     */
    vendor_org_id: string;
    /**
     * 
     * @type {string}
     * @memberof RepComplianceRequirement
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof RepComplianceRequirement
     */
    instructions: string;
    /**
     * Optional calendar date; empty means no date. Due and validity dates include the full UTC calendar day.
     * @type {string}
     * @memberof RepComplianceRequirement
     */
    due_on: string;
    /**
     * 
     * @type {string}
     * @memberof RepComplianceRequirement
     */
    rep_name: string;
    /**
     * 
     * @type {string}
     * @memberof RepComplianceRequirement
     */
    vendor_name: string;
    /**
     * 
     * @type {boolean}
     * @memberof RepComplianceRequirement
     */
    enabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RepComplianceRequirement
     */
    eligible: boolean;
    /**
     * 
     * @type {RepComplianceRequirementStateEnum}
     * @memberof RepComplianceRequirement
     */
    state: RepComplianceRequirementStateEnum;
    /**
     * 
     * @type {Date}
     * @memberof RepComplianceRequirement
     */
    created_at: Date;
    /**
     * 
     * @type {RepComplianceEvidence}
     * @memberof RepComplianceRequirement
     */
    current_evidence: RepComplianceEvidence | null;
}


/**
 * @export
 */
export const RepComplianceRequirementStateEnum = {
    Assigned: 'assigned',
    Completed: 'completed',
    Overdue: 'overdue',
    Expired: 'expired',
    Stopped: 'stopped'
} as const;
export type RepComplianceRequirementStateEnum = typeof RepComplianceRequirementStateEnum[keyof typeof RepComplianceRequirementStateEnum];


/**
 * Check if a given object implements the RepComplianceRequirement interface.
 */
export function instanceOfRepComplianceRequirement(value: object): value is RepComplianceRequirement {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organization_id' in value) || value['organization_id'] === undefined) return false;
    if (!('rep_user_id' in value) || value['rep_user_id'] === undefined) return false;
    if (!('vendor_org_id' in value) || value['vendor_org_id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('instructions' in value) || value['instructions'] === undefined) return false;
    if (!('due_on' in value) || value['due_on'] === undefined) return false;
    if (!('rep_name' in value) || value['rep_name'] === undefined) return false;
    if (!('vendor_name' in value) || value['vendor_name'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('eligible' in value) || value['eligible'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('current_evidence' in value) || value['current_evidence'] === undefined) return false;
    return true;
}

export function RepComplianceRequirementFromJSON(json: any): RepComplianceRequirement {
    return RepComplianceRequirementFromJSONTyped(json, false);
}

export function RepComplianceRequirementFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepComplianceRequirement {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organization_id': json['organization_id'],
        'rep_user_id': json['rep_user_id'],
        'vendor_org_id': json['vendor_org_id'],
        'title': json['title'],
        'instructions': json['instructions'],
        'due_on': json['due_on'],
        'rep_name': json['rep_name'],
        'vendor_name': json['vendor_name'],
        'enabled': json['enabled'],
        'eligible': json['eligible'],
        'state': json['state'],
        'created_at': (new Date(json['created_at'])),
        'current_evidence': RepComplianceEvidenceFromJSON(json['current_evidence']),
    };
}

export function RepComplianceRequirementToJSON(json: any): RepComplianceRequirement {
    return RepComplianceRequirementToJSONTyped(json, false);
}

export function RepComplianceRequirementToJSONTyped(value?: RepComplianceRequirement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organization_id': value['organization_id'],
        'rep_user_id': value['rep_user_id'],
        'vendor_org_id': value['vendor_org_id'],
        'title': value['title'],
        'instructions': value['instructions'],
        'due_on': value['due_on'],
        'rep_name': value['rep_name'],
        'vendor_name': value['vendor_name'],
        'enabled': value['enabled'],
        'eligible': value['eligible'],
        'state': value['state'],
        'created_at': value['created_at'].toISOString(),
        'current_evidence': RepComplianceEvidenceToJSON(value['current_evidence']),
    };
}

