/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepComplianceEvidenceInput
 */
export interface RepComplianceEvidenceInput {
    /**
     * 
     * @type {string}
     * @memberof RepComplianceEvidenceInput
     */
    provider_name: string;
    /**
     * 
     * @type {string}
     * @memberof RepComplianceEvidenceInput
     */
    evidence_reference: string;
    /**
     * Optional HTTPS verification link; BridgeMed does not fetch this URL.
     * @type {string}
     * @memberof RepComplianceEvidenceInput
     */
    evidence_url?: string;
    /**
     * 
     * @type {string}
     * @memberof RepComplianceEvidenceInput
     */
    notes?: string;
    /**
     * Calendar date in YYYY-MM-DD form.
     * @type {string}
     * @memberof RepComplianceEvidenceInput
     */
    completed_on: string;
    /**
     * Optional calendar date; empty means no date. Due and validity dates include the full UTC calendar day.
     * @type {string}
     * @memberof RepComplianceEvidenceInput
     */
    expires_on?: string;
    /**
     * The administrator confirms verification of external completion evidence.
     * @type {boolean}
     * @memberof RepComplianceEvidenceInput
     */
    verified: boolean;
}

/**
 * Check if a given object implements the RepComplianceEvidenceInput interface.
 */
export function instanceOfRepComplianceEvidenceInput(value: object): value is RepComplianceEvidenceInput {
    if (!('provider_name' in value) || value['provider_name'] === undefined) return false;
    if (!('evidence_reference' in value) || value['evidence_reference'] === undefined) return false;
    if (!('completed_on' in value) || value['completed_on'] === undefined) return false;
    if (!('verified' in value) || value['verified'] === undefined) return false;
    return true;
}

export function RepComplianceEvidenceInputFromJSON(json: any): RepComplianceEvidenceInput {
    return RepComplianceEvidenceInputFromJSONTyped(json, false);
}

export function RepComplianceEvidenceInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepComplianceEvidenceInput {
    if (json == null) {
        return json;
    }
    return {
        
        'provider_name': json['provider_name'],
        'evidence_reference': json['evidence_reference'],
        'evidence_url': json['evidence_url'] == null ? undefined : json['evidence_url'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'completed_on': json['completed_on'],
        'expires_on': json['expires_on'] == null ? undefined : json['expires_on'],
        'verified': json['verified'],
    };
}

export function RepComplianceEvidenceInputToJSON(json: any): RepComplianceEvidenceInput {
    return RepComplianceEvidenceInputToJSONTyped(json, false);
}

export function RepComplianceEvidenceInputToJSONTyped(value?: RepComplianceEvidenceInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider_name': value['provider_name'],
        'evidence_reference': value['evidence_reference'],
        'evidence_url': value['evidence_url'],
        'notes': value['notes'],
        'completed_on': value['completed_on'],
        'expires_on': value['expires_on'],
        'verified': value['verified'],
    };
}

