/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepCompliancePerson
 */
export interface RepCompliancePerson {
    /**
     * 
     * @type {string}
     * @memberof RepCompliancePerson
     */
    rep_user_id: string;
    /**
     * 
     * @type {string}
     * @memberof RepCompliancePerson
     */
    vendor_org_id: string;
    /**
     * 
     * @type {string}
     * @memberof RepCompliancePerson
     */
    rep_name: string;
    /**
     * 
     * @type {string}
     * @memberof RepCompliancePerson
     */
    vendor_name: string;
}

/**
 * Check if a given object implements the RepCompliancePerson interface.
 */
export function instanceOfRepCompliancePerson(value: object): value is RepCompliancePerson {
    if (!('rep_user_id' in value) || value['rep_user_id'] === undefined) return false;
    if (!('vendor_org_id' in value) || value['vendor_org_id'] === undefined) return false;
    if (!('rep_name' in value) || value['rep_name'] === undefined) return false;
    if (!('vendor_name' in value) || value['vendor_name'] === undefined) return false;
    return true;
}

export function RepCompliancePersonFromJSON(json: any): RepCompliancePerson {
    return RepCompliancePersonFromJSONTyped(json, false);
}

export function RepCompliancePersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepCompliancePerson {
    if (json == null) {
        return json;
    }
    return {
        
        'rep_user_id': json['rep_user_id'],
        'vendor_org_id': json['vendor_org_id'],
        'rep_name': json['rep_name'],
        'vendor_name': json['vendor_name'],
    };
}

export function RepCompliancePersonToJSON(json: any): RepCompliancePerson {
    return RepCompliancePersonToJSONTyped(json, false);
}

export function RepCompliancePersonToJSONTyped(value?: RepCompliancePerson | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rep_user_id': value['rep_user_id'],
        'vendor_org_id': value['vendor_org_id'],
        'rep_name': value['rep_name'],
        'vendor_name': value['vendor_name'],
    };
}

