/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestPasswordRecovery202Response
 */
export interface RequestPasswordRecovery202Response {
    /**
     * 
     * @type {string}
     * @memberof RequestPasswordRecovery202Response
     */
    message: string;
}

/**
 * Check if a given object implements the RequestPasswordRecovery202Response interface.
 */
export function instanceOfRequestPasswordRecovery202Response(value: object): value is RequestPasswordRecovery202Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function RequestPasswordRecovery202ResponseFromJSON(json: any): RequestPasswordRecovery202Response {
    return RequestPasswordRecovery202ResponseFromJSONTyped(json, false);
}

export function RequestPasswordRecovery202ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestPasswordRecovery202Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function RequestPasswordRecovery202ResponseToJSON(json: any): RequestPasswordRecovery202Response {
    return RequestPasswordRecovery202ResponseToJSONTyped(json, false);
}

export function RequestPasswordRecovery202ResponseToJSONTyped(value?: RequestPasswordRecovery202Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

