/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CalendarFeedScope } from './CalendarFeedScope';
import {
    CalendarFeedScopeFromJSON,
    CalendarFeedScopeFromJSONTyped,
    CalendarFeedScopeToJSON,
    CalendarFeedScopeToJSONTyped,
} from './CalendarFeedScope';

/**
 * 
 * @export
 * @interface RotateCalendarFeedRequest
 */
export interface RotateCalendarFeedRequest {
    /**
     * 
     * @type {CalendarFeedScope}
     * @memberof RotateCalendarFeedRequest
     */
    scope: CalendarFeedScope;
}



/**
 * Check if a given object implements the RotateCalendarFeedRequest interface.
 */
export function instanceOfRotateCalendarFeedRequest(value: object): value is RotateCalendarFeedRequest {
    if (!('scope' in value) || value['scope'] === undefined) return false;
    return true;
}

export function RotateCalendarFeedRequestFromJSON(json: any): RotateCalendarFeedRequest {
    return RotateCalendarFeedRequestFromJSONTyped(json, false);
}

export function RotateCalendarFeedRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RotateCalendarFeedRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'scope': CalendarFeedScopeFromJSON(json['scope']),
    };
}

export function RotateCalendarFeedRequestToJSON(json: any): RotateCalendarFeedRequest {
    return RotateCalendarFeedRequestToJSONTyped(json, false);
}

export function RotateCalendarFeedRequestToJSONTyped(value?: RotateCalendarFeedRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope': CalendarFeedScopeToJSON(value['scope']),
    };
}

