/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SwitchOrganizationRequest
 */
export interface SwitchOrganizationRequest {
    /**
     * 
     * @type {string}
     * @memberof SwitchOrganizationRequest
     */
    organization_id: string;
}

/**
 * Check if a given object implements the SwitchOrganizationRequest interface.
 */
export function instanceOfSwitchOrganizationRequest(value: object): value is SwitchOrganizationRequest {
    if (!('organization_id' in value) || value['organization_id'] === undefined) return false;
    return true;
}

export function SwitchOrganizationRequestFromJSON(json: any): SwitchOrganizationRequest {
    return SwitchOrganizationRequestFromJSONTyped(json, false);
}

export function SwitchOrganizationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwitchOrganizationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'organization_id': json['organization_id'],
    };
}

export function SwitchOrganizationRequestToJSON(json: any): SwitchOrganizationRequest {
    return SwitchOrganizationRequestToJSONTyped(json, false);
}

export function SwitchOrganizationRequestToJSONTyped(value?: SwitchOrganizationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization_id': value['organization_id'],
    };
}

