/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrainingSessionAttendanceStatus } from './TrainingSessionAttendanceStatus';
import {
    TrainingSessionAttendanceStatusFromJSON,
    TrainingSessionAttendanceStatusFromJSONTyped,
    TrainingSessionAttendanceStatusToJSON,
    TrainingSessionAttendanceStatusToJSONTyped,
} from './TrainingSessionAttendanceStatus';

/**
 * 
 * @export
 * @interface TrainingSessionRegistration
 */
export interface TrainingSessionRegistration {
    /**
     * 
     * @type {string}
     * @memberof TrainingSessionRegistration
     */
    organization_id: string;
    /**
     * Native means verified media presence, not course completion or awarded credit. Legacy records are not retroactively verified.
     * @type {TrainingSessionRegistrationAttendanceSourceEnum}
     * @memberof TrainingSessionRegistration
     */
    attendance_source: TrainingSessionRegistrationAttendanceSourceEnum;
    /**
     * 
     * @type {string}
     * @memberof TrainingSessionRegistration
     */
    attendance_evidence?: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingSessionRegistration
     */
    recorded_by_user_id?: string;
    /**
     * Conservative total of verified hospital learner media intervals, maintained by the server.
     * @type {number}
     * @memberof TrainingSessionRegistration
     */
    verified_attendance_seconds: number;
    /**
     * 
     * @type {string}
     * @memberof TrainingSessionRegistration
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingSessionRegistration
     */
    session_id: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingSessionRegistration
     */
    user_id: string;
    /**
     * 
     * @type {TrainingSessionAttendanceStatus}
     * @memberof TrainingSessionRegistration
     */
    attendance_status: TrainingSessionAttendanceStatus;
    /**
     * 
     * @type {Date}
     * @memberof TrainingSessionRegistration
     */
    checked_in_at?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof TrainingSessionRegistration
     */
    registered_by_user_id?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TrainingSessionRegistration
     */
    date_added: Date;
    /**
     * 
     * @type {Date}
     * @memberof TrainingSessionRegistration
     */
    date_updated?: Date | null;
}


/**
 * @export
 */
export const TrainingSessionRegistrationAttendanceSourceEnum = {
    None: 'none',
    Legacy: 'legacy',
    Admin: 'admin',
    Native: 'native'
} as const;
export type TrainingSessionRegistrationAttendanceSourceEnum = typeof TrainingSessionRegistrationAttendanceSourceEnum[keyof typeof TrainingSessionRegistrationAttendanceSourceEnum];


/**
 * Check if a given object implements the TrainingSessionRegistration interface.
 */
export function instanceOfTrainingSessionRegistration(value: object): value is TrainingSessionRegistration {
    if (!('organization_id' in value) || value['organization_id'] === undefined) return false;
    if (!('attendance_source' in value) || value['attendance_source'] === undefined) return false;
    if (!('verified_attendance_seconds' in value) || value['verified_attendance_seconds'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('session_id' in value) || value['session_id'] === undefined) return false;
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    if (!('attendance_status' in value) || value['attendance_status'] === undefined) return false;
    if (!('date_added' in value) || value['date_added'] === undefined) return false;
    return true;
}

export function TrainingSessionRegistrationFromJSON(json: any): TrainingSessionRegistration {
    return TrainingSessionRegistrationFromJSONTyped(json, false);
}

export function TrainingSessionRegistrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrainingSessionRegistration {
    if (json == null) {
        return json;
    }
    return {
        
        'organization_id': json['organization_id'],
        'attendance_source': json['attendance_source'],
        'attendance_evidence': json['attendance_evidence'] == null ? undefined : json['attendance_evidence'],
        'recorded_by_user_id': json['recorded_by_user_id'] == null ? undefined : json['recorded_by_user_id'],
        'verified_attendance_seconds': json['verified_attendance_seconds'],
        'id': json['id'],
        'session_id': json['session_id'],
        'user_id': json['user_id'],
        'attendance_status': TrainingSessionAttendanceStatusFromJSON(json['attendance_status']),
        'checked_in_at': json['checked_in_at'] == null ? undefined : (new Date(json['checked_in_at'])),
        'registered_by_user_id': json['registered_by_user_id'] == null ? undefined : json['registered_by_user_id'],
        'date_added': (new Date(json['date_added'])),
        'date_updated': json['date_updated'] == null ? undefined : (new Date(json['date_updated'])),
    };
}

export function TrainingSessionRegistrationToJSON(json: any): TrainingSessionRegistration {
    return TrainingSessionRegistrationToJSONTyped(json, false);
}

export function TrainingSessionRegistrationToJSONTyped(value?: TrainingSessionRegistration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization_id': value['organization_id'],
        'attendance_source': value['attendance_source'],
        'attendance_evidence': value['attendance_evidence'],
        'recorded_by_user_id': value['recorded_by_user_id'],
        'verified_attendance_seconds': value['verified_attendance_seconds'],
        'id': value['id'],
        'session_id': value['session_id'],
        'user_id': value['user_id'],
        'attendance_status': TrainingSessionAttendanceStatusToJSON(value['attendance_status']),
        'checked_in_at': value['checked_in_at'] == null ? value['checked_in_at'] : value['checked_in_at'].toISOString(),
        'registered_by_user_id': value['registered_by_user_id'],
        'date_added': value['date_added'].toISOString(),
        'date_updated': value['date_updated'] == null ? value['date_updated'] : value['date_updated'].toISOString(),
    };
}

