/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrainingSessionMaterialKind } from './TrainingSessionMaterialKind';
import {
    TrainingSessionMaterialKindFromJSON,
    TrainingSessionMaterialKindFromJSONTyped,
    TrainingSessionMaterialKindToJSON,
    TrainingSessionMaterialKindToJSONTyped,
} from './TrainingSessionMaterialKind';

/**
 * 
 * @export
 * @interface TrainingSessionMaterial
 */
export interface TrainingSessionMaterial {
    /**
     * 
     * @type {string}
     * @memberof TrainingSessionMaterial
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingSessionMaterial
     */
    session_id: string;
    /**
     * 
     * @type {TrainingSessionMaterialKind}
     * @memberof TrainingSessionMaterial
     */
    material_kind: TrainingSessionMaterialKind;
    /**
     * 
     * @type {string}
     * @memberof TrainingSessionMaterial
     */
    catalog_content_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrainingSessionMaterial
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingSessionMaterial
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingSessionMaterial
     */
    external_url?: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingSessionMaterial
     */
    upload_object_key?: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingSessionMaterial
     */
    upload_filename?: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingSessionMaterial
     */
    upload_content_type?: string;
    /**
     * 
     * @type {number}
     * @memberof TrainingSessionMaterial
     */
    upload_size_bytes?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TrainingSessionMaterial
     */
    upload_status?: string;
    /**
     * 
     * @type {number}
     * @memberof TrainingSessionMaterial
     */
    sort_order: number;
    /**
     * 
     * @type {string}
     * @memberof TrainingSessionMaterial
     */
    upload_url?: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingSessionMaterial
     */
    download_url?: string;
    /**
     * 
     * @type {Date}
     * @memberof TrainingSessionMaterial
     */
    date_added: Date;
    /**
     * 
     * @type {Date}
     * @memberof TrainingSessionMaterial
     */
    date_updated?: Date | null;
}



/**
 * Check if a given object implements the TrainingSessionMaterial interface.
 */
export function instanceOfTrainingSessionMaterial(value: object): value is TrainingSessionMaterial {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('session_id' in value) || value['session_id'] === undefined) return false;
    if (!('material_kind' in value) || value['material_kind'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('sort_order' in value) || value['sort_order'] === undefined) return false;
    if (!('date_added' in value) || value['date_added'] === undefined) return false;
    return true;
}

export function TrainingSessionMaterialFromJSON(json: any): TrainingSessionMaterial {
    return TrainingSessionMaterialFromJSONTyped(json, false);
}

export function TrainingSessionMaterialFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrainingSessionMaterial {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'session_id': json['session_id'],
        'material_kind': TrainingSessionMaterialKindFromJSON(json['material_kind']),
        'catalog_content_id': json['catalog_content_id'] == null ? undefined : json['catalog_content_id'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'external_url': json['external_url'] == null ? undefined : json['external_url'],
        'upload_object_key': json['upload_object_key'] == null ? undefined : json['upload_object_key'],
        'upload_filename': json['upload_filename'] == null ? undefined : json['upload_filename'],
        'upload_content_type': json['upload_content_type'] == null ? undefined : json['upload_content_type'],
        'upload_size_bytes': json['upload_size_bytes'] == null ? undefined : json['upload_size_bytes'],
        'upload_status': json['upload_status'] == null ? undefined : json['upload_status'],
        'sort_order': json['sort_order'],
        'upload_url': json['upload_url'] == null ? undefined : json['upload_url'],
        'download_url': json['download_url'] == null ? undefined : json['download_url'],
        'date_added': (new Date(json['date_added'])),
        'date_updated': json['date_updated'] == null ? undefined : (new Date(json['date_updated'])),
    };
}

export function TrainingSessionMaterialToJSON(json: any): TrainingSessionMaterial {
    return TrainingSessionMaterialToJSONTyped(json, false);
}

export function TrainingSessionMaterialToJSONTyped(value?: TrainingSessionMaterial | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'session_id': value['session_id'],
        'material_kind': TrainingSessionMaterialKindToJSON(value['material_kind']),
        'catalog_content_id': value['catalog_content_id'],
        'title': value['title'],
        'description': value['description'],
        'external_url': value['external_url'],
        'upload_object_key': value['upload_object_key'],
        'upload_filename': value['upload_filename'],
        'upload_content_type': value['upload_content_type'],
        'upload_size_bytes': value['upload_size_bytes'],
        'upload_status': value['upload_status'],
        'sort_order': value['sort_order'],
        'upload_url': value['upload_url'],
        'download_url': value['download_url'],
        'date_added': value['date_added'].toISOString(),
        'date_updated': value['date_updated'] == null ? value['date_updated'] : value['date_updated'].toISOString(),
    };
}

