/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrainingSessionDeliveryMode } from './TrainingSessionDeliveryMode';
import {
    TrainingSessionDeliveryModeFromJSON,
    TrainingSessionDeliveryModeFromJSONTyped,
    TrainingSessionDeliveryModeToJSON,
    TrainingSessionDeliveryModeToJSONTyped,
} from './TrainingSessionDeliveryMode';

/**
 * 
 * @export
 * @interface UpdateTrainingSessionRequest
 */
export interface UpdateTrainingSessionRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateTrainingSessionRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTrainingSessionRequest
     */
    description?: string;
    /**
     * 
     * @type {TrainingSessionDeliveryMode}
     * @memberof UpdateTrainingSessionRequest
     */
    delivery_mode: TrainingSessionDeliveryMode;
    /**
     * 
     * @type {Date}
     * @memberof UpdateTrainingSessionRequest
     */
    starts_at: Date;
    /**
     * 
     * @type {Date}
     * @memberof UpdateTrainingSessionRequest
     */
    ends_at: Date;
    /**
     * 
     * @type {string}
     * @memberof UpdateTrainingSessionRequest
     */
    location_text?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTrainingSessionRequest
     */
    external_join_url?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateTrainingSessionRequest
     */
    capacity?: number;
}



/**
 * Check if a given object implements the UpdateTrainingSessionRequest interface.
 */
export function instanceOfUpdateTrainingSessionRequest(value: object): value is UpdateTrainingSessionRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('delivery_mode' in value) || value['delivery_mode'] === undefined) return false;
    if (!('starts_at' in value) || value['starts_at'] === undefined) return false;
    if (!('ends_at' in value) || value['ends_at'] === undefined) return false;
    return true;
}

export function UpdateTrainingSessionRequestFromJSON(json: any): UpdateTrainingSessionRequest {
    return UpdateTrainingSessionRequestFromJSONTyped(json, false);
}

export function UpdateTrainingSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTrainingSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'delivery_mode': TrainingSessionDeliveryModeFromJSON(json['delivery_mode']),
        'starts_at': (new Date(json['starts_at'])),
        'ends_at': (new Date(json['ends_at'])),
        'location_text': json['location_text'] == null ? undefined : json['location_text'],
        'external_join_url': json['external_join_url'] == null ? undefined : json['external_join_url'],
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
    };
}

export function UpdateTrainingSessionRequestToJSON(json: any): UpdateTrainingSessionRequest {
    return UpdateTrainingSessionRequestToJSONTyped(json, false);
}

export function UpdateTrainingSessionRequestToJSONTyped(value?: UpdateTrainingSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'delivery_mode': TrainingSessionDeliveryModeToJSON(value['delivery_mode']),
        'starts_at': value['starts_at'].toISOString(),
        'ends_at': value['ends_at'].toISOString(),
        'location_text': value['location_text'],
        'external_join_url': value['external_join_url'],
        'capacity': value['capacity'],
    };
}

