/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrainingSessionAttendanceStatus } from './TrainingSessionAttendanceStatus';
import {
    TrainingSessionAttendanceStatusFromJSON,
    TrainingSessionAttendanceStatusFromJSONTyped,
    TrainingSessionAttendanceStatusToJSON,
    TrainingSessionAttendanceStatusToJSONTyped,
} from './TrainingSessionAttendanceStatus';

/**
 * 
 * @export
 * @interface UpdateTrainingSessionRegistrationRequest
 */
export interface UpdateTrainingSessionRegistrationRequest {
    /**
     * Required when a hospital administrator records attended or no_show. Describe the provider roster or other evidence, never infer attendance from a meeting-link click.
     * @type {string}
     * @memberof UpdateTrainingSessionRegistrationRequest
     */
    attendance_evidence?: string;
    /**
     * 
     * @type {TrainingSessionAttendanceStatus}
     * @memberof UpdateTrainingSessionRegistrationRequest
     */
    attendance_status: TrainingSessionAttendanceStatus;
}



/**
 * Check if a given object implements the UpdateTrainingSessionRegistrationRequest interface.
 */
export function instanceOfUpdateTrainingSessionRegistrationRequest(value: object): value is UpdateTrainingSessionRegistrationRequest {
    if (!('attendance_status' in value) || value['attendance_status'] === undefined) return false;
    return true;
}

export function UpdateTrainingSessionRegistrationRequestFromJSON(json: any): UpdateTrainingSessionRegistrationRequest {
    return UpdateTrainingSessionRegistrationRequestFromJSONTyped(json, false);
}

export function UpdateTrainingSessionRegistrationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTrainingSessionRegistrationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'attendance_evidence': json['attendance_evidence'] == null ? undefined : json['attendance_evidence'],
        'attendance_status': TrainingSessionAttendanceStatusFromJSON(json['attendance_status']),
    };
}

export function UpdateTrainingSessionRegistrationRequestToJSON(json: any): UpdateTrainingSessionRegistrationRequest {
    return UpdateTrainingSessionRegistrationRequestToJSONTyped(json, false);
}

export function UpdateTrainingSessionRegistrationRequestToJSONTyped(value?: UpdateTrainingSessionRegistrationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attendance_evidence': value['attendance_evidence'],
        'attendance_status': TrainingSessionAttendanceStatusToJSON(value['attendance_status']),
    };
}

