/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProductMetadataRequest
 */
export interface UpdateProductMetadataRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateProductMetadataRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductMetadataRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductMetadataRequest
     */
    metadata_revision: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductMetadataRequest
     */
    device_identifier?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductMetadataRequest
     */
    model_number?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateProductMetadataRequest
     */
    specialties?: Array<string>;
    /**
     * Catalog categories only; never patient procedures or case information.
     * @type {Array<string>}
     * @memberof UpdateProductMetadataRequest
     */
    procedure_types?: Array<string>;
}

/**
 * Check if a given object implements the UpdateProductMetadataRequest interface.
 */
export function instanceOfUpdateProductMetadataRequest(value: object): value is UpdateProductMetadataRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('metadata_revision' in value) || value['metadata_revision'] === undefined) return false;
    return true;
}

export function UpdateProductMetadataRequestFromJSON(json: any): UpdateProductMetadataRequest {
    return UpdateProductMetadataRequestFromJSONTyped(json, false);
}

export function UpdateProductMetadataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProductMetadataRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'metadata_revision': json['metadata_revision'],
        'device_identifier': json['device_identifier'] == null ? undefined : json['device_identifier'],
        'model_number': json['model_number'] == null ? undefined : json['model_number'],
        'specialties': json['specialties'] == null ? undefined : json['specialties'],
        'procedure_types': json['procedure_types'] == null ? undefined : json['procedure_types'],
    };
}

export function UpdateProductMetadataRequestToJSON(json: any): UpdateProductMetadataRequest {
    return UpdateProductMetadataRequestToJSONTyped(json, false);
}

export function UpdateProductMetadataRequestToJSONTyped(value?: UpdateProductMetadataRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'metadata_revision': value['metadata_revision'],
        'device_identifier': value['device_identifier'],
        'model_number': value['model_number'],
        'specialties': value['specialties'],
        'procedure_types': value['procedure_types'],
    };
}

