/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrainingSessionDeliveryMode } from './TrainingSessionDeliveryMode';
import {
    TrainingSessionDeliveryModeFromJSON,
    TrainingSessionDeliveryModeFromJSONTyped,
    TrainingSessionDeliveryModeToJSON,
    TrainingSessionDeliveryModeToJSONTyped,
} from './TrainingSessionDeliveryMode';
import type { TrainingRequestStatus } from './TrainingRequestStatus';
import {
    TrainingRequestStatusFromJSON,
    TrainingRequestStatusFromJSONTyped,
    TrainingRequestStatusToJSON,
    TrainingRequestStatusToJSONTyped,
} from './TrainingRequestStatus';

/**
 * 
 * @export
 * @interface UpdateTrainingRequestStatusRequest
 */
export interface UpdateTrainingRequestStatusRequest {
    /**
     * 
     * @type {TrainingRequestStatus}
     * @memberof UpdateTrainingRequestStatusRequest
     */
    status: TrainingRequestStatus;
    /**
     * 
     * @type {string}
     * @memberof UpdateTrainingRequestStatusRequest
     */
    assigned_user_id?: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdateTrainingRequestStatusRequest
     */
    scheduled_start_at?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UpdateTrainingRequestStatusRequest
     */
    scheduled_end_at?: Date;
    /**
     * 
     * @type {TrainingSessionDeliveryMode}
     * @memberof UpdateTrainingRequestStatusRequest
     */
    delivery_mode?: TrainingSessionDeliveryMode;
    /**
     * 
     * @type {string}
     * @memberof UpdateTrainingRequestStatusRequest
     */
    location_text?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTrainingRequestStatusRequest
     */
    external_join_url?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateTrainingRequestStatusRequest
     */
    capacity?: number;
}



/**
 * Check if a given object implements the UpdateTrainingRequestStatusRequest interface.
 */
export function instanceOfUpdateTrainingRequestStatusRequest(value: object): value is UpdateTrainingRequestStatusRequest {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function UpdateTrainingRequestStatusRequestFromJSON(json: any): UpdateTrainingRequestStatusRequest {
    return UpdateTrainingRequestStatusRequestFromJSONTyped(json, false);
}

export function UpdateTrainingRequestStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTrainingRequestStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': TrainingRequestStatusFromJSON(json['status']),
        'assigned_user_id': json['assigned_user_id'] == null ? undefined : json['assigned_user_id'],
        'scheduled_start_at': json['scheduled_start_at'] == null ? undefined : (new Date(json['scheduled_start_at'])),
        'scheduled_end_at': json['scheduled_end_at'] == null ? undefined : (new Date(json['scheduled_end_at'])),
        'delivery_mode': json['delivery_mode'] == null ? undefined : TrainingSessionDeliveryModeFromJSON(json['delivery_mode']),
        'location_text': json['location_text'] == null ? undefined : json['location_text'],
        'external_join_url': json['external_join_url'] == null ? undefined : json['external_join_url'],
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
    };
}

export function UpdateTrainingRequestStatusRequestToJSON(json: any): UpdateTrainingRequestStatusRequest {
    return UpdateTrainingRequestStatusRequestToJSONTyped(json, false);
}

export function UpdateTrainingRequestStatusRequestToJSONTyped(value?: UpdateTrainingRequestStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': TrainingRequestStatusToJSON(value['status']),
        'assigned_user_id': value['assigned_user_id'],
        'scheduled_start_at': value['scheduled_start_at'] == null ? value['scheduled_start_at'] : value['scheduled_start_at'].toISOString(),
        'scheduled_end_at': value['scheduled_end_at'] == null ? value['scheduled_end_at'] : value['scheduled_end_at'].toISOString(),
        'delivery_mode': TrainingSessionDeliveryModeToJSON(value['delivery_mode']),
        'location_text': value['location_text'],
        'external_join_url': value['external_join_url'],
        'capacity': value['capacity'],
    };
}

