/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrainingSessionMaterialKind } from './TrainingSessionMaterialKind';
import {
    TrainingSessionMaterialKindFromJSON,
    TrainingSessionMaterialKindFromJSONTyped,
    TrainingSessionMaterialKindToJSON,
    TrainingSessionMaterialKindToJSONTyped,
} from './TrainingSessionMaterialKind';

/**
 * 
 * @export
 * @interface UpdateTrainingSessionMaterialRequest
 */
export interface UpdateTrainingSessionMaterialRequest {
    /**
     * 
     * @type {TrainingSessionMaterialKind}
     * @memberof UpdateTrainingSessionMaterialRequest
     */
    material_kind: TrainingSessionMaterialKind;
    /**
     * 
     * @type {string}
     * @memberof UpdateTrainingSessionMaterialRequest
     */
    catalog_content_id?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTrainingSessionMaterialRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTrainingSessionMaterialRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTrainingSessionMaterialRequest
     */
    external_url?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTrainingSessionMaterialRequest
     */
    upload_filename?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTrainingSessionMaterialRequest
     */
    upload_content_type?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateTrainingSessionMaterialRequest
     */
    upload_size_bytes?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateTrainingSessionMaterialRequest
     */
    sort_order?: number;
}



/**
 * Check if a given object implements the UpdateTrainingSessionMaterialRequest interface.
 */
export function instanceOfUpdateTrainingSessionMaterialRequest(value: object): value is UpdateTrainingSessionMaterialRequest {
    if (!('material_kind' in value) || value['material_kind'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function UpdateTrainingSessionMaterialRequestFromJSON(json: any): UpdateTrainingSessionMaterialRequest {
    return UpdateTrainingSessionMaterialRequestFromJSONTyped(json, false);
}

export function UpdateTrainingSessionMaterialRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTrainingSessionMaterialRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'material_kind': TrainingSessionMaterialKindFromJSON(json['material_kind']),
        'catalog_content_id': json['catalog_content_id'] == null ? undefined : json['catalog_content_id'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'external_url': json['external_url'] == null ? undefined : json['external_url'],
        'upload_filename': json['upload_filename'] == null ? undefined : json['upload_filename'],
        'upload_content_type': json['upload_content_type'] == null ? undefined : json['upload_content_type'],
        'upload_size_bytes': json['upload_size_bytes'] == null ? undefined : json['upload_size_bytes'],
        'sort_order': json['sort_order'] == null ? undefined : json['sort_order'],
    };
}

export function UpdateTrainingSessionMaterialRequestToJSON(json: any): UpdateTrainingSessionMaterialRequest {
    return UpdateTrainingSessionMaterialRequestToJSONTyped(json, false);
}

export function UpdateTrainingSessionMaterialRequestToJSONTyped(value?: UpdateTrainingSessionMaterialRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'material_kind': TrainingSessionMaterialKindToJSON(value['material_kind']),
        'catalog_content_id': value['catalog_content_id'],
        'title': value['title'],
        'description': value['description'],
        'external_url': value['external_url'],
        'upload_filename': value['upload_filename'],
        'upload_content_type': value['upload_content_type'],
        'upload_size_bytes': value['upload_size_bytes'],
        'sort_order': value['sort_order'],
    };
}

