/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VendorSignupResult
 */
export interface VendorSignupResult {
    /**
     * 
     * @type {string}
     * @memberof VendorSignupResult
     */
    organization_id: string;
    /**
     * 
     * @type {string}
     * @memberof VendorSignupResult
     */
    organization_name: string;
    /**
     * 
     * @type {string}
     * @memberof VendorSignupResult
     */
    email: string;
}

/**
 * Check if a given object implements the VendorSignupResult interface.
 */
export function instanceOfVendorSignupResult(value: object): value is VendorSignupResult {
    if (!('organization_id' in value) || value['organization_id'] === undefined) return false;
    if (!('organization_name' in value) || value['organization_name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function VendorSignupResultFromJSON(json: any): VendorSignupResult {
    return VendorSignupResultFromJSONTyped(json, false);
}

export function VendorSignupResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): VendorSignupResult {
    if (json == null) {
        return json;
    }
    return {
        
        'organization_id': json['organization_id'],
        'organization_name': json['organization_name'],
        'email': json['email'],
    };
}

export function VendorSignupResultToJSON(json: any): VendorSignupResult {
    return VendorSignupResultToJSONTyped(json, false);
}

export function VendorSignupResultToJSONTyped(value?: VendorSignupResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization_id': value['organization_id'],
        'organization_name': value['organization_name'],
        'email': value['email'],
    };
}

