/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VendorSignupPreview
 */
export interface VendorSignupPreview {
    /**
     * 
     * @type {string}
     * @memberof VendorSignupPreview
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof VendorSignupPreview
     */
    first_name: string;
    /**
     * 
     * @type {string}
     * @memberof VendorSignupPreview
     */
    last_name: string;
    /**
     * 
     * @type {string}
     * @memberof VendorSignupPreview
     */
    company_name: string;
    /**
     * 
     * @type {boolean}
     * @memberof VendorSignupPreview
     */
    existing_account: boolean;
}

/**
 * Check if a given object implements the VendorSignupPreview interface.
 */
export function instanceOfVendorSignupPreview(value: object): value is VendorSignupPreview {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('first_name' in value) || value['first_name'] === undefined) return false;
    if (!('last_name' in value) || value['last_name'] === undefined) return false;
    if (!('company_name' in value) || value['company_name'] === undefined) return false;
    if (!('existing_account' in value) || value['existing_account'] === undefined) return false;
    return true;
}

export function VendorSignupPreviewFromJSON(json: any): VendorSignupPreview {
    return VendorSignupPreviewFromJSONTyped(json, false);
}

export function VendorSignupPreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): VendorSignupPreview {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'first_name': json['first_name'],
        'last_name': json['last_name'],
        'company_name': json['company_name'],
        'existing_account': json['existing_account'],
    };
}

export function VendorSignupPreviewToJSON(json: any): VendorSignupPreview {
    return VendorSignupPreviewToJSONTyped(json, false);
}

export function VendorSignupPreviewToJSONTyped(value?: VendorSignupPreview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'first_name': value['first_name'],
        'last_name': value['last_name'],
        'company_name': value['company_name'],
        'existing_account': value['existing_account'],
    };
}

