/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VendorBillingSummary
 */
export interface VendorBillingSummary {
    /**
     * 
     * @type {string}
     * @memberof VendorBillingSummary
     */
    organization_id: string;
    /**
     * 
     * @type {string}
     * @memberof VendorBillingSummary
     */
    organization_name: string;
    /**
     * 
     * @type {VendorBillingSummaryAccessModeEnum}
     * @memberof VendorBillingSummary
     */
    access_mode: VendorBillingSummaryAccessModeEnum;
    /**
     * Current server-enforced access to paid vendor operations. Billing recovery, safety withdrawals, and hospital access to published documents remain available when false.
     * @type {boolean}
     * @memberof VendorBillingSummary
     */
    paid_operations_allowed: boolean;
    /**
     * Saved subscription status, or none before a subscription is attached.
     * @type {string}
     * @memberof VendorBillingSummary
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof VendorBillingSummary
     */
    plan_key: string;
    /**
     * month, year, or empty before a supported subscription is attached.
     * @type {string}
     * @memberof VendorBillingSummary
     */
    interval: string;
    /**
     * 
     * @type {Date}
     * @memberof VendorBillingSummary
     */
    paid_through?: Date;
    /**
     * 
     * @type {Date}
     * @memberof VendorBillingSummary
     */
    grace_until?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof VendorBillingSummary
     */
    cancel_at_period_end: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof VendorBillingSummary
     */
    needs_review: boolean;
    /**
     * No nonterminal subscription exists. Uncertain prior operations still require recovery before creation.
     * @type {boolean}
     * @memberof VendorBillingSummary
     */
    can_checkout: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof VendorBillingSummary
     */
    can_open_portal: boolean;
    /**
     * 
     * @type {Date}
     * @memberof VendorBillingSummary
     */
    last_reconciled_at?: Date;
}


/**
 * @export
 */
export const VendorBillingSummaryAccessModeEnum = {
    Required: 'required',
    MigrationReview: 'migration_review'
} as const;
export type VendorBillingSummaryAccessModeEnum = typeof VendorBillingSummaryAccessModeEnum[keyof typeof VendorBillingSummaryAccessModeEnum];


/**
 * Check if a given object implements the VendorBillingSummary interface.
 */
export function instanceOfVendorBillingSummary(value: object): value is VendorBillingSummary {
    if (!('organization_id' in value) || value['organization_id'] === undefined) return false;
    if (!('organization_name' in value) || value['organization_name'] === undefined) return false;
    if (!('access_mode' in value) || value['access_mode'] === undefined) return false;
    if (!('paid_operations_allowed' in value) || value['paid_operations_allowed'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('plan_key' in value) || value['plan_key'] === undefined) return false;
    if (!('interval' in value) || value['interval'] === undefined) return false;
    if (!('cancel_at_period_end' in value) || value['cancel_at_period_end'] === undefined) return false;
    if (!('needs_review' in value) || value['needs_review'] === undefined) return false;
    if (!('can_checkout' in value) || value['can_checkout'] === undefined) return false;
    if (!('can_open_portal' in value) || value['can_open_portal'] === undefined) return false;
    return true;
}

export function VendorBillingSummaryFromJSON(json: any): VendorBillingSummary {
    return VendorBillingSummaryFromJSONTyped(json, false);
}

export function VendorBillingSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): VendorBillingSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'organization_id': json['organization_id'],
        'organization_name': json['organization_name'],
        'access_mode': json['access_mode'],
        'paid_operations_allowed': json['paid_operations_allowed'],
        'status': json['status'],
        'plan_key': json['plan_key'],
        'interval': json['interval'],
        'paid_through': json['paid_through'] == null ? undefined : (new Date(json['paid_through'])),
        'grace_until': json['grace_until'] == null ? undefined : (new Date(json['grace_until'])),
        'cancel_at_period_end': json['cancel_at_period_end'],
        'needs_review': json['needs_review'],
        'can_checkout': json['can_checkout'],
        'can_open_portal': json['can_open_portal'],
        'last_reconciled_at': json['last_reconciled_at'] == null ? undefined : (new Date(json['last_reconciled_at'])),
    };
}

export function VendorBillingSummaryToJSON(json: any): VendorBillingSummary {
    return VendorBillingSummaryToJSONTyped(json, false);
}

export function VendorBillingSummaryToJSONTyped(value?: VendorBillingSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization_id': value['organization_id'],
        'organization_name': value['organization_name'],
        'access_mode': value['access_mode'],
        'paid_operations_allowed': value['paid_operations_allowed'],
        'status': value['status'],
        'plan_key': value['plan_key'],
        'interval': value['interval'],
        'paid_through': value['paid_through'] == null ? value['paid_through'] : value['paid_through'].toISOString(),
        'grace_until': value['grace_until'] == null ? value['grace_until'] : value['grace_until'].toISOString(),
        'cancel_at_period_end': value['cancel_at_period_end'],
        'needs_review': value['needs_review'],
        'can_checkout': value['can_checkout'],
        'can_open_portal': value['can_open_portal'],
        'last_reconciled_at': value['last_reconciled_at'] == null ? value['last_reconciled_at'] : value['last_reconciled_at'].toISOString(),
    };
}

