/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VendorSignupInput
 */
export interface VendorSignupInput {
    /**
     * 
     * @type {string}
     * @memberof VendorSignupInput
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof VendorSignupInput
     */
    first_name: string;
    /**
     * 
     * @type {string}
     * @memberof VendorSignupInput
     */
    last_name: string;
    /**
     * 
     * @type {string}
     * @memberof VendorSignupInput
     */
    company_name: string;
}

/**
 * Check if a given object implements the VendorSignupInput interface.
 */
export function instanceOfVendorSignupInput(value: object): value is VendorSignupInput {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('first_name' in value) || value['first_name'] === undefined) return false;
    if (!('last_name' in value) || value['last_name'] === undefined) return false;
    if (!('company_name' in value) || value['company_name'] === undefined) return false;
    return true;
}

export function VendorSignupInputFromJSON(json: any): VendorSignupInput {
    return VendorSignupInputFromJSONTyped(json, false);
}

export function VendorSignupInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): VendorSignupInput {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'first_name': json['first_name'],
        'last_name': json['last_name'],
        'company_name': json['company_name'],
    };
}

export function VendorSignupInputToJSON(json: any): VendorSignupInput {
    return VendorSignupInputToJSONTyped(json, false);
}

export function VendorSignupInputToJSONTyped(value?: VendorSignupInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'first_name': value['first_name'],
        'last_name': value['last_name'],
        'company_name': value['company_name'],
    };
}

