/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VendorSignupToken
 */
export interface VendorSignupToken {
    /**
     * 
     * @type {string}
     * @memberof VendorSignupToken
     */
    token: string;
}

/**
 * Check if a given object implements the VendorSignupToken interface.
 */
export function instanceOfVendorSignupToken(value: object): value is VendorSignupToken {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function VendorSignupTokenFromJSON(json: any): VendorSignupToken {
    return VendorSignupTokenFromJSONTyped(json, false);
}

export function VendorSignupTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): VendorSignupToken {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function VendorSignupTokenToJSON(json: any): VendorSignupToken {
    return VendorSignupTokenToJSONTyped(json, false);
}

export function VendorSignupTokenToJSONTyped(value?: VendorSignupToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

