/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VideoAssetStatus = {
    Draft: 'draft',
    Processing: 'processing',
    Ready: 'ready',
    Failed: 'failed',
    Archived: 'archived'
} as const;
export type VideoAssetStatus = typeof VideoAssetStatus[keyof typeof VideoAssetStatus];


export function instanceOfVideoAssetStatus(value: any): boolean {
    for (const key in VideoAssetStatus) {
        if (Object.prototype.hasOwnProperty.call(VideoAssetStatus, key)) {
            if (VideoAssetStatus[key as keyof typeof VideoAssetStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VideoAssetStatusFromJSON(json: any): VideoAssetStatus {
    return VideoAssetStatusFromJSONTyped(json, false);
}

export function VideoAssetStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoAssetStatus {
    return json as VideoAssetStatus;
}

export function VideoAssetStatusToJSON(value?: VideoAssetStatus | null): any {
    return value as any;
}

export function VideoAssetStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): VideoAssetStatus {
    return value as VideoAssetStatus;
}

