/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VideoUploadStatus = {
    Pending: 'pending',
    Uploaded: 'uploaded'
} as const;
export type VideoUploadStatus = typeof VideoUploadStatus[keyof typeof VideoUploadStatus];


export function instanceOfVideoUploadStatus(value: any): boolean {
    for (const key in VideoUploadStatus) {
        if (Object.prototype.hasOwnProperty.call(VideoUploadStatus, key)) {
            if (VideoUploadStatus[key as keyof typeof VideoUploadStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VideoUploadStatusFromJSON(json: any): VideoUploadStatus {
    return VideoUploadStatusFromJSONTyped(json, false);
}

export function VideoUploadStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoUploadStatus {
    return json as VideoUploadStatus;
}

export function VideoUploadStatusToJSON(value?: VideoUploadStatus | null): any {
    return value as any;
}

export function VideoUploadStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): VideoUploadStatus {
    return value as VideoUploadStatus;
}

