/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkspaceSearchItem } from './WorkspaceSearchItem';
import {
    WorkspaceSearchItemFromJSON,
    WorkspaceSearchItemFromJSONTyped,
    WorkspaceSearchItemToJSON,
    WorkspaceSearchItemToJSONTyped,
} from './WorkspaceSearchItem';

/**
 * 
 * @export
 * @interface WorkspaceSearchGroup
 */
export interface WorkspaceSearchGroup {
    /**
     * 
     * @type {WorkspaceSearchGroupTypeEnum}
     * @memberof WorkspaceSearchGroup
     */
    type: WorkspaceSearchGroupTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceSearchGroup
     */
    label: string;
    /**
     * 
     * @type {Array<WorkspaceSearchItem>}
     * @memberof WorkspaceSearchGroup
     */
    items: Array<WorkspaceSearchItem>;
}


/**
 * @export
 */
export const WorkspaceSearchGroupTypeEnum = {
    Products: 'products',
    Content: 'content',
    Reps: 'reps',
    Organizations: 'organizations',
    Webinars: 'webinars',
    Training: 'training'
} as const;
export type WorkspaceSearchGroupTypeEnum = typeof WorkspaceSearchGroupTypeEnum[keyof typeof WorkspaceSearchGroupTypeEnum];


/**
 * Check if a given object implements the WorkspaceSearchGroup interface.
 */
export function instanceOfWorkspaceSearchGroup(value: object): value is WorkspaceSearchGroup {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function WorkspaceSearchGroupFromJSON(json: any): WorkspaceSearchGroup {
    return WorkspaceSearchGroupFromJSONTyped(json, false);
}

export function WorkspaceSearchGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceSearchGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'label': json['label'],
        'items': ((json['items'] as Array<any>).map(WorkspaceSearchItemFromJSON)),
    };
}

export function WorkspaceSearchGroupToJSON(json: any): WorkspaceSearchGroup {
    return WorkspaceSearchGroupToJSONTyped(json, false);
}

export function WorkspaceSearchGroupToJSONTyped(value?: WorkspaceSearchGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'label': value['label'],
        'items': ((value['items'] as Array<any>).map(WorkspaceSearchItemToJSON)),
    };
}

