/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkspaceInsightMetric
 */
export interface WorkspaceInsightMetric {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceInsightMetric
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceInsightMetric
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceInsightMetric
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceInsightMetric
     */
    tone?: string;
}

/**
 * Check if a given object implements the WorkspaceInsightMetric interface.
 */
export function instanceOfWorkspaceInsightMetric(value: object): value is WorkspaceInsightMetric {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function WorkspaceInsightMetricFromJSON(json: any): WorkspaceInsightMetric {
    return WorkspaceInsightMetricFromJSONTyped(json, false);
}

export function WorkspaceInsightMetricFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceInsightMetric {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'label': json['label'],
        'value': json['value'],
        'tone': json['tone'] == null ? undefined : json['tone'],
    };
}

export function WorkspaceInsightMetricToJSON(json: any): WorkspaceInsightMetric {
    return WorkspaceInsightMetricToJSONTyped(json, false);
}

export function WorkspaceInsightMetricToJSONTyped(value?: WorkspaceInsightMetric | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'label': value['label'],
        'value': value['value'],
        'tone': value['tone'],
    };
}

