/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkspaceActivityItem
 */
export interface WorkspaceActivityItem {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceActivityItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceActivityItem
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceActivityItem
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceActivityItem
     */
    subtitle?: string;
    /**
     * 
     * @type {Date}
     * @memberof WorkspaceActivityItem
     */
    timestamp: Date;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceActivityItem
     */
    to?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceActivityItem
     */
    severity?: string;
}

/**
 * Check if a given object implements the WorkspaceActivityItem interface.
 */
export function instanceOfWorkspaceActivityItem(value: object): value is WorkspaceActivityItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function WorkspaceActivityItemFromJSON(json: any): WorkspaceActivityItem {
    return WorkspaceActivityItemFromJSONTyped(json, false);
}

export function WorkspaceActivityItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceActivityItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'title': json['title'],
        'subtitle': json['subtitle'] == null ? undefined : json['subtitle'],
        'timestamp': (new Date(json['timestamp'])),
        'to': json['to'] == null ? undefined : json['to'],
        'severity': json['severity'] == null ? undefined : json['severity'],
    };
}

export function WorkspaceActivityItemToJSON(json: any): WorkspaceActivityItem {
    return WorkspaceActivityItemToJSONTyped(json, false);
}

export function WorkspaceActivityItemToJSONTyped(value?: WorkspaceActivityItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'title': value['title'],
        'subtitle': value['subtitle'],
        'timestamp': value['timestamp'].toISOString(),
        'to': value['to'],
        'severity': value['severity'],
    };
}

