/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CallerContext,
  CreateSessionRequest,
  CreateSessionResponse,
  ErrorResponse,
  OrganizationAccess,
  SimpleOKResponse,
  SwitchOrganizationRequest,
} from '../models/index';
import {
    CallerContextFromJSON,
    CallerContextToJSON,
    CreateSessionRequestFromJSON,
    CreateSessionRequestToJSON,
    CreateSessionResponseFromJSON,
    CreateSessionResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    OrganizationAccessFromJSON,
    OrganizationAccessToJSON,
    SimpleOKResponseFromJSON,
    SimpleOKResponseToJSON,
    SwitchOrganizationRequestFromJSON,
    SwitchOrganizationRequestToJSON,
} from '../models/index';

export interface CreateSessionOperationRequest {
    createSessionRequest: CreateSessionRequest;
}

export interface SwitchOrganizationOperationRequest {
    switchOrganizationRequest: SwitchOrganizationRequest;
}

/**
 * AuthApi - interface
 * 
 * @export
 * @interface AuthApiInterface
 */
export interface AuthApiInterface {
    /**
     * Creates request options for createSession without sending the request
     * @param {CreateSessionRequest} createSessionRequest 
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    createSessionRequestOpts(requestParameters: CreateSessionOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Start session
     * @param {CreateSessionRequest} createSessionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    createSessionRaw(requestParameters: CreateSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSessionResponse>>;

    /**
     * Start session
     */
    createSession(requestParameters: CreateSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSessionResponse>;

    /**
     * Creates request options for getMe without sending the request
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    getMeRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Current caller context
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    getMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CallerContext>>;

    /**
     * Current caller context
     */
    getMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CallerContext>;

    /**
     * Creates request options for listOrganizationAccess without sending the request
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    listOrganizationAccessRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List the caller\'s active organization access
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    listOrganizationAccessRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrganizationAccess>>>;

    /**
     * List the caller\'s active organization access
     */
    listOrganizationAccess(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrganizationAccess>>;

    /**
     * Creates request options for logout without sending the request
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    logoutRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary End session
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    logoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleOKResponse>>;

    /**
     * End session
     */
    logout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleOKResponse>;

    /**
     * Creates request options for refreshSession without sending the request
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    refreshSessionRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Refresh session
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    refreshSessionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSessionResponse>>;

    /**
     * Refresh session
     */
    refreshSession(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSessionResponse>;

    /**
     * Creates request options for switchOrganization without sending the request
     * @param {SwitchOrganizationRequest} switchOrganizationRequest 
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    switchOrganizationRequestOpts(requestParameters: SwitchOrganizationOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Select an organization and issue a session with its current capabilities
     * @param {SwitchOrganizationRequest} switchOrganizationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    switchOrganizationRaw(requestParameters: SwitchOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSessionResponse>>;

    /**
     * Select an organization and issue a session with its current capabilities
     */
    switchOrganization(requestParameters: SwitchOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSessionResponse>;

}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI implements AuthApiInterface {

    /**
     * Creates request options for createSession without sending the request
     */
    async createSessionRequestOpts(requestParameters: CreateSessionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'createSessionRequest',
                'Required parameter "createSessionRequest" was null or undefined when calling createSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/auth/session`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSessionRequestToJSON(requestParameters['createSessionRequest']),
        };
    }

    /**
     * Start session
     */
    async createSessionRaw(requestParameters: CreateSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSessionResponse>> {
        const requestOptions = await this.createSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateSessionResponseFromJSON(jsonValue));
    }

    /**
     * Start session
     */
    async createSession(requestParameters: CreateSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSessionResponse> {
        const response = await this.createSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMe without sending the request
     */
    async getMeRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/auth/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Current caller context
     */
    async getMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CallerContext>> {
        const requestOptions = await this.getMeRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CallerContextFromJSON(jsonValue));
    }

    /**
     * Current caller context
     */
    async getMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CallerContext> {
        const response = await this.getMeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listOrganizationAccess without sending the request
     */
    async listOrganizationAccessRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/auth/organizations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the caller\'s active organization access
     */
    async listOrganizationAccessRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrganizationAccess>>> {
        const requestOptions = await this.listOrganizationAccessRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrganizationAccessFromJSON));
    }

    /**
     * List the caller\'s active organization access
     */
    async listOrganizationAccess(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrganizationAccess>> {
        const response = await this.listOrganizationAccessRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for logout without sending the request
     */
    async logoutRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/auth/logout`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * End session
     */
    async logoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleOKResponse>> {
        const requestOptions = await this.logoutRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimpleOKResponseFromJSON(jsonValue));
    }

    /**
     * End session
     */
    async logout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleOKResponse> {
        const response = await this.logoutRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for refreshSession without sending the request
     */
    async refreshSessionRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/auth/refresh`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Refresh session
     */
    async refreshSessionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSessionResponse>> {
        const requestOptions = await this.refreshSessionRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateSessionResponseFromJSON(jsonValue));
    }

    /**
     * Refresh session
     */
    async refreshSession(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSessionResponse> {
        const response = await this.refreshSessionRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for switchOrganization without sending the request
     */
    async switchOrganizationRequestOpts(requestParameters: SwitchOrganizationOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['switchOrganizationRequest'] == null) {
            throw new runtime.RequiredError(
                'switchOrganizationRequest',
                'Required parameter "switchOrganizationRequest" was null or undefined when calling switchOrganization().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/auth/organization`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SwitchOrganizationRequestToJSON(requestParameters['switchOrganizationRequest']),
        };
    }

    /**
     * Select an organization and issue a session with its current capabilities
     */
    async switchOrganizationRaw(requestParameters: SwitchOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSessionResponse>> {
        const requestOptions = await this.switchOrganizationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateSessionResponseFromJSON(jsonValue));
    }

    /**
     * Select an organization and issue a session with its current capabilities
     */
    async switchOrganization(requestParameters: SwitchOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSessionResponse> {
        const response = await this.switchOrganizationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
