/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BillingHostedAction,
  ErrorResponse,
  VendorBillingSummary,
  VendorCheckoutInput,
  VendorPrice,
} from '../models/index';
import {
    BillingHostedActionFromJSON,
    BillingHostedActionToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    VendorBillingSummaryFromJSON,
    VendorBillingSummaryToJSON,
    VendorCheckoutInputFromJSON,
    VendorCheckoutInputToJSON,
    VendorPriceFromJSON,
    VendorPriceToJSON,
} from '../models/index';

export interface OpenVendorBillingPortalRequest {
    body: object;
}

export interface ReceiveStripeBillingWebhookRequest {
    stripeSignature: string;
    requestBody: { [key: string]: any; };
}

export interface RefreshVendorBillingRequest {
    body: object;
}

export interface StartVendorCheckoutRequest {
    vendorCheckoutInput: VendorCheckoutInput;
}

/**
 * BillingApi - interface
 * 
 * @export
 * @interface BillingApiInterface
 */
export interface BillingApiInterface {
    /**
     * Creates request options for getVendorBilling without sending the request
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    getVendorBillingRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Requires the current vendor organization administrator and billing.manage. No caller-supplied organization or customer is accepted.
     * @summary Read current organization billing
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    getVendorBillingRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VendorBillingSummary>>;

    /**
     * Requires the current vendor organization administrator and billing.manage. No caller-supplied organization or customer is accepted.
     * Read current organization billing
     */
    getVendorBilling(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VendorBillingSummary>;

    /**
     * Creates request options for listVendorPlans without sending the request
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    listVendorPlansRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Amounts and currencies come from configured Stripe prices. Provider IDs are private. Prices are cached for five minutes; checkout validates the current provider price again.
     * @summary Read available organization prices
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    listVendorPlansRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<VendorPrice>>>;

    /**
     * Amounts and currencies come from configured Stripe prices. Provider IDs are private. Prices are cached for five minutes; checkout validates the current provider price again.
     * Read available organization prices
     */
    listVendorPlans(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<VendorPrice>>;

    /**
     * Creates request options for openVendorBillingPortal without sending the request
     * @param {object} body 
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    openVendorBillingPortalRequestOpts(requestParameters: OpenVendorBillingPortalRequest): Promise<runtime.RequestOpts>;

    /**
     * Requires billing.manage and current vendor administrator access. Available after paid access lapses. The server selects the mapped customer and validated full or restricted recovery portal configuration.
     * @summary Open hosted billing management and recovery
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    openVendorBillingPortalRaw(requestParameters: OpenVendorBillingPortalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BillingHostedAction>>;

    /**
     * Requires billing.manage and current vendor administrator access. Available after paid access lapses. The server selects the mapped customer and validated full or restricted recovery portal configuration.
     * Open hosted billing management and recovery
     */
    openVendorBillingPortal(requestParameters: OpenVendorBillingPortalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BillingHostedAction>;

    /**
     * Creates request options for receiveStripeBillingWebhook without sending the request
     * @param {string} stripeSignature 
     * @param {{ [key: string]: any; }} requestBody 
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    receiveStripeBillingWebhookRequestOpts(requestParameters: ReceiveStripeBillingWebhookRequest): Promise<runtime.RequestOpts>;

    /**
     * The untouched body is limited to 1 MiB. Only valid signed events in the configured test/live mode are accepted; recognized events are acknowledged after durable idempotent capture. Signed unsupported event types are acknowledged without persistence.
     * @summary Verify and durably capture a Stripe event
     * @param {string} stripeSignature 
     * @param {{ [key: string]: any; }} requestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    receiveStripeBillingWebhookRaw(requestParameters: ReceiveStripeBillingWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * The untouched body is limited to 1 MiB. Only valid signed events in the configured test/live mode are accepted; recognized events are acknowledged after durable idempotent capture. Signed unsupported event types are acknowledged without persistence.
     * Verify and durably capture a Stripe event
     */
    receiveStripeBillingWebhook(requestParameters: ReceiveStripeBillingWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for refreshVendorBilling without sending the request
     * @param {object} body 
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    refreshVendorBillingRequestOpts(requestParameters: RefreshVendorBillingRequest): Promise<runtime.RequestOpts>;

    /**
     * Requires billing.manage and current vendor administrator access. A return from hosted checkout is not proof of payment; reconciliation retrieves authoritative provider state.
     * @summary Reconcile current organization subscription
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    refreshVendorBillingRaw(requestParameters: RefreshVendorBillingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VendorBillingSummary>>;

    /**
     * Requires billing.manage and current vendor administrator access. A return from hosted checkout is not proof of payment; reconciliation retrieves authoritative provider state.
     * Reconcile current organization subscription
     */
    refreshVendorBilling(requestParameters: RefreshVendorBillingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VendorBillingSummary>;

    /**
     * Creates request options for startVendorCheckout without sending the request
     * @param {VendorCheckoutInput} vendorCheckoutInput 
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    startVendorCheckoutRequestOpts(requestParameters: StartVendorCheckoutRequest): Promise<runtime.RequestOpts>;

    /**
     * Requires billing.manage and current vendor administrator access. Server-persisted operation identities provide idempotency. An unresolved checkout is recovered before a new one can be created. Existing subscriptions must be managed through the portal.
     * @summary Start or recover hosted organization checkout
     * @param {VendorCheckoutInput} vendorCheckoutInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    startVendorCheckoutRaw(requestParameters: StartVendorCheckoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BillingHostedAction>>;

    /**
     * Requires billing.manage and current vendor administrator access. Server-persisted operation identities provide idempotency. An unresolved checkout is recovered before a new one can be created. Existing subscriptions must be managed through the portal.
     * Start or recover hosted organization checkout
     */
    startVendorCheckout(requestParameters: StartVendorCheckoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BillingHostedAction>;

}

/**
 * 
 */
export class BillingApi extends runtime.BaseAPI implements BillingApiInterface {

    /**
     * Creates request options for getVendorBilling without sending the request
     */
    async getVendorBillingRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/billing`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Requires the current vendor organization administrator and billing.manage. No caller-supplied organization or customer is accepted.
     * Read current organization billing
     */
    async getVendorBillingRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VendorBillingSummary>> {
        const requestOptions = await this.getVendorBillingRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VendorBillingSummaryFromJSON(jsonValue));
    }

    /**
     * Requires the current vendor organization administrator and billing.manage. No caller-supplied organization or customer is accepted.
     * Read current organization billing
     */
    async getVendorBilling(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VendorBillingSummary> {
        const response = await this.getVendorBillingRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listVendorPlans without sending the request
     */
    async listVendorPlansRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/vendor-plans`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Amounts and currencies come from configured Stripe prices. Provider IDs are private. Prices are cached for five minutes; checkout validates the current provider price again.
     * Read available organization prices
     */
    async listVendorPlansRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<VendorPrice>>> {
        const requestOptions = await this.listVendorPlansRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VendorPriceFromJSON));
    }

    /**
     * Amounts and currencies come from configured Stripe prices. Provider IDs are private. Prices are cached for five minutes; checkout validates the current provider price again.
     * Read available organization prices
     */
    async listVendorPlans(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<VendorPrice>> {
        const response = await this.listVendorPlansRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for openVendorBillingPortal without sending the request
     */
    async openVendorBillingPortalRequestOpts(requestParameters: OpenVendorBillingPortalRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling openVendorBillingPortal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/billing/portal`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Requires billing.manage and current vendor administrator access. Available after paid access lapses. The server selects the mapped customer and validated full or restricted recovery portal configuration.
     * Open hosted billing management and recovery
     */
    async openVendorBillingPortalRaw(requestParameters: OpenVendorBillingPortalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BillingHostedAction>> {
        const requestOptions = await this.openVendorBillingPortalRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BillingHostedActionFromJSON(jsonValue));
    }

    /**
     * Requires billing.manage and current vendor administrator access. Available after paid access lapses. The server selects the mapped customer and validated full or restricted recovery portal configuration.
     * Open hosted billing management and recovery
     */
    async openVendorBillingPortal(requestParameters: OpenVendorBillingPortalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BillingHostedAction> {
        const response = await this.openVendorBillingPortalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for receiveStripeBillingWebhook without sending the request
     */
    async receiveStripeBillingWebhookRequestOpts(requestParameters: ReceiveStripeBillingWebhookRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['stripeSignature'] == null) {
            throw new runtime.RequiredError(
                'stripeSignature',
                'Required parameter "stripeSignature" was null or undefined when calling receiveStripeBillingWebhook().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling receiveStripeBillingWebhook().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['stripeSignature'] != null) {
            headerParameters['Stripe-Signature'] = String(requestParameters['stripeSignature']);
        }


        let urlPath = `/billing/webhooks/stripe`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        };
    }

    /**
     * The untouched body is limited to 1 MiB. Only valid signed events in the configured test/live mode are accepted; recognized events are acknowledged after durable idempotent capture. Signed unsupported event types are acknowledged without persistence.
     * Verify and durably capture a Stripe event
     */
    async receiveStripeBillingWebhookRaw(requestParameters: ReceiveStripeBillingWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.receiveStripeBillingWebhookRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * The untouched body is limited to 1 MiB. Only valid signed events in the configured test/live mode are accepted; recognized events are acknowledged after durable idempotent capture. Signed unsupported event types are acknowledged without persistence.
     * Verify and durably capture a Stripe event
     */
    async receiveStripeBillingWebhook(requestParameters: ReceiveStripeBillingWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.receiveStripeBillingWebhookRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for refreshVendorBilling without sending the request
     */
    async refreshVendorBillingRequestOpts(requestParameters: RefreshVendorBillingRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling refreshVendorBilling().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/billing/refresh`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Requires billing.manage and current vendor administrator access. A return from hosted checkout is not proof of payment; reconciliation retrieves authoritative provider state.
     * Reconcile current organization subscription
     */
    async refreshVendorBillingRaw(requestParameters: RefreshVendorBillingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VendorBillingSummary>> {
        const requestOptions = await this.refreshVendorBillingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VendorBillingSummaryFromJSON(jsonValue));
    }

    /**
     * Requires billing.manage and current vendor administrator access. A return from hosted checkout is not proof of payment; reconciliation retrieves authoritative provider state.
     * Reconcile current organization subscription
     */
    async refreshVendorBilling(requestParameters: RefreshVendorBillingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VendorBillingSummary> {
        const response = await this.refreshVendorBillingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for startVendorCheckout without sending the request
     */
    async startVendorCheckoutRequestOpts(requestParameters: StartVendorCheckoutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['vendorCheckoutInput'] == null) {
            throw new runtime.RequiredError(
                'vendorCheckoutInput',
                'Required parameter "vendorCheckoutInput" was null or undefined when calling startVendorCheckout().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/billing/checkout`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VendorCheckoutInputToJSON(requestParameters['vendorCheckoutInput']),
        };
    }

    /**
     * Requires billing.manage and current vendor administrator access. Server-persisted operation identities provide idempotency. An unresolved checkout is recovered before a new one can be created. Existing subscriptions must be managed through the portal.
     * Start or recover hosted organization checkout
     */
    async startVendorCheckoutRaw(requestParameters: StartVendorCheckoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BillingHostedAction>> {
        const requestOptions = await this.startVendorCheckoutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BillingHostedActionFromJSON(jsonValue));
    }

    /**
     * Requires billing.manage and current vendor administrator access. Server-persisted operation identities provide idempotency. An unresolved checkout is recovered before a new one can be created. Existing subscriptions must be managed through the portal.
     * Start or recover hosted organization checkout
     */
    async startVendorCheckout(requestParameters: StartVendorCheckoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BillingHostedAction> {
        const response = await this.startVendorCheckoutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
