/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateManagedDocumentRequest,
  CreateVideoRequest,
  DocumentRevision,
  DocumentRevisionInput,
  DocumentVisibilityRequest,
  DocumentWithdrawalRequest,
  ErrorResponse,
  ManagedDocument,
  ManagedDocumentPage,
  VideoPlayback,
  VideoUploadConfirmation,
} from '../models/index';
import {
    CreateManagedDocumentRequestFromJSON,
    CreateManagedDocumentRequestToJSON,
    CreateVideoRequestFromJSON,
    CreateVideoRequestToJSON,
    DocumentRevisionFromJSON,
    DocumentRevisionToJSON,
    DocumentRevisionInputFromJSON,
    DocumentRevisionInputToJSON,
    DocumentVisibilityRequestFromJSON,
    DocumentVisibilityRequestToJSON,
    DocumentWithdrawalRequestFromJSON,
    DocumentWithdrawalRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ManagedDocumentFromJSON,
    ManagedDocumentToJSON,
    ManagedDocumentPageFromJSON,
    ManagedDocumentPageToJSON,
    VideoPlaybackFromJSON,
    VideoPlaybackToJSON,
    VideoUploadConfirmationFromJSON,
    VideoUploadConfirmationToJSON,
} from '../models/index';

export interface AddDocumentRevisionRequest {
    id: string;
    documentRevisionInput: DocumentRevisionInput;
}

export interface ConfirmVideoUploadRequest {
    id: string;
    videoUploadConfirmation: VideoUploadConfirmation;
}

export interface CreateManagedDocumentOperationRequest {
    idempotencyKey: string;
    createManagedDocumentRequest: CreateManagedDocumentRequest;
}

export interface CreateVideoOperationRequest {
    idempotencyKey: string;
    createVideoRequest: CreateVideoRequest;
}

export interface GetDocumentAssetRequest {
    id: string;
    revision: string;
    name: string;
    range?: string;
    download?: GetDocumentAssetDownloadEnum;
}

export interface GetManagedDocumentRequest {
    id: string;
}

export interface GetVideoRequest {
    id: string;
}

export interface GetVideoPlaybackRequest {
    id: string;
    revisionId?: string;
}

export interface HeadDocumentAssetRequest {
    id: string;
    revision: string;
    name: string;
    range?: string;
    download?: HeadDocumentAssetDownloadEnum;
}

export interface ListManagedDocumentsRequest {
    productId: string;
    limit?: number;
    offset?: number;
}

export interface PublishDocumentRevisionRequest {
    id: string;
    revision: string;
}

export interface RetryDocumentProcessingRequest {
    id: string;
    revision: string;
}

export interface SetDocumentHospitalVisibilityRequest {
    id: string;
    documentVisibilityRequest: DocumentVisibilityRequest;
}

export interface UploadDocumentSourceRequest {
    id: string;
    revision: string;
    body: Blob;
}

export interface WithdrawDocumentRevisionRequest {
    id: string;
    revision: string;
    documentWithdrawalRequest: DocumentWithdrawalRequest;
}

/**
 * DocumentsApi - interface
 * 
 * @export
 * @interface DocumentsApiInterface
 */
export interface DocumentsApiInterface {
    /**
     * Creates request options for addDocumentRevision without sending the request
     * @param {string} id 
     * @param {DocumentRevisionInput} documentRevisionInput 
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    addDocumentRevisionRequestOpts(requestParameters: AddDocumentRevisionRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create or resume a draft with identical metadata
     * @param {string} id 
     * @param {DocumentRevisionInput} documentRevisionInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    addDocumentRevisionRaw(requestParameters: AddDocumentRevisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DocumentRevision>>;

    /**
     * Create or resume a draft with identical metadata
     */
    addDocumentRevision(requestParameters: AddDocumentRevisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DocumentRevision>;

    /**
     * Creates request options for confirmVideoUpload without sending the request
     * @param {string} id 
     * @param {VideoUploadConfirmation} videoUploadConfirmation 
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    confirmVideoUploadRequestOpts(requestParameters: ConfirmVideoUploadRequest): Promise<runtime.RequestOpts>;

    /**
     * Upload through the document source endpoint first. It verifies the bytes and queues processing atomically. This idempotent confirmation cannot accept an incomplete source.
     * @summary Confirm a complete source upload
     * @param {string} id 
     * @param {VideoUploadConfirmation} videoUploadConfirmation 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    confirmVideoUploadRaw(requestParameters: ConfirmVideoUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Upload through the document source endpoint first. It verifies the bytes and queues processing atomically. This idempotent confirmation cannot accept an incomplete source.
     * Confirm a complete source upload
     */
    confirmVideoUpload(requestParameters: ConfirmVideoUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for createManagedDocument without sending the request
     * @param {string} idempotencyKey Reuse the same UUID only for an identical submission.
     * @param {CreateManagedDocumentRequest} createManagedDocumentRequest 
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    createManagedDocumentRequestOpts(requestParameters: CreateManagedDocumentOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a private document and draft revision
     * @param {string} idempotencyKey Reuse the same UUID only for an identical submission.
     * @param {CreateManagedDocumentRequest} createManagedDocumentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    createManagedDocumentRaw(requestParameters: CreateManagedDocumentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ManagedDocument>>;

    /**
     * Create a private document and draft revision
     */
    createManagedDocument(requestParameters: CreateManagedDocumentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ManagedDocument>;

    /**
     * Creates request options for createVideo without sending the request
     * @param {string} idempotencyKey 
     * @param {CreateVideoRequest} createVideoRequest 
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    createVideoRequestOpts(requestParameters: CreateVideoOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a private video and draft revision
     * @param {string} idempotencyKey 
     * @param {CreateVideoRequest} createVideoRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    createVideoRaw(requestParameters: CreateVideoOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ManagedDocument>>;

    /**
     * Create a private video and draft revision
     */
    createVideo(requestParameters: CreateVideoOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ManagedDocument>;

    /**
     * Creates request options for getDocumentAsset without sending the request
     * @param {string} id 
     * @param {string} revision 
     * @param {string} name 
     * @param {string} [range] One bytes range. Multiple ranges are rejected.
     * @param {'1'} [download] 
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    getDocumentAssetRequestOpts(requestParameters: GetDocumentAssetRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Authorize and deliver a private document asset
     * @param {string} id 
     * @param {string} revision 
     * @param {string} name 
     * @param {string} [range] One bytes range. Multiple ranges are rejected.
     * @param {'1'} [download] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    getDocumentAssetRaw(requestParameters: GetDocumentAssetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>>;

    /**
     * Authorize and deliver a private document asset
     */
    getDocumentAsset(requestParameters: GetDocumentAssetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob>;

    /**
     * Creates request options for getManagedDocument without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    getManagedDocumentRequestOpts(requestParameters: GetManagedDocumentRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get a document and its permitted revisions
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    getManagedDocumentRaw(requestParameters: GetManagedDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ManagedDocument>>;

    /**
     * Get a document and its permitted revisions
     */
    getManagedDocument(requestParameters: GetManagedDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ManagedDocument>;

    /**
     * Creates request options for getVideo without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    getVideoRequestOpts(requestParameters: GetVideoRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Read authorized video metadata
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    getVideoRaw(requestParameters: GetVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ManagedDocument>>;

    /**
     * Read authorized video metadata
     */
    getVideo(requestParameters: GetVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ManagedDocument>;

    /**
     * Creates request options for getVideoPlayback without sending the request
     * @param {string} id 
     * @param {string} [revisionId] 
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    getVideoPlaybackRequestOpts(requestParameters: GetVideoPlaybackRequest): Promise<runtime.RequestOpts>;

    /**
     * Every manifest, caption and segment request requires a valid short-lived signed application session and live tenant authorization. URLs contain no bearer secrets.
     * @summary Resolve authenticated video playback
     * @param {string} id 
     * @param {string} [revisionId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    getVideoPlaybackRaw(requestParameters: GetVideoPlaybackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoPlayback>>;

    /**
     * Every manifest, caption and segment request requires a valid short-lived signed application session and live tenant authorization. URLs contain no bearer secrets.
     * Resolve authenticated video playback
     */
    getVideoPlayback(requestParameters: GetVideoPlaybackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoPlayback>;

    /**
     * Creates request options for headDocumentAsset without sending the request
     * @param {string} id 
     * @param {string} revision 
     * @param {string} name 
     * @param {string} [range] One bytes range. Multiple ranges are rejected.
     * @param {'1'} [download] 
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    headDocumentAssetRequestOpts(requestParameters: HeadDocumentAssetRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Authorize and deliver a private document asset
     * @param {string} id 
     * @param {string} revision 
     * @param {string} name 
     * @param {string} [range] One bytes range. Multiple ranges are rejected.
     * @param {'1'} [download] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    headDocumentAssetRaw(requestParameters: HeadDocumentAssetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Authorize and deliver a private document asset
     */
    headDocumentAsset(requestParameters: HeadDocumentAssetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for listManagedDocuments without sending the request
     * @param {string} productId 
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    listManagedDocumentsRequestOpts(requestParameters: ListManagedDocumentsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List private documents for a device
     * @param {string} productId 
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    listManagedDocumentsRaw(requestParameters: ListManagedDocumentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ManagedDocumentPage>>;

    /**
     * List private documents for a device
     */
    listManagedDocuments(requestParameters: ListManagedDocumentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ManagedDocumentPage>;

    /**
     * Creates request options for publishDocumentRevision without sending the request
     * @param {string} id 
     * @param {string} revision 
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    publishDocumentRevisionRequestOpts(requestParameters: PublishDocumentRevisionRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Publish a validated revision to eligible libraries
     * @param {string} id 
     * @param {string} revision 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    publishDocumentRevisionRaw(requestParameters: PublishDocumentRevisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Publish a validated revision to eligible libraries
     */
    publishDocumentRevision(requestParameters: PublishDocumentRevisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for retryDocumentProcessing without sending the request
     * @param {string} id 
     * @param {string} revision 
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    retryDocumentProcessingRequestOpts(requestParameters: RetryDocumentProcessingRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Request processing retry for a failed draft
     * @param {string} id 
     * @param {string} revision 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    retryDocumentProcessingRaw(requestParameters: RetryDocumentProcessingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Request processing retry for a failed draft
     */
    retryDocumentProcessing(requestParameters: RetryDocumentProcessingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for setDocumentHospitalVisibility without sending the request
     * @param {string} id 
     * @param {DocumentVisibilityRequest} documentVisibilityRequest 
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    setDocumentHospitalVisibilityRequestOpts(requestParameters: SetDocumentHospitalVisibilityRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Set visibility in the current hospital library
     * @param {string} id 
     * @param {DocumentVisibilityRequest} documentVisibilityRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    setDocumentHospitalVisibilityRaw(requestParameters: SetDocumentHospitalVisibilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Set visibility in the current hospital library
     */
    setDocumentHospitalVisibility(requestParameters: SetDocumentHospitalVisibilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for uploadDocumentSource without sending the request
     * @param {string} id 
     * @param {string} revision 
     * @param {Blob} body 
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    uploadDocumentSourceRequestOpts(requestParameters: UploadDocumentSourceRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Upload source bytes for validation and processing
     * @param {string} id 
     * @param {string} revision 
     * @param {Blob} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    uploadDocumentSourceRaw(requestParameters: UploadDocumentSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Upload source bytes for validation and processing
     */
    uploadDocumentSource(requestParameters: UploadDocumentSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for withdrawDocumentRevision without sending the request
     * @param {string} id 
     * @param {string} revision 
     * @param {DocumentWithdrawalRequest} documentWithdrawalRequest 
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    withdrawDocumentRevisionRequestOpts(requestParameters: WithdrawDocumentRevisionRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Withdraw a revision and invalidate its delivery
     * @param {string} id 
     * @param {string} revision 
     * @param {DocumentWithdrawalRequest} documentWithdrawalRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    withdrawDocumentRevisionRaw(requestParameters: WithdrawDocumentRevisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Withdraw a revision and invalidate its delivery
     */
    withdrawDocumentRevision(requestParameters: WithdrawDocumentRevisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class DocumentsApi extends runtime.BaseAPI implements DocumentsApiInterface {

    /**
     * Creates request options for addDocumentRevision without sending the request
     */
    async addDocumentRevisionRequestOpts(requestParameters: AddDocumentRevisionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling addDocumentRevision().'
            );
        }

        if (requestParameters['documentRevisionInput'] == null) {
            throw new runtime.RequiredError(
                'documentRevisionInput',
                'Required parameter "documentRevisionInput" was null or undefined when calling addDocumentRevision().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/documents/{id}/revisions`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DocumentRevisionInputToJSON(requestParameters['documentRevisionInput']),
        };
    }

    /**
     * Create or resume a draft with identical metadata
     */
    async addDocumentRevisionRaw(requestParameters: AddDocumentRevisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DocumentRevision>> {
        const requestOptions = await this.addDocumentRevisionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DocumentRevisionFromJSON(jsonValue));
    }

    /**
     * Create or resume a draft with identical metadata
     */
    async addDocumentRevision(requestParameters: AddDocumentRevisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DocumentRevision> {
        const response = await this.addDocumentRevisionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for confirmVideoUpload without sending the request
     */
    async confirmVideoUploadRequestOpts(requestParameters: ConfirmVideoUploadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling confirmVideoUpload().'
            );
        }

        if (requestParameters['videoUploadConfirmation'] == null) {
            throw new runtime.RequiredError(
                'videoUploadConfirmation',
                'Required parameter "videoUploadConfirmation" was null or undefined when calling confirmVideoUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/videos/{id}/upload-complete`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VideoUploadConfirmationToJSON(requestParameters['videoUploadConfirmation']),
        };
    }

    /**
     * Upload through the document source endpoint first. It verifies the bytes and queues processing atomically. This idempotent confirmation cannot accept an incomplete source.
     * Confirm a complete source upload
     */
    async confirmVideoUploadRaw(requestParameters: ConfirmVideoUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.confirmVideoUploadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Upload through the document source endpoint first. It verifies the bytes and queues processing atomically. This idempotent confirmation cannot accept an incomplete source.
     * Confirm a complete source upload
     */
    async confirmVideoUpload(requestParameters: ConfirmVideoUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.confirmVideoUploadRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for createManagedDocument without sending the request
     */
    async createManagedDocumentRequestOpts(requestParameters: CreateManagedDocumentOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createManagedDocument().'
            );
        }

        if (requestParameters['createManagedDocumentRequest'] == null) {
            throw new runtime.RequiredError(
                'createManagedDocumentRequest',
                'Required parameter "createManagedDocumentRequest" was null or undefined when calling createManagedDocument().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/documents/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateManagedDocumentRequestToJSON(requestParameters['createManagedDocumentRequest']),
        };
    }

    /**
     * Create a private document and draft revision
     */
    async createManagedDocumentRaw(requestParameters: CreateManagedDocumentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ManagedDocument>> {
        const requestOptions = await this.createManagedDocumentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ManagedDocumentFromJSON(jsonValue));
    }

    /**
     * Create a private document and draft revision
     */
    async createManagedDocument(requestParameters: CreateManagedDocumentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ManagedDocument> {
        const response = await this.createManagedDocumentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createVideo without sending the request
     */
    async createVideoRequestOpts(requestParameters: CreateVideoOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createVideo().'
            );
        }

        if (requestParameters['createVideoRequest'] == null) {
            throw new runtime.RequiredError(
                'createVideoRequest',
                'Required parameter "createVideoRequest" was null or undefined when calling createVideo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/videos/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateVideoRequestToJSON(requestParameters['createVideoRequest']),
        };
    }

    /**
     * Create a private video and draft revision
     */
    async createVideoRaw(requestParameters: CreateVideoOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ManagedDocument>> {
        const requestOptions = await this.createVideoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ManagedDocumentFromJSON(jsonValue));
    }

    /**
     * Create a private video and draft revision
     */
    async createVideo(requestParameters: CreateVideoOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ManagedDocument> {
        const response = await this.createVideoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDocumentAsset without sending the request
     */
    async getDocumentAssetRequestOpts(requestParameters: GetDocumentAssetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDocumentAsset().'
            );
        }

        if (requestParameters['revision'] == null) {
            throw new runtime.RequiredError(
                'revision',
                'Required parameter "revision" was null or undefined when calling getDocumentAsset().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getDocumentAsset().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['download'] != null) {
            queryParameters['download'] = requestParameters['download'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['range'] != null) {
            headerParameters['Range'] = String(requestParameters['range']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/documents/{id}/revisions/{revision}/assets/{name}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"revision"}}`, encodeURIComponent(String(requestParameters['revision'])));
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Authorize and deliver a private document asset
     */
    async getDocumentAssetRaw(requestParameters: GetDocumentAssetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.getDocumentAssetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Authorize and deliver a private document asset
     */
    async getDocumentAsset(requestParameters: GetDocumentAssetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.getDocumentAssetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getManagedDocument without sending the request
     */
    async getManagedDocumentRequestOpts(requestParameters: GetManagedDocumentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getManagedDocument().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/documents/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a document and its permitted revisions
     */
    async getManagedDocumentRaw(requestParameters: GetManagedDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ManagedDocument>> {
        const requestOptions = await this.getManagedDocumentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ManagedDocumentFromJSON(jsonValue));
    }

    /**
     * Get a document and its permitted revisions
     */
    async getManagedDocument(requestParameters: GetManagedDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ManagedDocument> {
        const response = await this.getManagedDocumentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getVideo without sending the request
     */
    async getVideoRequestOpts(requestParameters: GetVideoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getVideo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/videos/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read authorized video metadata
     */
    async getVideoRaw(requestParameters: GetVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ManagedDocument>> {
        const requestOptions = await this.getVideoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ManagedDocumentFromJSON(jsonValue));
    }

    /**
     * Read authorized video metadata
     */
    async getVideo(requestParameters: GetVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ManagedDocument> {
        const response = await this.getVideoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getVideoPlayback without sending the request
     */
    async getVideoPlaybackRequestOpts(requestParameters: GetVideoPlaybackRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getVideoPlayback().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['revisionId'] != null) {
            queryParameters['revision_id'] = requestParameters['revisionId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/videos/{id}/play`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Every manifest, caption and segment request requires a valid short-lived signed application session and live tenant authorization. URLs contain no bearer secrets.
     * Resolve authenticated video playback
     */
    async getVideoPlaybackRaw(requestParameters: GetVideoPlaybackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoPlayback>> {
        const requestOptions = await this.getVideoPlaybackRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoPlaybackFromJSON(jsonValue));
    }

    /**
     * Every manifest, caption and segment request requires a valid short-lived signed application session and live tenant authorization. URLs contain no bearer secrets.
     * Resolve authenticated video playback
     */
    async getVideoPlayback(requestParameters: GetVideoPlaybackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoPlayback> {
        const response = await this.getVideoPlaybackRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headDocumentAsset without sending the request
     */
    async headDocumentAssetRequestOpts(requestParameters: HeadDocumentAssetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling headDocumentAsset().'
            );
        }

        if (requestParameters['revision'] == null) {
            throw new runtime.RequiredError(
                'revision',
                'Required parameter "revision" was null or undefined when calling headDocumentAsset().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling headDocumentAsset().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['download'] != null) {
            queryParameters['download'] = requestParameters['download'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['range'] != null) {
            headerParameters['Range'] = String(requestParameters['range']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/documents/{id}/revisions/{revision}/assets/{name}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"revision"}}`, encodeURIComponent(String(requestParameters['revision'])));
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'HEAD',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Authorize and deliver a private document asset
     */
    async headDocumentAssetRaw(requestParameters: HeadDocumentAssetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.headDocumentAssetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Authorize and deliver a private document asset
     */
    async headDocumentAsset(requestParameters: HeadDocumentAssetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.headDocumentAssetRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listManagedDocuments without sending the request
     */
    async listManagedDocumentsRequestOpts(requestParameters: ListManagedDocumentsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling listManagedDocuments().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['productId'] != null) {
            queryParameters['product_id'] = requestParameters['productId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/documents/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List private documents for a device
     */
    async listManagedDocumentsRaw(requestParameters: ListManagedDocumentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ManagedDocumentPage>> {
        const requestOptions = await this.listManagedDocumentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ManagedDocumentPageFromJSON(jsonValue));
    }

    /**
     * List private documents for a device
     */
    async listManagedDocuments(requestParameters: ListManagedDocumentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ManagedDocumentPage> {
        const response = await this.listManagedDocumentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publishDocumentRevision without sending the request
     */
    async publishDocumentRevisionRequestOpts(requestParameters: PublishDocumentRevisionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling publishDocumentRevision().'
            );
        }

        if (requestParameters['revision'] == null) {
            throw new runtime.RequiredError(
                'revision',
                'Required parameter "revision" was null or undefined when calling publishDocumentRevision().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/documents/{id}/revisions/{revision}/publish`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"revision"}}`, encodeURIComponent(String(requestParameters['revision'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Publish a validated revision to eligible libraries
     */
    async publishDocumentRevisionRaw(requestParameters: PublishDocumentRevisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.publishDocumentRevisionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Publish a validated revision to eligible libraries
     */
    async publishDocumentRevision(requestParameters: PublishDocumentRevisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.publishDocumentRevisionRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for retryDocumentProcessing without sending the request
     */
    async retryDocumentProcessingRequestOpts(requestParameters: RetryDocumentProcessingRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling retryDocumentProcessing().'
            );
        }

        if (requestParameters['revision'] == null) {
            throw new runtime.RequiredError(
                'revision',
                'Required parameter "revision" was null or undefined when calling retryDocumentProcessing().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/documents/{id}/revisions/{revision}/retry`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"revision"}}`, encodeURIComponent(String(requestParameters['revision'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Request processing retry for a failed draft
     */
    async retryDocumentProcessingRaw(requestParameters: RetryDocumentProcessingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.retryDocumentProcessingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Request processing retry for a failed draft
     */
    async retryDocumentProcessing(requestParameters: RetryDocumentProcessingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.retryDocumentProcessingRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for setDocumentHospitalVisibility without sending the request
     */
    async setDocumentHospitalVisibilityRequestOpts(requestParameters: SetDocumentHospitalVisibilityRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling setDocumentHospitalVisibility().'
            );
        }

        if (requestParameters['documentVisibilityRequest'] == null) {
            throw new runtime.RequiredError(
                'documentVisibilityRequest',
                'Required parameter "documentVisibilityRequest" was null or undefined when calling setDocumentHospitalVisibility().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/documents/{id}/visibility`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: DocumentVisibilityRequestToJSON(requestParameters['documentVisibilityRequest']),
        };
    }

    /**
     * Set visibility in the current hospital library
     */
    async setDocumentHospitalVisibilityRaw(requestParameters: SetDocumentHospitalVisibilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.setDocumentHospitalVisibilityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Set visibility in the current hospital library
     */
    async setDocumentHospitalVisibility(requestParameters: SetDocumentHospitalVisibilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.setDocumentHospitalVisibilityRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for uploadDocumentSource without sending the request
     */
    async uploadDocumentSourceRequestOpts(requestParameters: UploadDocumentSourceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling uploadDocumentSource().'
            );
        }

        if (requestParameters['revision'] == null) {
            throw new runtime.RequiredError(
                'revision',
                'Required parameter "revision" was null or undefined when calling uploadDocumentSource().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling uploadDocumentSource().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/octet-stream';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/documents/{id}/revisions/{revision}/source`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"revision"}}`, encodeURIComponent(String(requestParameters['revision'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Upload source bytes for validation and processing
     */
    async uploadDocumentSourceRaw(requestParameters: UploadDocumentSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.uploadDocumentSourceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Upload source bytes for validation and processing
     */
    async uploadDocumentSource(requestParameters: UploadDocumentSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.uploadDocumentSourceRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for withdrawDocumentRevision without sending the request
     */
    async withdrawDocumentRevisionRequestOpts(requestParameters: WithdrawDocumentRevisionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling withdrawDocumentRevision().'
            );
        }

        if (requestParameters['revision'] == null) {
            throw new runtime.RequiredError(
                'revision',
                'Required parameter "revision" was null or undefined when calling withdrawDocumentRevision().'
            );
        }

        if (requestParameters['documentWithdrawalRequest'] == null) {
            throw new runtime.RequiredError(
                'documentWithdrawalRequest',
                'Required parameter "documentWithdrawalRequest" was null or undefined when calling withdrawDocumentRevision().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/documents/{id}/revisions/{revision}/withdraw`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"revision"}}`, encodeURIComponent(String(requestParameters['revision'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DocumentWithdrawalRequestToJSON(requestParameters['documentWithdrawalRequest']),
        };
    }

    /**
     * Withdraw a revision and invalidate its delivery
     */
    async withdrawDocumentRevisionRaw(requestParameters: WithdrawDocumentRevisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.withdrawDocumentRevisionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Withdraw a revision and invalidate its delivery
     */
    async withdrawDocumentRevision(requestParameters: WithdrawDocumentRevisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.withdrawDocumentRevisionRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const GetDocumentAssetDownloadEnum = {
    _1: '1'
} as const;
export type GetDocumentAssetDownloadEnum = typeof GetDocumentAssetDownloadEnum[keyof typeof GetDocumentAssetDownloadEnum];
/**
 * @export
 */
export const HeadDocumentAssetDownloadEnum = {
    _1: '1'
} as const;
export type HeadDocumentAssetDownloadEnum = typeof HeadDocumentAssetDownloadEnum[keyof typeof HeadDocumentAssetDownloadEnum];
