/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CalendarFeed,
  CalendarFeedScope,
  CalendarItem,
  CalendarScope,
  ErrorResponse,
  RecordEventAttendanceRequest,
  RotateCalendarFeedRequest,
  TrainingSessionRegistration,
} from '../models/index';
import {
    CalendarFeedFromJSON,
    CalendarFeedToJSON,
    CalendarFeedScopeFromJSON,
    CalendarFeedScopeToJSON,
    CalendarItemFromJSON,
    CalendarItemToJSON,
    CalendarScopeFromJSON,
    CalendarScopeToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    RecordEventAttendanceRequestFromJSON,
    RecordEventAttendanceRequestToJSON,
    RotateCalendarFeedRequestFromJSON,
    RotateCalendarFeedRequestToJSON,
    TrainingSessionRegistrationFromJSON,
    TrainingSessionRegistrationToJSON,
} from '../models/index';

export interface CancelEventRegistrationRequest {
    type: CancelEventRegistrationTypeEnum;
    id: string;
}

export interface ExportCalendarEventRequest {
    type: ExportCalendarEventTypeEnum;
    id: string;
}

export interface ListCalendarEventsRequest {
    start?: Date;
    end?: Date;
    scope?: CalendarScope;
    types?: string;
}

export interface ListEventRegistrationsRequest {
    type: ListEventRegistrationsTypeEnum;
    id: string;
}

export interface PublicCalendarFeedRequest {
    scope: CalendarFeedScope;
    token: string;
}

export interface RecordEventAttendanceOperationRequest {
    type: RecordEventAttendanceOperationTypeEnum;
    id: string;
    userID: string;
    recordEventAttendanceRequest: RecordEventAttendanceRequest;
}

export interface RegisterForEventRequest {
    type: RegisterForEventTypeEnum;
    id: string;
}

export interface RevokeCalendarFeedRequest {
    rotateCalendarFeedRequest: RotateCalendarFeedRequest;
}

export interface RotateCalendarFeedOperationRequest {
    rotateCalendarFeedRequest: RotateCalendarFeedRequest;
}

/**
 * EventsApi - interface
 * 
 * @export
 * @interface EventsApiInterface
 */
export interface EventsApiInterface {
    /**
     * Creates request options for cancelEventRegistration without sending the request
     * @param {'training' | 'webinar'} type 
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    cancelEventRegistrationRequestOpts(requestParameters: CancelEventRegistrationRequest): Promise<runtime.RequestOpts>;

    /**
     * Hospital learners read their own records; hospital administrators read only their hospital. Vendor and human platform roles have no access. Registration does not prove attendance or award credit.
     * @summary Cancel your pending event registration
     * @param {'training' | 'webinar'} type 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    cancelEventRegistrationRaw(requestParameters: CancelEventRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Hospital learners read their own records; hospital administrators read only their hospital. Vendor and human platform roles have no access. Registration does not prove attendance or award credit.
     * Cancel your pending event registration
     */
    cancelEventRegistration(requestParameters: CancelEventRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for exportCalendarEvent without sending the request
     * @param {'webinar' | 'training'} type 
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    exportCalendarEventRequestOpts(requestParameters: ExportCalendarEventRequest): Promise<runtime.RequestOpts>;

    /**
     * Private iCalendar download with the same stable UID, update sequence and cancellation status as subscriptions. Exporting is not registration or attendance.
     * @summary Export one authorized education event
     * @param {'webinar' | 'training'} type 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    exportCalendarEventRaw(requestParameters: ExportCalendarEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>>;

    /**
     * Private iCalendar download with the same stable UID, update sequence and cancellation status as subscriptions. Exporting is not registration or attendance.
     * Export one authorized education event
     */
    exportCalendarEvent(requestParameters: ExportCalendarEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob>;

    /**
     * Creates request options for listCalendarEvents without sending the request
     * @param {Date} [start] 
     * @param {Date} [end] 
     * @param {CalendarScope} [scope] 
     * @param {string} [types] Comma-separated event source types
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    listCalendarEventsRequestOpts(requestParameters: ListCalendarEventsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Unified calendar events
     * @param {Date} [start] 
     * @param {Date} [end] 
     * @param {CalendarScope} [scope] 
     * @param {string} [types] Comma-separated event source types
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    listCalendarEventsRaw(requestParameters: ListCalendarEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CalendarItem>>>;

    /**
     * Unified calendar events
     */
    listCalendarEvents(requestParameters: ListCalendarEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CalendarItem>>;

    /**
     * Creates request options for listCalendarFeeds without sending the request
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    listCalendarFeedsRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List calendar feeds
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    listCalendarFeedsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CalendarFeed>>>;

    /**
     * List calendar feeds
     */
    listCalendarFeeds(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CalendarFeed>>;

    /**
     * Creates request options for listEventRegistrations without sending the request
     * @param {'training' | 'webinar'} type 
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    listEventRegistrationsRequestOpts(requestParameters: ListEventRegistrationsRequest): Promise<runtime.RequestOpts>;

    /**
     * Hospital learners read their own records; hospital administrators read only their hospital. Vendor and human platform roles have no access. Registration does not prove attendance or award credit.
     * @summary Read private hospital event registrations
     * @param {'training' | 'webinar'} type 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    listEventRegistrationsRaw(requestParameters: ListEventRegistrationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TrainingSessionRegistration>>>;

    /**
     * Hospital learners read their own records; hospital administrators read only their hospital. Vendor and human platform roles have no access. Registration does not prove attendance or award credit.
     * Read private hospital event registrations
     */
    listEventRegistrations(requestParameters: ListEventRegistrationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TrainingSessionRegistration>>;

    /**
     * Creates request options for publicCalendarFeed without sending the request
     * @param {CalendarFeedScope} scope 
     * @param {string} token 
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    publicCalendarFeedRequestOpts(requestParameters: PublicCalendarFeedRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Private bearer calendar subscription
     * @param {CalendarFeedScope} scope 
     * @param {string} token 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    publicCalendarFeedRaw(requestParameters: PublicCalendarFeedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     * Private bearer calendar subscription
     */
    publicCalendarFeed(requestParameters: PublicCalendarFeedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Creates request options for recordEventAttendance without sending the request
     * @param {'training' | 'webinar'} type 
     * @param {string} id 
     * @param {string} userID 
     * @param {RecordEventAttendanceRequest} recordEventAttendanceRequest 
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    recordEventAttendanceRequestOpts(requestParameters: RecordEventAttendanceOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Hospital learners read their own records; hospital administrators read only their hospital. Vendor and human platform roles have no access. Registration does not prove attendance or award credit.
     * @summary Record a hospital learner attendance outcome with evidence
     * @param {'training' | 'webinar'} type 
     * @param {string} id 
     * @param {string} userID 
     * @param {RecordEventAttendanceRequest} recordEventAttendanceRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    recordEventAttendanceRaw(requestParameters: RecordEventAttendanceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingSessionRegistration>>;

    /**
     * Hospital learners read their own records; hospital administrators read only their hospital. Vendor and human platform roles have no access. Registration does not prove attendance or award credit.
     * Record a hospital learner attendance outcome with evidence
     */
    recordEventAttendance(requestParameters: RecordEventAttendanceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingSessionRegistration>;

    /**
     * Creates request options for registerForEvent without sending the request
     * @param {'training' | 'webinar'} type 
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    registerForEventRequestOpts(requestParameters: RegisterForEventRequest): Promise<runtime.RequestOpts>;

    /**
     * Hospital learners read their own records; hospital administrators read only their hospital. Vendor and human platform roles have no access. Registration does not prove attendance or award credit.
     * @summary Register yourself for an education event
     * @param {'training' | 'webinar'} type 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    registerForEventRaw(requestParameters: RegisterForEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingSessionRegistration>>;

    /**
     * Hospital learners read their own records; hospital administrators read only their hospital. Vendor and human platform roles have no access. Registration does not prove attendance or award credit.
     * Register yourself for an education event
     */
    registerForEvent(requestParameters: RegisterForEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingSessionRegistration>;

    /**
     * Creates request options for revokeCalendarFeed without sending the request
     * @param {RotateCalendarFeedRequest} rotateCalendarFeedRequest 
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    revokeCalendarFeedRequestOpts(requestParameters: RevokeCalendarFeedRequest): Promise<runtime.RequestOpts>;

    /**
     * Immediately rejects the old URL. Listing subscriptions preserves the stopped state. Rotate explicitly to create a replacement URL.
     * @summary Stop a private calendar subscription
     * @param {RotateCalendarFeedRequest} rotateCalendarFeedRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    revokeCalendarFeedRaw(requestParameters: RevokeCalendarFeedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Immediately rejects the old URL. Listing subscriptions preserves the stopped state. Rotate explicitly to create a replacement URL.
     * Stop a private calendar subscription
     */
    revokeCalendarFeed(requestParameters: RevokeCalendarFeedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for rotateCalendarFeed without sending the request
     * @param {RotateCalendarFeedRequest} rotateCalendarFeedRequest 
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    rotateCalendarFeedRequestOpts(requestParameters: RotateCalendarFeedOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Rotate calendar feed token
     * @param {RotateCalendarFeedRequest} rotateCalendarFeedRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    rotateCalendarFeedRaw(requestParameters: RotateCalendarFeedOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CalendarFeed>>;

    /**
     * Rotate calendar feed token
     */
    rotateCalendarFeed(requestParameters: RotateCalendarFeedOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CalendarFeed>;

}

/**
 * 
 */
export class EventsApi extends runtime.BaseAPI implements EventsApiInterface {

    /**
     * Creates request options for cancelEventRegistration without sending the request
     */
    async cancelEventRegistrationRequestOpts(requestParameters: CancelEventRegistrationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling cancelEventRegistration().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling cancelEventRegistration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/events/{type}/{id}/registrations/me`;
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Hospital learners read their own records; hospital administrators read only their hospital. Vendor and human platform roles have no access. Registration does not prove attendance or award credit.
     * Cancel your pending event registration
     */
    async cancelEventRegistrationRaw(requestParameters: CancelEventRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.cancelEventRegistrationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Hospital learners read their own records; hospital administrators read only their hospital. Vendor and human platform roles have no access. Registration does not prove attendance or award credit.
     * Cancel your pending event registration
     */
    async cancelEventRegistration(requestParameters: CancelEventRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.cancelEventRegistrationRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for exportCalendarEvent without sending the request
     */
    async exportCalendarEventRequestOpts(requestParameters: ExportCalendarEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling exportCalendarEvent().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling exportCalendarEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/events/{type}/{id}/calendar.ics`;
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Private iCalendar download with the same stable UID, update sequence and cancellation status as subscriptions. Exporting is not registration or attendance.
     * Export one authorized education event
     */
    async exportCalendarEventRaw(requestParameters: ExportCalendarEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.exportCalendarEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Private iCalendar download with the same stable UID, update sequence and cancellation status as subscriptions. Exporting is not registration or attendance.
     * Export one authorized education event
     */
    async exportCalendarEvent(requestParameters: ExportCalendarEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.exportCalendarEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCalendarEvents without sending the request
     */
    async listCalendarEventsRequestOpts(requestParameters: ListCalendarEventsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString();
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString();
        }

        if (requestParameters['scope'] != null) {
            queryParameters['scope'] = requestParameters['scope'];
        }

        if (requestParameters['types'] != null) {
            queryParameters['types'] = requestParameters['types'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/events/calendar`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Unified calendar events
     */
    async listCalendarEventsRaw(requestParameters: ListCalendarEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CalendarItem>>> {
        const requestOptions = await this.listCalendarEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CalendarItemFromJSON));
    }

    /**
     * Unified calendar events
     */
    async listCalendarEvents(requestParameters: ListCalendarEventsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CalendarItem>> {
        const response = await this.listCalendarEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCalendarFeeds without sending the request
     */
    async listCalendarFeedsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/calendar/feeds`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List calendar feeds
     */
    async listCalendarFeedsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CalendarFeed>>> {
        const requestOptions = await this.listCalendarFeedsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CalendarFeedFromJSON));
    }

    /**
     * List calendar feeds
     */
    async listCalendarFeeds(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CalendarFeed>> {
        const response = await this.listCalendarFeedsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listEventRegistrations without sending the request
     */
    async listEventRegistrationsRequestOpts(requestParameters: ListEventRegistrationsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling listEventRegistrations().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listEventRegistrations().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/events/{type}/{id}/registrations`;
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Hospital learners read their own records; hospital administrators read only their hospital. Vendor and human platform roles have no access. Registration does not prove attendance or award credit.
     * Read private hospital event registrations
     */
    async listEventRegistrationsRaw(requestParameters: ListEventRegistrationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TrainingSessionRegistration>>> {
        const requestOptions = await this.listEventRegistrationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TrainingSessionRegistrationFromJSON));
    }

    /**
     * Hospital learners read their own records; hospital administrators read only their hospital. Vendor and human platform roles have no access. Registration does not prove attendance or award credit.
     * Read private hospital event registrations
     */
    async listEventRegistrations(requestParameters: ListEventRegistrationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TrainingSessionRegistration>> {
        const response = await this.listEventRegistrationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicCalendarFeed without sending the request
     */
    async publicCalendarFeedRequestOpts(requestParameters: PublicCalendarFeedRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['scope'] == null) {
            throw new runtime.RequiredError(
                'scope',
                'Required parameter "scope" was null or undefined when calling publicCalendarFeed().'
            );
        }

        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling publicCalendarFeed().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/calendar/feeds/{scope}/{token}.ics`;
        urlPath = urlPath.replace(`{${"scope"}}`, encodeURIComponent(String(requestParameters['scope'])));
        urlPath = urlPath.replace(`{${"token"}}`, encodeURIComponent(String(requestParameters['token'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Private bearer calendar subscription
     */
    async publicCalendarFeedRaw(requestParameters: PublicCalendarFeedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.publicCalendarFeedRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Private bearer calendar subscription
     */
    async publicCalendarFeed(requestParameters: PublicCalendarFeedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.publicCalendarFeedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recordEventAttendance without sending the request
     */
    async recordEventAttendanceRequestOpts(requestParameters: RecordEventAttendanceOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling recordEventAttendance().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling recordEventAttendance().'
            );
        }

        if (requestParameters['userID'] == null) {
            throw new runtime.RequiredError(
                'userID',
                'Required parameter "userID" was null or undefined when calling recordEventAttendance().'
            );
        }

        if (requestParameters['recordEventAttendanceRequest'] == null) {
            throw new runtime.RequiredError(
                'recordEventAttendanceRequest',
                'Required parameter "recordEventAttendanceRequest" was null or undefined when calling recordEventAttendance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/events/{type}/{id}/registrations/{userID}`;
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"userID"}}`, encodeURIComponent(String(requestParameters['userID'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: RecordEventAttendanceRequestToJSON(requestParameters['recordEventAttendanceRequest']),
        };
    }

    /**
     * Hospital learners read their own records; hospital administrators read only their hospital. Vendor and human platform roles have no access. Registration does not prove attendance or award credit.
     * Record a hospital learner attendance outcome with evidence
     */
    async recordEventAttendanceRaw(requestParameters: RecordEventAttendanceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingSessionRegistration>> {
        const requestOptions = await this.recordEventAttendanceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingSessionRegistrationFromJSON(jsonValue));
    }

    /**
     * Hospital learners read their own records; hospital administrators read only their hospital. Vendor and human platform roles have no access. Registration does not prove attendance or award credit.
     * Record a hospital learner attendance outcome with evidence
     */
    async recordEventAttendance(requestParameters: RecordEventAttendanceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingSessionRegistration> {
        const response = await this.recordEventAttendanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for registerForEvent without sending the request
     */
    async registerForEventRequestOpts(requestParameters: RegisterForEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling registerForEvent().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling registerForEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/events/{type}/{id}/registrations/me`;
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Hospital learners read their own records; hospital administrators read only their hospital. Vendor and human platform roles have no access. Registration does not prove attendance or award credit.
     * Register yourself for an education event
     */
    async registerForEventRaw(requestParameters: RegisterForEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingSessionRegistration>> {
        const requestOptions = await this.registerForEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingSessionRegistrationFromJSON(jsonValue));
    }

    /**
     * Hospital learners read their own records; hospital administrators read only their hospital. Vendor and human platform roles have no access. Registration does not prove attendance or award credit.
     * Register yourself for an education event
     */
    async registerForEvent(requestParameters: RegisterForEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingSessionRegistration> {
        const response = await this.registerForEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for revokeCalendarFeed without sending the request
     */
    async revokeCalendarFeedRequestOpts(requestParameters: RevokeCalendarFeedRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['rotateCalendarFeedRequest'] == null) {
            throw new runtime.RequiredError(
                'rotateCalendarFeedRequest',
                'Required parameter "rotateCalendarFeedRequest" was null or undefined when calling revokeCalendarFeed().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/calendar/feeds/revoke`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RotateCalendarFeedRequestToJSON(requestParameters['rotateCalendarFeedRequest']),
        };
    }

    /**
     * Immediately rejects the old URL. Listing subscriptions preserves the stopped state. Rotate explicitly to create a replacement URL.
     * Stop a private calendar subscription
     */
    async revokeCalendarFeedRaw(requestParameters: RevokeCalendarFeedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.revokeCalendarFeedRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Immediately rejects the old URL. Listing subscriptions preserves the stopped state. Rotate explicitly to create a replacement URL.
     * Stop a private calendar subscription
     */
    async revokeCalendarFeed(requestParameters: RevokeCalendarFeedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.revokeCalendarFeedRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for rotateCalendarFeed without sending the request
     */
    async rotateCalendarFeedRequestOpts(requestParameters: RotateCalendarFeedOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['rotateCalendarFeedRequest'] == null) {
            throw new runtime.RequiredError(
                'rotateCalendarFeedRequest',
                'Required parameter "rotateCalendarFeedRequest" was null or undefined when calling rotateCalendarFeed().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/calendar/feeds/rotate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RotateCalendarFeedRequestToJSON(requestParameters['rotateCalendarFeedRequest']),
        };
    }

    /**
     * Rotate calendar feed token
     */
    async rotateCalendarFeedRaw(requestParameters: RotateCalendarFeedOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CalendarFeed>> {
        const requestOptions = await this.rotateCalendarFeedRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CalendarFeedFromJSON(jsonValue));
    }

    /**
     * Rotate calendar feed token
     */
    async rotateCalendarFeed(requestParameters: RotateCalendarFeedOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CalendarFeed> {
        const response = await this.rotateCalendarFeedRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CancelEventRegistrationTypeEnum = {
    Training: 'training',
    Webinar: 'webinar'
} as const;
export type CancelEventRegistrationTypeEnum = typeof CancelEventRegistrationTypeEnum[keyof typeof CancelEventRegistrationTypeEnum];
/**
 * @export
 */
export const ExportCalendarEventTypeEnum = {
    Webinar: 'webinar',
    Training: 'training'
} as const;
export type ExportCalendarEventTypeEnum = typeof ExportCalendarEventTypeEnum[keyof typeof ExportCalendarEventTypeEnum];
/**
 * @export
 */
export const ListEventRegistrationsTypeEnum = {
    Training: 'training',
    Webinar: 'webinar'
} as const;
export type ListEventRegistrationsTypeEnum = typeof ListEventRegistrationsTypeEnum[keyof typeof ListEventRegistrationsTypeEnum];
/**
 * @export
 */
export const RecordEventAttendanceOperationTypeEnum = {
    Training: 'training',
    Webinar: 'webinar'
} as const;
export type RecordEventAttendanceOperationTypeEnum = typeof RecordEventAttendanceOperationTypeEnum[keyof typeof RecordEventAttendanceOperationTypeEnum];
/**
 * @export
 */
export const RegisterForEventTypeEnum = {
    Training: 'training',
    Webinar: 'webinar'
} as const;
export type RegisterForEventTypeEnum = typeof RegisterForEventTypeEnum[keyof typeof RegisterForEventTypeEnum];
