/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FeatureSettings,
} from '../models/index';
import {
    FeatureSettingsFromJSON,
    FeatureSettingsToJSON,
} from '../models/index';

/**
 * FeaturesApi - interface
 * 
 * @export
 * @interface FeaturesApiInterface
 */
export interface FeaturesApiInterface {
    /**
     * Creates request options for getFeatures without sending the request
     * @throws {RequiredError}
     * @memberof FeaturesApiInterface
     */
    getFeaturesRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Public effective integration controls. Contains no provider configuration. Disabled operations return 503 after applicable access checks; authorization and saved records are unchanged.
     * @summary Read integration availability
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeaturesApiInterface
     */
    getFeaturesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FeatureSettings>>;

    /**
     * Public effective integration controls. Contains no provider configuration. Disabled operations return 503 after applicable access checks; authorization and saved records are unchanged.
     * Read integration availability
     */
    getFeatures(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FeatureSettings>;

}

/**
 * 
 */
export class FeaturesApi extends runtime.BaseAPI implements FeaturesApiInterface {

    /**
     * Creates request options for getFeatures without sending the request
     */
    async getFeaturesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/features`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Public effective integration controls. Contains no provider configuration. Disabled operations return 503 after applicable access checks; authorization and saved records are unchanged.
     * Read integration availability
     */
    async getFeaturesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FeatureSettings>> {
        const requestOptions = await this.getFeaturesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FeatureSettingsFromJSON(jsonValue));
    }

    /**
     * Public effective integration controls. Contains no provider configuration. Disabled operations return 503 after applicable access checks; authorization and saved records are unchanged.
     * Read integration availability
     */
    async getFeatures(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FeatureSettings> {
        const response = await this.getFeaturesRaw(initOverrides);
        return await response.value();
    }

}
