/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateVideoRequest,
    CreateVideoRequestFromJSON,
    CreateVideoRequestToJSON,
} from '../models/CreateVideoRequest';
import {
    type CreateVideoResponse,
    CreateVideoResponseFromJSON,
    CreateVideoResponseToJSON,
} from '../models/CreateVideoResponse';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type VideoAsset,
    VideoAssetFromJSON,
    VideoAssetToJSON,
} from '../models/VideoAsset';
import {
    type VideoPlayback,
    VideoPlaybackFromJSON,
    VideoPlaybackToJSON,
} from '../models/VideoPlayback';

export interface CompleteVideoUploadRequest {
    id: string;
}

export interface CreateVideoOperationRequest {
    createVideoRequest: CreateVideoRequest;
}

export interface GetVideoRequest {
    id: string;
}

export interface PlayVideoRequest {
    id: string;
}

/**
 * VideosApi - interface
 * 
 * @export
 * @interface VideosApiInterface
 */
export interface VideosApiInterface {
    /**
     * Creates request options for completeVideoUpload without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof VideosApiInterface
     */
    completeVideoUploadRequestOpts(requestParameters: CompleteVideoUploadRequest): Promise<runtime.RequestOpts>;

    /**
     * Marks the raw source upload complete and moves the video into processing state. Encode job execution is configured separately.
     * @summary Mark a video upload complete
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApiInterface
     */
    completeVideoUploadRaw(requestParameters: CompleteVideoUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoAsset>>;

    /**
     * Marks the raw source upload complete and moves the video into processing state. Encode job execution is configured separately.
     * Mark a video upload complete
     */
    completeVideoUpload(requestParameters: CompleteVideoUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoAsset>;

    /**
     * Creates request options for createVideo without sending the request
     * @param {CreateVideoRequest} createVideoRequest 
     * @throws {RequiredError}
     * @memberof VideosApiInterface
     */
    createVideoRequestOpts(requestParameters: CreateVideoOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates zero-PHI video metadata and server-generated opaque storage keys. Upload URLs are omitted until storage signing is configured.
     * @summary Create a video metadata record
     * @param {CreateVideoRequest} createVideoRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApiInterface
     */
    createVideoRaw(requestParameters: CreateVideoOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateVideoResponse>>;

    /**
     * Creates zero-PHI video metadata and server-generated opaque storage keys. Upload URLs are omitted until storage signing is configured.
     * Create a video metadata record
     */
    createVideo(requestParameters: CreateVideoOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateVideoResponse>;

    /**
     * Creates request options for getVideo without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof VideosApiInterface
     */
    getVideoRequestOpts(requestParameters: GetVideoRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get a video metadata record
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApiInterface
     */
    getVideoRaw(requestParameters: GetVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoAsset>>;

    /**
     * Get a video metadata record
     */
    getVideo(requestParameters: GetVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoAsset>;

    /**
     * Creates request options for playVideo without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof VideosApiInterface
     */
    playVideoRequestOpts(requestParameters: PlayVideoRequest): Promise<runtime.RequestOpts>;

    /**
     * Foundation stub. Returns not implemented until CloudFront signed cookie playback is configured.
     * @summary Get video playback information
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApiInterface
     */
    playVideoRaw(requestParameters: PlayVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoPlayback>>;

    /**
     * Foundation stub. Returns not implemented until CloudFront signed cookie playback is configured.
     * Get video playback information
     */
    playVideo(requestParameters: PlayVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoPlayback>;

}

/**
 * 
 */
export class VideosApi extends runtime.BaseAPI implements VideosApiInterface {

    /**
     * Creates request options for completeVideoUpload without sending the request
     */
    async completeVideoUploadRequestOpts(requestParameters: CompleteVideoUploadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling completeVideoUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/videos/{id}/upload-complete`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Marks the raw source upload complete and moves the video into processing state. Encode job execution is configured separately.
     * Mark a video upload complete
     */
    async completeVideoUploadRaw(requestParameters: CompleteVideoUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoAsset>> {
        const requestOptions = await this.completeVideoUploadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoAssetFromJSON(jsonValue));
    }

    /**
     * Marks the raw source upload complete and moves the video into processing state. Encode job execution is configured separately.
     * Mark a video upload complete
     */
    async completeVideoUpload(requestParameters: CompleteVideoUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoAsset> {
        const response = await this.completeVideoUploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createVideo without sending the request
     */
    async createVideoRequestOpts(requestParameters: CreateVideoOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createVideoRequest'] == null) {
            throw new runtime.RequiredError(
                'createVideoRequest',
                'Required parameter "createVideoRequest" was null or undefined when calling createVideo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/videos/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateVideoRequestToJSON(requestParameters['createVideoRequest']),
        };
    }

    /**
     * Creates zero-PHI video metadata and server-generated opaque storage keys. Upload URLs are omitted until storage signing is configured.
     * Create a video metadata record
     */
    async createVideoRaw(requestParameters: CreateVideoOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateVideoResponse>> {
        const requestOptions = await this.createVideoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateVideoResponseFromJSON(jsonValue));
    }

    /**
     * Creates zero-PHI video metadata and server-generated opaque storage keys. Upload URLs are omitted until storage signing is configured.
     * Create a video metadata record
     */
    async createVideo(requestParameters: CreateVideoOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateVideoResponse> {
        const response = await this.createVideoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getVideo without sending the request
     */
    async getVideoRequestOpts(requestParameters: GetVideoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getVideo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/videos/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a video metadata record
     */
    async getVideoRaw(requestParameters: GetVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoAsset>> {
        const requestOptions = await this.getVideoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoAssetFromJSON(jsonValue));
    }

    /**
     * Get a video metadata record
     */
    async getVideo(requestParameters: GetVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoAsset> {
        const response = await this.getVideoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for playVideo without sending the request
     */
    async playVideoRequestOpts(requestParameters: PlayVideoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling playVideo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/videos/{id}/play`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Foundation stub. Returns not implemented until CloudFront signed cookie playback is configured.
     * Get video playback information
     */
    async playVideoRaw(requestParameters: PlayVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoPlayback>> {
        const requestOptions = await this.playVideoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoPlaybackFromJSON(jsonValue));
    }

    /**
     * Foundation stub. Returns not implemented until CloudFront signed cookie playback is configured.
     * Get video playback information
     */
    async playVideo(requestParameters: PlayVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoPlayback> {
        const response = await this.playVideoRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
