/* tslint:disable */
/* eslint-disable */
/**
 * Bridge Med API
 * Bridge Med backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AudienceHospital,
  CreateWebinarQnARequest,
  CreateWebinarRequest,
  ErrorResponse,
  EventAvailability,
  EventPublication,
  JoinWebinarRequest,
  UpdateWebinarQnARequest,
  UpdateWebinarRequest,
  Webinar,
  WebinarJoinResult,
  WebinarQnAItem,
} from '../models/index';
import {
    AudienceHospitalFromJSON,
    AudienceHospitalToJSON,
    CreateWebinarQnARequestFromJSON,
    CreateWebinarQnARequestToJSON,
    CreateWebinarRequestFromJSON,
    CreateWebinarRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    EventAvailabilityFromJSON,
    EventAvailabilityToJSON,
    EventPublicationFromJSON,
    EventPublicationToJSON,
    JoinWebinarRequestFromJSON,
    JoinWebinarRequestToJSON,
    UpdateWebinarQnARequestFromJSON,
    UpdateWebinarQnARequestToJSON,
    UpdateWebinarRequestFromJSON,
    UpdateWebinarRequestToJSON,
    WebinarFromJSON,
    WebinarToJSON,
    WebinarJoinResultFromJSON,
    WebinarJoinResultToJSON,
    WebinarQnAItemFromJSON,
    WebinarQnAItemToJSON,
} from '../models/index';

export interface CancelWebinarRequest {
    id: string;
}

export interface CreateWebinarOperationRequest {
    createWebinarRequest: CreateWebinarRequest;
}

export interface CreateWebinarQnAOperationRequest {
    id: string;
    createWebinarQnARequest: CreateWebinarQnARequest;
}

export interface EndWebinarRequest {
    id: string;
}

export interface GetHospitalWebinarAvailabilityRequest {
    id: string;
}

export interface GetWebinarRequest {
    id: string;
}

export interface GetWebinarAudienceRequest {
    id: string;
}

export interface JoinWebinarOperationRequest {
    id: string;
    joinWebinarRequest?: JoinWebinarRequest;
}

export interface ListWebinarQnARequest {
    id: string;
}

export interface ListWebinarsRequest {
    organizationId?: string;
    hostUserId?: string;
    statuses?: string;
    start?: Date;
    end?: Date;
}

export interface PublishWebinarAudienceRequest {
    id: string;
    organizationID: string;
    eventPublication: EventPublication;
}

export interface SetHospitalWebinarAvailabilityRequest {
    id: string;
    eventAvailability: EventAvailability;
}

export interface SignalWebinarRequest {
    id: string;
    participantToken: string;
}

export interface StartWebinarRequest {
    id: string;
}

export interface UpdateWebinarOperationRequest {
    id: string;
    updateWebinarRequest: UpdateWebinarRequest;
}

export interface UpdateWebinarQnAOperationRequest {
    id: string;
    itemID: string;
    updateWebinarQnARequest: UpdateWebinarQnARequest;
}

/**
 * WebinarsApi - interface
 * 
 * @export
 * @interface WebinarsApiInterface
 */
export interface WebinarsApiInterface {
    /**
     * Creates request options for cancelWebinar without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    cancelWebinarRequestOpts(requestParameters: CancelWebinarRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Cancel webinar
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    cancelWebinarRaw(requestParameters: CancelWebinarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Webinar>>;

    /**
     * Cancel webinar
     */
    cancelWebinar(requestParameters: CancelWebinarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Webinar>;

    /**
     * Creates request options for createWebinar without sending the request
     * @param {CreateWebinarRequest} createWebinarRequest 
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    createWebinarRequestOpts(requestParameters: CreateWebinarOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create webinar
     * @param {CreateWebinarRequest} createWebinarRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    createWebinarRaw(requestParameters: CreateWebinarOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Webinar>>;

    /**
     * Create webinar
     */
    createWebinar(requestParameters: CreateWebinarOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Webinar>;

    /**
     * Creates request options for createWebinarQnA without sending the request
     * @param {string} id 
     * @param {CreateWebinarQnARequest} createWebinarQnARequest 
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    createWebinarQnARequestOpts(requestParameters: CreateWebinarQnAOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create webinar Q&A item
     * @param {string} id 
     * @param {CreateWebinarQnARequest} createWebinarQnARequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    createWebinarQnARaw(requestParameters: CreateWebinarQnAOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebinarQnAItem>>;

    /**
     * Create webinar Q&A item
     */
    createWebinarQnA(requestParameters: CreateWebinarQnAOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebinarQnAItem>;

    /**
     * Creates request options for endWebinar without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    endWebinarRequestOpts(requestParameters: EndWebinarRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary End webinar
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    endWebinarRaw(requestParameters: EndWebinarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Webinar>>;

    /**
     * End webinar
     */
    endWebinar(requestParameters: EndWebinarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Webinar>;

    /**
     * Creates request options for getHospitalWebinarAvailability without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    getHospitalWebinarAvailabilityRequestOpts(requestParameters: GetHospitalWebinarAvailabilityRequest): Promise<runtime.RequestOpts>;

    /**
     * Vendor hosts and authorized company managers choose partner hospitals explicitly. Hospital administrators control access for their own staff. Withdrawing access preserves private participation history and sends cancellation updates to calendar subscriptions.
     * @summary Read your hospital availability for an event
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    getHospitalWebinarAvailabilityRaw(requestParameters: GetHospitalWebinarAvailabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventAvailability>>;

    /**
     * Vendor hosts and authorized company managers choose partner hospitals explicitly. Hospital administrators control access for their own staff. Withdrawing access preserves private participation history and sends cancellation updates to calendar subscriptions.
     * Read your hospital availability for an event
     */
    getHospitalWebinarAvailability(requestParameters: GetHospitalWebinarAvailabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventAvailability>;

    /**
     * Creates request options for getWebinar without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    getWebinarRequestOpts(requestParameters: GetWebinarRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get webinar
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    getWebinarRaw(requestParameters: GetWebinarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Webinar>>;

    /**
     * Get webinar
     */
    getWebinar(requestParameters: GetWebinarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Webinar>;

    /**
     * Creates request options for getWebinarAudience without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    getWebinarAudienceRequestOpts(requestParameters: GetWebinarAudienceRequest): Promise<runtime.RequestOpts>;

    /**
     * Vendor hosts and authorized company managers choose partner hospitals explicitly. Hospital administrators control access for their own staff. Withdrawing access preserves private participation history and sends cancellation updates to calendar subscriptions.
     * @summary List eligible hospitals and current event publication
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    getWebinarAudienceRaw(requestParameters: GetWebinarAudienceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AudienceHospital>>>;

    /**
     * Vendor hosts and authorized company managers choose partner hospitals explicitly. Hospital administrators control access for their own staff. Withdrawing access preserves private participation history and sends cancellation updates to calendar subscriptions.
     * List eligible hospitals and current event publication
     */
    getWebinarAudience(requestParameters: GetWebinarAudienceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AudienceHospital>>;

    /**
     * Creates request options for joinWebinar without sending the request
     * @param {string} id 
     * @param {JoinWebinarRequest} [joinWebinarRequest] 
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    joinWebinarRequestOpts(requestParameters: JoinWebinarOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Join webinar
     * @param {string} id 
     * @param {JoinWebinarRequest} [joinWebinarRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    joinWebinarRaw(requestParameters: JoinWebinarOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebinarJoinResult>>;

    /**
     * Join webinar
     */
    joinWebinar(requestParameters: JoinWebinarOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebinarJoinResult>;

    /**
     * Creates request options for listWebinarQnA without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    listWebinarQnARequestOpts(requestParameters: ListWebinarQnARequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List webinar Q&A items
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    listWebinarQnARaw(requestParameters: ListWebinarQnARequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WebinarQnAItem>>>;

    /**
     * List webinar Q&A items
     */
    listWebinarQnA(requestParameters: ListWebinarQnARequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WebinarQnAItem>>;

    /**
     * Creates request options for listWebinars without sending the request
     * @param {string} [organizationId] 
     * @param {string} [hostUserId] 
     * @param {string} [statuses] Comma-separated webinar statuses
     * @param {Date} [start] 
     * @param {Date} [end] 
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    listWebinarsRequestOpts(requestParameters: ListWebinarsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List webinars
     * @param {string} [organizationId] 
     * @param {string} [hostUserId] 
     * @param {string} [statuses] Comma-separated webinar statuses
     * @param {Date} [start] 
     * @param {Date} [end] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    listWebinarsRaw(requestParameters: ListWebinarsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Webinar>>>;

    /**
     * List webinars
     */
    listWebinars(requestParameters: ListWebinarsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Webinar>>;

    /**
     * Creates request options for publishWebinarAudience without sending the request
     * @param {string} id 
     * @param {string} organizationID 
     * @param {EventPublication} eventPublication 
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    publishWebinarAudienceRequestOpts(requestParameters: PublishWebinarAudienceRequest): Promise<runtime.RequestOpts>;

    /**
     * Vendor hosts and authorized company managers choose partner hospitals explicitly. Hospital administrators control access for their own staff. Withdrawing access preserves private participation history and sends cancellation updates to calendar subscriptions.
     * @summary Publish or withdraw a vendor event for one hospital
     * @param {string} id 
     * @param {string} organizationID 
     * @param {EventPublication} eventPublication 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    publishWebinarAudienceRaw(requestParameters: PublishWebinarAudienceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Vendor hosts and authorized company managers choose partner hospitals explicitly. Hospital administrators control access for their own staff. Withdrawing access preserves private participation history and sends cancellation updates to calendar subscriptions.
     * Publish or withdraw a vendor event for one hospital
     */
    publishWebinarAudience(requestParameters: PublishWebinarAudienceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for setHospitalWebinarAvailability without sending the request
     * @param {string} id 
     * @param {EventAvailability} eventAvailability 
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    setHospitalWebinarAvailabilityRequestOpts(requestParameters: SetHospitalWebinarAvailabilityRequest): Promise<runtime.RequestOpts>;

    /**
     * Vendor hosts and authorized company managers choose partner hospitals explicitly. Hospital administrators control access for their own staff. Withdrawing access preserves private participation history and sends cancellation updates to calendar subscriptions.
     * @summary Enable or disable event access for your hospital
     * @param {string} id 
     * @param {EventAvailability} eventAvailability 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    setHospitalWebinarAvailabilityRaw(requestParameters: SetHospitalWebinarAvailabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Vendor hosts and authorized company managers choose partner hospitals explicitly. Hospital administrators control access for their own staff. Withdrawing access preserves private participation history and sends cancellation updates to calendar subscriptions.
     * Enable or disable event access for your hospital
     */
    setHospitalWebinarAvailability(requestParameters: SetHospitalWebinarAvailabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for signalWebinar without sending the request
     * @param {string} id 
     * @param {string} participantToken 
     * @deprecated
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    signalWebinarRequestOpts(requestParameters: SignalWebinarRequest): Promise<runtime.RequestOpts>;

    /**
     * Requires a current authenticated browser session and a participant token for that same user and room.
     * @summary WebRTC signaling websocket endpoint
     * @param {string} id 
     * @param {string} participantToken 
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    signalWebinarRaw(requestParameters: SignalWebinarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Requires a current authenticated browser session and a participant token for that same user and room.
     * WebRTC signaling websocket endpoint
     * @deprecated
     */
    signalWebinar(requestParameters: SignalWebinarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for startWebinar without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    startWebinarRequestOpts(requestParameters: StartWebinarRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Start webinar
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    startWebinarRaw(requestParameters: StartWebinarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Webinar>>;

    /**
     * Start webinar
     */
    startWebinar(requestParameters: StartWebinarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Webinar>;

    /**
     * Creates request options for updateWebinar without sending the request
     * @param {string} id 
     * @param {UpdateWebinarRequest} updateWebinarRequest 
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    updateWebinarRequestOpts(requestParameters: UpdateWebinarOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Update webinar
     * @param {string} id 
     * @param {UpdateWebinarRequest} updateWebinarRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    updateWebinarRaw(requestParameters: UpdateWebinarOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Webinar>>;

    /**
     * Update webinar
     */
    updateWebinar(requestParameters: UpdateWebinarOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Webinar>;

    /**
     * Creates request options for updateWebinarQnA without sending the request
     * @param {string} id 
     * @param {string} itemID 
     * @param {UpdateWebinarQnARequest} updateWebinarQnARequest 
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    updateWebinarQnARequestOpts(requestParameters: UpdateWebinarQnAOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Moderate webinar Q&A item
     * @param {string} id 
     * @param {string} itemID 
     * @param {UpdateWebinarQnARequest} updateWebinarQnARequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebinarsApiInterface
     */
    updateWebinarQnARaw(requestParameters: UpdateWebinarQnAOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebinarQnAItem>>;

    /**
     * Moderate webinar Q&A item
     */
    updateWebinarQnA(requestParameters: UpdateWebinarQnAOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebinarQnAItem>;

}

/**
 * 
 */
export class WebinarsApi extends runtime.BaseAPI implements WebinarsApiInterface {

    /**
     * Creates request options for cancelWebinar without sending the request
     */
    async cancelWebinarRequestOpts(requestParameters: CancelWebinarRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling cancelWebinar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webinars/{id}/cancel`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cancel webinar
     */
    async cancelWebinarRaw(requestParameters: CancelWebinarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Webinar>> {
        const requestOptions = await this.cancelWebinarRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebinarFromJSON(jsonValue));
    }

    /**
     * Cancel webinar
     */
    async cancelWebinar(requestParameters: CancelWebinarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Webinar> {
        const response = await this.cancelWebinarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createWebinar without sending the request
     */
    async createWebinarRequestOpts(requestParameters: CreateWebinarOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createWebinarRequest'] == null) {
            throw new runtime.RequiredError(
                'createWebinarRequest',
                'Required parameter "createWebinarRequest" was null or undefined when calling createWebinar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webinars/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWebinarRequestToJSON(requestParameters['createWebinarRequest']),
        };
    }

    /**
     * Create webinar
     */
    async createWebinarRaw(requestParameters: CreateWebinarOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Webinar>> {
        const requestOptions = await this.createWebinarRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebinarFromJSON(jsonValue));
    }

    /**
     * Create webinar
     */
    async createWebinar(requestParameters: CreateWebinarOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Webinar> {
        const response = await this.createWebinarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createWebinarQnA without sending the request
     */
    async createWebinarQnARequestOpts(requestParameters: CreateWebinarQnAOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createWebinarQnA().'
            );
        }

        if (requestParameters['createWebinarQnARequest'] == null) {
            throw new runtime.RequiredError(
                'createWebinarQnARequest',
                'Required parameter "createWebinarQnARequest" was null or undefined when calling createWebinarQnA().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webinars/{id}/qna`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWebinarQnARequestToJSON(requestParameters['createWebinarQnARequest']),
        };
    }

    /**
     * Create webinar Q&A item
     */
    async createWebinarQnARaw(requestParameters: CreateWebinarQnAOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebinarQnAItem>> {
        const requestOptions = await this.createWebinarQnARequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebinarQnAItemFromJSON(jsonValue));
    }

    /**
     * Create webinar Q&A item
     */
    async createWebinarQnA(requestParameters: CreateWebinarQnAOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebinarQnAItem> {
        const response = await this.createWebinarQnARaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for endWebinar without sending the request
     */
    async endWebinarRequestOpts(requestParameters: EndWebinarRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling endWebinar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webinars/{id}/end`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * End webinar
     */
    async endWebinarRaw(requestParameters: EndWebinarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Webinar>> {
        const requestOptions = await this.endWebinarRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebinarFromJSON(jsonValue));
    }

    /**
     * End webinar
     */
    async endWebinar(requestParameters: EndWebinarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Webinar> {
        const response = await this.endWebinarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getHospitalWebinarAvailability without sending the request
     */
    async getHospitalWebinarAvailabilityRequestOpts(requestParameters: GetHospitalWebinarAvailabilityRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getHospitalWebinarAvailability().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webinars/{id}/availability`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Vendor hosts and authorized company managers choose partner hospitals explicitly. Hospital administrators control access for their own staff. Withdrawing access preserves private participation history and sends cancellation updates to calendar subscriptions.
     * Read your hospital availability for an event
     */
    async getHospitalWebinarAvailabilityRaw(requestParameters: GetHospitalWebinarAvailabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventAvailability>> {
        const requestOptions = await this.getHospitalWebinarAvailabilityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventAvailabilityFromJSON(jsonValue));
    }

    /**
     * Vendor hosts and authorized company managers choose partner hospitals explicitly. Hospital administrators control access for their own staff. Withdrawing access preserves private participation history and sends cancellation updates to calendar subscriptions.
     * Read your hospital availability for an event
     */
    async getHospitalWebinarAvailability(requestParameters: GetHospitalWebinarAvailabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventAvailability> {
        const response = await this.getHospitalWebinarAvailabilityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWebinar without sending the request
     */
    async getWebinarRequestOpts(requestParameters: GetWebinarRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getWebinar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webinars/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get webinar
     */
    async getWebinarRaw(requestParameters: GetWebinarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Webinar>> {
        const requestOptions = await this.getWebinarRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebinarFromJSON(jsonValue));
    }

    /**
     * Get webinar
     */
    async getWebinar(requestParameters: GetWebinarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Webinar> {
        const response = await this.getWebinarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWebinarAudience without sending the request
     */
    async getWebinarAudienceRequestOpts(requestParameters: GetWebinarAudienceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getWebinarAudience().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webinars/{id}/audience`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Vendor hosts and authorized company managers choose partner hospitals explicitly. Hospital administrators control access for their own staff. Withdrawing access preserves private participation history and sends cancellation updates to calendar subscriptions.
     * List eligible hospitals and current event publication
     */
    async getWebinarAudienceRaw(requestParameters: GetWebinarAudienceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AudienceHospital>>> {
        const requestOptions = await this.getWebinarAudienceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AudienceHospitalFromJSON));
    }

    /**
     * Vendor hosts and authorized company managers choose partner hospitals explicitly. Hospital administrators control access for their own staff. Withdrawing access preserves private participation history and sends cancellation updates to calendar subscriptions.
     * List eligible hospitals and current event publication
     */
    async getWebinarAudience(requestParameters: GetWebinarAudienceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AudienceHospital>> {
        const response = await this.getWebinarAudienceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for joinWebinar without sending the request
     */
    async joinWebinarRequestOpts(requestParameters: JoinWebinarOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling joinWebinar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webinars/{id}/join`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JoinWebinarRequestToJSON(requestParameters['joinWebinarRequest']),
        };
    }

    /**
     * Join webinar
     */
    async joinWebinarRaw(requestParameters: JoinWebinarOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebinarJoinResult>> {
        const requestOptions = await this.joinWebinarRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebinarJoinResultFromJSON(jsonValue));
    }

    /**
     * Join webinar
     */
    async joinWebinar(requestParameters: JoinWebinarOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebinarJoinResult> {
        const response = await this.joinWebinarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listWebinarQnA without sending the request
     */
    async listWebinarQnARequestOpts(requestParameters: ListWebinarQnARequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listWebinarQnA().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webinars/{id}/qna`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List webinar Q&A items
     */
    async listWebinarQnARaw(requestParameters: ListWebinarQnARequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WebinarQnAItem>>> {
        const requestOptions = await this.listWebinarQnARequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WebinarQnAItemFromJSON));
    }

    /**
     * List webinar Q&A items
     */
    async listWebinarQnA(requestParameters: ListWebinarQnARequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WebinarQnAItem>> {
        const response = await this.listWebinarQnARaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listWebinars without sending the request
     */
    async listWebinarsRequestOpts(requestParameters: ListWebinarsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['organizationId'] != null) {
            queryParameters['organization_id'] = requestParameters['organizationId'];
        }

        if (requestParameters['hostUserId'] != null) {
            queryParameters['host_user_id'] = requestParameters['hostUserId'];
        }

        if (requestParameters['statuses'] != null) {
            queryParameters['statuses'] = requestParameters['statuses'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString();
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webinars/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List webinars
     */
    async listWebinarsRaw(requestParameters: ListWebinarsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Webinar>>> {
        const requestOptions = await this.listWebinarsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WebinarFromJSON));
    }

    /**
     * List webinars
     */
    async listWebinars(requestParameters: ListWebinarsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Webinar>> {
        const response = await this.listWebinarsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publishWebinarAudience without sending the request
     */
    async publishWebinarAudienceRequestOpts(requestParameters: PublishWebinarAudienceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling publishWebinarAudience().'
            );
        }

        if (requestParameters['organizationID'] == null) {
            throw new runtime.RequiredError(
                'organizationID',
                'Required parameter "organizationID" was null or undefined when calling publishWebinarAudience().'
            );
        }

        if (requestParameters['eventPublication'] == null) {
            throw new runtime.RequiredError(
                'eventPublication',
                'Required parameter "eventPublication" was null or undefined when calling publishWebinarAudience().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webinars/{id}/audience/{organizationID}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters['organizationID'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EventPublicationToJSON(requestParameters['eventPublication']),
        };
    }

    /**
     * Vendor hosts and authorized company managers choose partner hospitals explicitly. Hospital administrators control access for their own staff. Withdrawing access preserves private participation history and sends cancellation updates to calendar subscriptions.
     * Publish or withdraw a vendor event for one hospital
     */
    async publishWebinarAudienceRaw(requestParameters: PublishWebinarAudienceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.publishWebinarAudienceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Vendor hosts and authorized company managers choose partner hospitals explicitly. Hospital administrators control access for their own staff. Withdrawing access preserves private participation history and sends cancellation updates to calendar subscriptions.
     * Publish or withdraw a vendor event for one hospital
     */
    async publishWebinarAudience(requestParameters: PublishWebinarAudienceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.publishWebinarAudienceRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for setHospitalWebinarAvailability without sending the request
     */
    async setHospitalWebinarAvailabilityRequestOpts(requestParameters: SetHospitalWebinarAvailabilityRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling setHospitalWebinarAvailability().'
            );
        }

        if (requestParameters['eventAvailability'] == null) {
            throw new runtime.RequiredError(
                'eventAvailability',
                'Required parameter "eventAvailability" was null or undefined when calling setHospitalWebinarAvailability().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webinars/{id}/availability`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EventAvailabilityToJSON(requestParameters['eventAvailability']),
        };
    }

    /**
     * Vendor hosts and authorized company managers choose partner hospitals explicitly. Hospital administrators control access for their own staff. Withdrawing access preserves private participation history and sends cancellation updates to calendar subscriptions.
     * Enable or disable event access for your hospital
     */
    async setHospitalWebinarAvailabilityRaw(requestParameters: SetHospitalWebinarAvailabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.setHospitalWebinarAvailabilityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Vendor hosts and authorized company managers choose partner hospitals explicitly. Hospital administrators control access for their own staff. Withdrawing access preserves private participation history and sends cancellation updates to calendar subscriptions.
     * Enable or disable event access for your hospital
     */
    async setHospitalWebinarAvailability(requestParameters: SetHospitalWebinarAvailabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.setHospitalWebinarAvailabilityRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for signalWebinar without sending the request
     * @deprecated
     */
    async signalWebinarRequestOpts(requestParameters: SignalWebinarRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling signalWebinar().'
            );
        }

        if (requestParameters['participantToken'] == null) {
            throw new runtime.RequiredError(
                'participantToken',
                'Required parameter "participantToken" was null or undefined when calling signalWebinar().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['participantToken'] != null) {
            queryParameters['participant_token'] = requestParameters['participantToken'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webinars/{id}/signal`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Requires a current authenticated browser session and a participant token for that same user and room.
     * WebRTC signaling websocket endpoint
     * @deprecated
     */
    async signalWebinarRaw(requestParameters: SignalWebinarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.signalWebinarRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Requires a current authenticated browser session and a participant token for that same user and room.
     * WebRTC signaling websocket endpoint
     * @deprecated
     */
    async signalWebinar(requestParameters: SignalWebinarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.signalWebinarRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for startWebinar without sending the request
     */
    async startWebinarRequestOpts(requestParameters: StartWebinarRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling startWebinar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webinars/{id}/start`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Start webinar
     */
    async startWebinarRaw(requestParameters: StartWebinarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Webinar>> {
        const requestOptions = await this.startWebinarRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebinarFromJSON(jsonValue));
    }

    /**
     * Start webinar
     */
    async startWebinar(requestParameters: StartWebinarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Webinar> {
        const response = await this.startWebinarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateWebinar without sending the request
     */
    async updateWebinarRequestOpts(requestParameters: UpdateWebinarOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateWebinar().'
            );
        }

        if (requestParameters['updateWebinarRequest'] == null) {
            throw new runtime.RequiredError(
                'updateWebinarRequest',
                'Required parameter "updateWebinarRequest" was null or undefined when calling updateWebinar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webinars/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateWebinarRequestToJSON(requestParameters['updateWebinarRequest']),
        };
    }

    /**
     * Update webinar
     */
    async updateWebinarRaw(requestParameters: UpdateWebinarOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Webinar>> {
        const requestOptions = await this.updateWebinarRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebinarFromJSON(jsonValue));
    }

    /**
     * Update webinar
     */
    async updateWebinar(requestParameters: UpdateWebinarOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Webinar> {
        const response = await this.updateWebinarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateWebinarQnA without sending the request
     */
    async updateWebinarQnARequestOpts(requestParameters: UpdateWebinarQnAOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateWebinarQnA().'
            );
        }

        if (requestParameters['itemID'] == null) {
            throw new runtime.RequiredError(
                'itemID',
                'Required parameter "itemID" was null or undefined when calling updateWebinarQnA().'
            );
        }

        if (requestParameters['updateWebinarQnARequest'] == null) {
            throw new runtime.RequiredError(
                'updateWebinarQnARequest',
                'Required parameter "updateWebinarQnARequest" was null or undefined when calling updateWebinarQnA().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webinars/{id}/qna/{itemID}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"itemID"}}`, encodeURIComponent(String(requestParameters['itemID'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateWebinarQnARequestToJSON(requestParameters['updateWebinarQnARequest']),
        };
    }

    /**
     * Moderate webinar Q&A item
     */
    async updateWebinarQnARaw(requestParameters: UpdateWebinarQnAOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebinarQnAItem>> {
        const requestOptions = await this.updateWebinarQnARequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebinarQnAItemFromJSON(jsonValue));
    }

    /**
     * Moderate webinar Q&A item
     */
    async updateWebinarQnA(requestParameters: UpdateWebinarQnAOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebinarQnAItem> {
        const response = await this.updateWebinarQnARaw(requestParameters, initOverrides);
        return await response.value();
    }

}
